### ISSUE TITLE
Add more details to README

### ISSUE THREAD

**Issue by davidak** [nix-community/disko#1]
This project looks useful. Can you give some more information?

- What is the status?
- What is the roadmap to upstream it to nixpkgs?
- Why not configure disk setup in `configuration.nix` using nix expression?
- How is it related to [nixpart](https://github.com/NixOS/nixpart)?

We need declarative disk layout configuration to make NixOS more user friendly! https://discourse.nixos.org/t/user-friendly-nixos-distro/1348/20?u=davidak

**Comment by Lassulus** [comment]
status is, we are finally doing something again, maybe we get feature complete before the steam runs out again :D
current features we would like to see before being feature complete:
- zfs
- raids via lvm
- btrfs subvolumes
- get some helper functions to create a list of needed packages for a given configuration

roadmap for upstreaming? none right now. maybe at some point, but we are slow working volunteers. First feature complete and if doesn't look to clunky/weird we will think about that.

why not in configuration.nix? well maybe at some point, but right now we are not part of nixpkgs and reading it out of configuration.nix again would be extra work.

I have no idea howto use nixpart
