### ISSUE TITLE
Fail on boot due to `zfs` mount point being non-empty.

### ISSUE THREAD

**Issue by nialov** [nix-community/disko#114]
# Preface

Whether this is an issue with `disko` or just more of a `zfs`+`systemd` general issue is beyond me. I am too much of a beginner with `zfs` at this point. Just looking for help mostly!

# Problem

With the following `partitions.nix`, the `/home` mount fails due to "non-empty directory there" (logs further below):

~~~nix
{ disks ? [ "/dev/disk/by-id/<my-disk>" ]
, ... }: {
  disk = {
    main = {
      type = "disk";
      device = builtins.elemAt disks 0;
      content = {
        type = "table";
        format = "gpt";
        partitions = [
          {
            type = "partition";
            name = "ESP";
            start = "0";
            end = "64MiB";
            fs-type = "fat32";
            bootable = true;
            content = {
              type = "filesystem";
              format = "vfat";
              mountpoint = "/boot";
            };
          }
          {
            type = "partition";
            name = "zfs";
            start = "128MiB";
            end = "100%";
            content = {
              type = "zfs";
              pool = "zroot";
            };
          }
        ];
      };
    };
  };
  zpool = {
    zroot = {
      type = "zpool";
      # mode = "mirror";
      rootFsOptions = {
        compression = "lz4";
        "com.sun:auto-snapshot" = "false";
      };
      # mountpoint = "/";

      datasets = {
        "root" = {
          zfs_type = "filesystem";
          mountpoint = null;
        };
        "root/nixos" = {
          zfs_type = "filesystem";
          mountpoint = "/";
        };
        "root/home" = {
          zfs_type = "filesystem";
          mountpoint = "/home";
        };
      };
    };
  };
}

~~~

The relevant error log parts from `sudo journalctl --boot` is as follows (cleaned some probably irrelevant logs from the middle):

~~~
Jan 14 09:37:46 nixos-desktop zfs[1008]: cannot mount 'zroot/root/home': mountpoint or dataset is busy
Jan 14 09:37:46 nixos-desktop systemd[1]: Mounted FUSE Control File System.
Jan 14 09:37:46 nixos-desktop systemd[1]: Mounted Kernel Configuration File System.
Jan 14 09:37:46 nixos-desktop systemd[1]: Finished Apply Kernel Variables.
Jan 14 09:37:46 nixos-desktop systemd[1]: Finished Create Static Device Nodes in /dev.
Jan 14 09:37:46 nixos-desktop systemd[1]: Reached target Preparation for Local File Systems.
Jan 14 09:37:46 nixos-desktop systemd[1]: home.mount: Directory /home to mount over is not empty, mounting anyway.
Jan 14 09:37:46 nixos-desktop systemd[1]: Mounting /home...
Jan 14 09:37:46 nixos-desktop systemd[1]: Starting Rule-based Manager for Device Events and Files...
Jan 14 09:37:46 nixos-desktop systemd[1]: Finished Load/Save Random Seed.
Jan 14 09:37:46 nixos-desktop systemd-udevd[1080]: Using default interface naming scheme 'v252'.
Jan 14 09:37:46 nixos-desktop systemd[1]: zfs-mount.service: Main process exited, code=exited, status=1/FAILURE
Jan 14 09:37:46 nixos-desktop systemd[1]: zfs-mount.service: Failed with result 'exit-code'.
Jan 14 09:37:46 nixos-desktop systemd[1]: Failed to start Mount ZFS filesystems.
~~~

Output from `zfs list` is as follows:

~~~
➜ zfs list
NAME               USED  AVAIL     REFER  MOUNTPOINT
zroot             19.9G   211G       24K  /zroot
zroot/root        19.9G   211G       25K  /zroot/root
zroot/root/home   9.23G   211G     9.23G  /zroot/root/home
zroot/root/nixos  10.7G   211G     10.7G  /zroot/root/nixos
~~~

Finally, even though the boot goes to emergency mode due to the failing mounting, simply continuing **will then successfully mount the `/home` mount without any further issues in use**. So this is a somewhat minor issue.

# What I expected

The `partitions.nix` should be valid as I understand it but might be plain wrong due to lack of `zfs` knowledge.

# Partial solutions

Setting

~~~nix
boot.zfs.forceImportAll = true;
~~~

will make the boot not enter emergency mode even with the same error messages found in the boot log.

I also tried mounting the `/` partition separately and noticed the the `/home` directory already contains an empty user directory. This seems to be the non-empty issue causing this whole bug. There is nothing else except an empty user directory. Deleting this will not persist as it appears again in the next boot or the boot after that. I suppose finding out what creates this empty user directory is crucial? 

Setting `users.users.nialov.createHome = lib.mkForce false;` did not change anything.

**Comment by Lassulus** [comment]
I usually run `zpool export -fa` after I installed the system before rebooting, so the pool can be cleanly imported after the reboot. It would be nice if disko could do this for you. But I'm unsure how it could do that :D

please report if this fixes the problem, makes it worse or has no impact on it.

apart from that I cannot spot any misconfiguration.

**Comment by nialov** [comment]
That you for the quick reply!

> I usually run `zpool export -fa` after I installed the system before rebooting, so the pool can be cleanly imported after the reboot. It would be nice if disko could do this for you. But I'm unsure how it could do that :D
> 
> please report if this fixes the problem, makes it worse or has no impact on it.

I tried this solution **without** reinstalling on my current system. So I just booted to an installation medium, mounted the zfs drives with `disko mount` and ran `zfs export -fa`. After some unmounting issues this ran successfully. But no change in the bug I have described here. As I understand you probably suggest doing a whole clean reinstall so this was just a hail mary on my part as I do not have an understanding about `zfs` yet. Might do one later but do not have the time atm :/

However, I did find a crude (and potentially damaging later?) method to remove the non-empty error by adding

~~~nix
{
  systemd.services."zfs-mount".serviceConfig.ExecStartPre =
    "${pkgs.zfs}/sbin/zfs mount -O -a";
]
~~~

to my configuration. The `-O` i.e. overlay option is the new thing to the previous `ExecStart` command of the `zfs-mount` service. It allows mounting on directories that are non-empty (i.e. it is potentially very dangerous) as I understand it. I could not override the `ExecStart` command (i.e. `zfs-mount".serviceConfig.ExecStart = lib.mkAfter "-O";`) as there is some weirdness in how it is actually added to the service config. So now it just runs the mount commands twice, but because the `ExecStartPre` command succeeds in mounting the `ExecStart` part probably does nothing (?).

**Comment by nialov** [comment]
Aaaaand an update: the bug has not disappeared, rather it appears sporadically/randomly. My guess, which probably is no big revelation, is that some `systemd` service generates the empty user directory and there is a race condition between the `zfs-mount` and that other service.

**Comment by Mic92** [comment]
Seems like this is better discussed in nixos. Disko only generates the implementation but is not responsible for how things are mounted in the end.

**Comment by nialov** [comment]
> Seems like this is better discussed in nixpkgs. Disko only generates the implementation but is not responsible for how things are mounted in the end.

I will post an issue on `nixpkgs`. The configuration generated by `disko` is (mainly) in the `fileSystems` attribute of the final config as I understand? I suppose that is the relevant part for creating an issue in `nixpkgs`.

**Comment by Mic92** [comment]
Yes. You can explore the result like this:

```
╭─[~/git/infra]─[ci]
nix-shell ╰─ % nix repl
Welcome to Nix 2.12.0. Type :? for help.

nix-repl> :lf github:nix-community/infra
Added 19 variables.

nix-repl> outputs.nixosConfigurations."build04.nix-community.org"
{ _module = { ... }; config = { ... }; extendModules = «lambda @ /nix/store/pm0s0wqyzr0vjpfcs423ckmy0222vslb-source/lib/modules.nix:329:23»; extraArgs = { ... }; options = { ... }; pkgs = { ... }; type = { ... }; }

nix-repl> outputs.nixosConfigurations."build04.nix-community.org".config.fileSystems
{ "/" = { ... }; "/boot" = { ... }; "/home" = { ... }; }

nix-repl> outputs.nixosConfigurations."build04.nix-community.org".config.fileSystems."/home"
{ autoFormat = false; autoResize = false; depends = [ ... ]; device = "zroot/root/home"; encrypted = { ... }; formatOptions = ""; fsType = "zfs"; label = null; mountPoint = "/home"; neededForBoot = false; noCheck = false; options = [ ... ]; }
```

**Comment by nialov** [comment]
> Thank you, I opted to not using a dataset for the /home/ to still continue using zfs-mount automount functionality. Switching to 
> legacy seems to be the only way to avoid the race condition.

> Can the automount functionality and using legacy mountpoints be mixed freely? I.e. using legacy for /home.

> This issue can be considered "fixed" for me as I now know what to avoid what the expected errors might be. You can close it if 
> deemed suitable or keep it open for future reference. I suppose this is a quite a major caveat when using the automount 
> functionality of zfs.

Using a legacy mountpoint for the `/home` dataset seems to be the only solution to avoid this race condition. You can check the discussion at <https://github.com/NixOS/nixpkgs/issues/212762> where I pasted the above quote if you want to check the short discussion.

Beyond that this issue can be considered solved for me.
