### ISSUE TITLE
Feature request: Btrfs subvolumes support

### ISSUE THREAD

**Issue by Baitinq** [nix-community/disko#13]
It would be really cool if this project supported btrfs. Has anyone started implementing this already? If not I might come around to doing it eventually.

EDIT: I mean btrfs subvolumes, sorry for not clarifying.

**Comment by Lassulus** [comment]
I would guess it should just work? since btrfs can be created with `mkfs.btrfs`? you can try and post any errors you encounter here I guess

**Comment by Baitinq** [comment]
@Lassulus sorry, to clarify I meant btrfs subvolumes

**Comment by Mic92** [comment]
That should not be very different from lvm: https://github.com/nix-community/disko/blob/master/lib/default.nix#L92

**Comment by Baitinq** [comment]
I might implement this in the future, thank you for your pointer @Mic92 . For now I am happy replacing btrfs subvolumes with lvm volumes. Maybe we leave this issue open in case anyone else wants this feature and "forces" me to implement it? :)

**Comment by Lassulus** [comment]
I can look into it when implementing raid support for lvm and zfs. Wanted to get this done until end of next week

**Comment by Lassulus** [comment]
I also added btrfs subvolumes to https://github.com/nix-community/disko/pull/27

**Comment by Baitinq** [comment]
> I also added btrfs subvolumes to #27
