### ISSUE TITLE
Support flag to switch mode in disko-mount

### ISSUE THREAD

**Issue by ktrinh-anduril** [nix-community/disko#132]
First off, thank you so much for your work! Disko has helped saved a lot of time in our embedded Nixos deployments. However, we recently run into a specific use case that is not currently implemented. We want to mount rootfs as readonly at runtime but want to make it read-writable at installation time, right now, `disko-mount` just use one set of flag that is specified using `mountOptions`, if we specify read-only mount flags there then the installation will fail since it needs to write to disk, but if we don't then it won't be mounted correctly at runtime.

It would be nice to have `disko-mount` accept an argument like `--installation-mode` or something similar as well as supporting another set of mount options in configurations.

I am willing to implement this feature and make a PR if the disko team thinks it's a desirable feature.

**Comment by Lassulus** [comment]
heyhey, thank you for your kind words!

this should already be possible, since the disko config is just nix code, you could parametrize it. doing something like:
```
{ lib, readOnly ? true }:
{
  disk.main = {
    type = "disk"
    content = {
      type = "filesystem";
      fs = "ext4";
      mountOptions = [ "defaults" ] ++ lib.optional readOnly "ro";
    };
  };
}
```

you can then pass the arg during installation, for example with the disko cli:
`disko --mode mount --arg readOnly false ./myDiskConfig.nix`

hopefully that is enough to support your usecase!

**Comment by ktrinh-anduril** [comment]
Thank you for the quick response! I didn't realize how flexible `disko` is! The parametrizing work well for our needs. Thank you again for your awesome work!
