### ISSUE TITLE
"ininite recursion encountered" on nixos-install

### ISSUE THREAD

**Issue by Siroj42** [nix-community/disko#157]
I followed the steps outlined in the quickstart guide, but when I execute `nixos-install`, it results in the following error:

```
error: infinite recursion encountered

       at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:478:28:

          477|         builtins.addErrorContext (context name)
          478|           (args.${name} or config._module.args.${name})
             |                            ^
          479|       ) (lib.functionArgs f);
(use '--show-trace' to show detailed location information)
```

Using the `--show-trace` argument shows that this recursion apparently happened

`while evaluating the module argument 'pkgs' in "/mnt/etc/nixos/configuration.nix"`

and the error disappears when I remove the lines

```
(pkgs.callPackage ./disko-config.nix {
  disks = ["/dev/vda"];
})
```

from the `imports` section of my configuration.nix (of course, it is then replaced by another error because no root file system is defined). Do you know what could be causing this error?

**Comment by Lassulus** [comment]
hmm, weird, can you try doing `(import ./disko-config { disks = [ "/dev/vda" ]; inherit lib; })` instead in the imports list?

**Comment by Siroj42** [comment]
I tried it and I'm getting this error now:

```
error: The option `disk' does not exist. Definition values:
       - In `/mnt/etc/nixos/configuration.nix':
           {
             vda = {
               content = {
                 format = "gpt";
                 partitions = [
           ...
```

**Comment by Mic92** [comment]
You need to import this file into `disko.devices`:

```
{
  disko.devices = import ./disko-config.nix { disks = [ "/dev/vda" ]; inherit lib; };
}
```

I just noticed this was wrong in our quickstart.md: https://github.com/nix-community/disko/pull/158
