### ISSUE TITLE
Using disko in a script does not prompt for LUKS password

### ISSUE THREAD

**Issue by Anomalocaridid** [nix-community/disko#164]
I'm trying to make a script to automate a NixOS installation from the installation media and I use disko to take care of partitioning. However, it seems like  whenever I run disko inside a script and use it to make a LUKS partition, it doesn't prompt for the password. It still shows it runs the `cryptSetup` commands in the output, though. It also fails to partition the disk and terminates with the message `No key available with this passphrase.`. Running the command directly in a terminal prompts for the password and formats the disk as expected, though.

The exact command I'm using is:

```bash
nix run github:nix-community/disko \
	--extra-experimental-features nix-command \
	--extra-experimental-features flakes \
	-- \
	--mode zap_create_mount /tmp/disko-config.nix \
	--arg disks '[ "/dev/vda" ]' ||
	exit 1
```
[This is the full script so far](https://github.com/Anomalocaridid/nixos-install/blob/main/nixos-install.sh)

[This is my disko config](https://github.com/Anomalocaridid/nixos-dotfiles/blob/main/disko-config.nix)

I run the script from a NixOS installation medium using this command:
`curl -s https://raw.githubusercontent.com/Anomalocaridid/nixos-install/main/nixos-install.sh | sudo bash`

**Comment by Mic92** [comment]
cc @phaer did you deal with passwords or was it disk encryption key only when working on `nixos-anywhere`?

**Comment by phaer** [comment]
@Mic92 I've used passwords as well, but always with ZFS native encryption, not LUKS.

iirc, @Lassulus mentioned that cryptsetup *does* ask for a passphrase in such cases, but the prompt does not show? Could that be the case for you as well @Anomalocaridid ?

**Comment by Anomalocaridid** [comment]
@phaer Maybe? I kind of doubt it.

It doesn't seem to wait for input when it gets to the `cryptsetup` commands when running my script, it just waits for a few seconds and continues without having me enter a password until it eventually errors out.

However, if I run it directly in a terminal, it stops at the password prompt until I enter something.

**Comment by Lassulus** [comment]
I guess the terminal is somehow not handled by disko if it ran other ways, I would suggest doing something like in https://github.com/nix-community/disko/issues/132

**Comment by Mic92** [comment]
> I guess the terminal is somehow not handled by disko if it ran other ways, I would suggest doing something like in #132

Would be worth documenting.

**Comment by Anomalocaridid** [comment]
@Lassulus I'm not sure I follow. Are you suggesting that I use the parameterization to pass a password to `cryptsetup` so I do not have to rely on it prompting me for it?

**Comment by Lassulus** [comment]
yeah, just parametrize the password (keyFile is what you want to set, you need to skip the trailing newline though, for example with echo -n) so you can set it during install but not set it in your actual nixos config

**Comment by Anomalocaridid** [comment]
Thanks! It works now!

**Comment by Anomalocaridid** [comment]
I was able to solve this without needing a keyfile by adding `</dev/tty` to the end of the command running `disko.` That made the prompts appear as if I ran the command directly.
