### ISSUE TITLE
Add `passwordFile` to set password for LUKS devices

### ISSUE THREAD

**Issue by tandy-1000** [nix-community/disko#165]
Using sops-nix we could set the password file as a secret, this would help make disko suitable for unattended partitioning of LUKS encrypted drives.

**Comment by Lassulus** [comment]
https://github.com/nix-community/disko/blob/master/types/luks.nix#L13 can do this already, you just write the password without a newline at the end into it.

**Comment by tandy-1000** [comment]
Oh, my mistake, thanks!
