### ISSUE TITLE
Nullable filesystem mountpoint

### ISSUE THREAD

**Issue by uningan** [nix-community/disko#169]
There is no option for a created, but not OS mounted, filesystem. I am not sure if there is some design limitations to avoid this. If there is not i can go with a PR.

**Comment by Lassulus** [comment]
You can usually set `mointpoint = null`

**Comment by uningan** [comment]
```
error: A definition for option `devices.disk.main.content.content.partitions."[definition 1-entry 1]".content.mountpoint' is not of type `An absolute path'. Definition values:
       - In `<unknown-file>': null
(use '--show-trace' to show detailed location information)
```

**Comment by Lassulus** [comment]
Huh then it got changed at some point or I'm mixing things up. Will fix it later
