### ISSUE TITLE
How to create a btrfs swapfile subvolume

### ISSUE THREAD

**Issue by Anomalocaridid** [nix-community/disko#179]
I am having difficulty figuring out how to create a btrfs swapfile subvolume.

Currently, my config does it manually, using postCreateHook like so:
```nix
"/swap" = {
  mountOptions = [ "noatime" ];
  postCreateHook = ''
    mount -t btrfs /dev/mapper/crypted /mnt
    btrfs filesystem mkswapfile --size ${memory} /mnt/swap/swapfile
    umount /mnt
  '';
};
```

However, I am not sure if this is the proper way to do so with `disko` or how to add the created swapfile to `swapDevices`.

**Comment by Lassulus** [comment]
there is currently now way to do this with disko. I guess we could add it, if we can find a nice interface for it, probably something similiar to `btrfs_subvol`

**Comment by Anomalocaridid** [comment]
Thank you. That is good to know. I guess I'll just use a swap partition for now.
