### ISSUE TITLE
more details what it can do and what it can't

### ISSUE THREAD

**Issue by mrVanDalo** [nix-community/disko#2]
more details on the readme would be great.

* can it calculate deltas between a given partition and a wanted partition? will you see log errors?
* does it delete partitions which are not defined?
* what happens definitions in the json are "wrong" (to much space is consumed, sdz does not exist, ... )
* where can I find the json definition schema ? for example for dm-crypt?

**Comment by Lassulus** [comment]
- no, the tool can only create everything from scratch. deltas would be hard
- well it doesn't create them when running, and as the partition table is wiped they won't exist afterwards, but also everything else is gone
- runtime errors
- for now there isn't a schema, at some point I would like to do this with nixos-options
