### ISSUE TITLE
called without required argument 'disko'

### ISSUE THREAD

**Issue by WilliamBehrens** [nix-community/disko#209]
When attempting to install from an iso using disko and following the quickstart guide I keep getting the following error.

![image](https://user-images.githubusercontent.com/35979547/233218341-90bc601e-6251-49ff-a72f-8ec1bd63bf52.png)

command: `nix --extra-experimental-features "flakes nix-command" run github:nix-community/disko -- --mode zap_create_mount disks.nix`

`disks.nix`:
```nix
{ disko, disks ? [ "/dev/vda" ], ...}: {
  imports = [
    disko.nixosModules.disko
  ];

  # Hybrid BIOS and UEFI boot
  disko.devices = {
    disk = {
      vda = {
        type = "disk";
        device = builtins.elemAt disks 0;
        content = {
          type = "table";
          format = "gpt";
          partitions = [
            # Bios boot fallback
            {
              name = "boot";
              type = "partition";
              start = "0";
              end = "1M";
              flags = [ "bios_grub" ];
            }

            # EFI Boot Partition
            {
              type = "partition";
              name = "ESP";
              start = "1M";
              end = "512M";
              bootable = true;
              content = {
                type = "filesystem";
                format = "vfat";
                mountpoint = "/boot";
              };
            }

            # Root partition
            {
              name = "root";
              type = "partition";
              start = "512MiB";
              end = "100%";
              part-type = "primary";
              bootable = true;
              content = {
                type = "btrfs";
                extraArgs = [ "-f" ];
                subvolumes = {
                  "/root" = {
                    mountpoint = "/";
                    mountOptions = [ "compress=zstd" "noatime" ];
                  };
                  "/home" = {
                    mountpoint = "/home";
                    mountOptions = [ "compress=zstd" "noatime" ];
                  };
                  "/nix" = {
                    mountpoint = "/nix";
                    mountOptions = [ "compress=zstd" "noatime" ];
                  };
                };
              };
            }
          ];
        };
      };
    };
  };
}
```

**Comment by lilyinstarlight** [comment]
Shouldn't it be called without `disko` and the `imports` like that, especially when called from CLI? Is that in the quickstart guide?

Also I think you'll need to remove the `type = "partition"` config lines after #196 (see the upgrade guide in the `docs` directory and the updated example config from the quickstart)

**Comment by WilliamBehrens** [comment]
The import is there as the file is normally part of a flake and would error out if that line wasn't present

**Comment by WilliamBehrens** [comment]
@lilyinstarlight Following your suggestion leaves me with 
![image](https://user-images.githubusercontent.com/35979547/233396137-89d16fbd-2515-4164-8e67-9c1904db61bb.png)

**Comment by Lassulus** [comment]
ah yeah, thats a breaking change which was merged a couple of days ago, there is an upgrading guide: https://github.com/nix-community/disko/blob/master/docs/upgrade-guide.md

**Comment by Lassulus** [comment]
also in a more general thing, the disko arg can't be passed when using the CLI because it doesn't know about the nixos module yet, Maybe thats unexpected and I will think about a fix. but for now it's better to keep this lines separated in different files when using the CLI. 

An alternative to using the CLI would be to run the disko output from the system closure. for example like this:

`$(nix build '.#nixosConfigurations.fnord.config.system.build.disko' --no-link --print-out-paths)`
