### ISSUE TITLE
How to use `diskoConfigurations` in a flake

### ISSUE THREAD

**Issue by Anomalocaridid** [nix-community/disko#216]
I am trying to use Disko with a flake, but I cannot figure out exactly what I need to do. So far, I was able to determine that I need to set `diskoConfigurations.<system-name>`, but I am at a loss for what exactly I set it to. I could not find any relevant documentation and I cannot figure it out by reading the source code (although that may be because I am still learning to use NixOS).

Here is my [flake.nix](https://github.com/Anomalocaridid/dotfiles/blob/nixos/flake.nix) and here is the [script](https://github.com/Anomalocaridid/dotfiles/blob/nixos/nixos-install.sh) I am running Disko from. When I run the script, I get an error saying `attribute 'disko' missing,` but I am not sure where to set such an attribute.

**Comment by akirak** [comment]
@Anomalocaridid Set `disko.devices` instead of `inputs.disko.devices` here:

https://github.com/Anomalocaridid/dotfiles/blob/950e0d713bfbc9cac485a3dd91d6d3000de477ec/flake.nix#L32-L35

**Comment by Anomalocaridid** [comment]
I did that, but I still get the same error. 

Just in case it's important, here's the full error message:
```
error: attribute 'disko' missing

       at /nix/store/jpjdaylsd0clkzr9cg4n43yg816hccca-disko/share/disko/default.nix:10:49:

            9|       # _file = toString input;
           10|       imports = lib.singleton { disko.devices = cfg.disko.devices; };
             |                                                 ^
           11|       options = {
       Did you mean disk?
(use '--show-trace' to show detailed location information)
```

**Comment by Anomalocaridid** [comment]
It works now! Thank you!
