### ISSUE TITLE
Use the module system to evaluate diskoFile

### ISSUE THREAD

**Issue by SuperSandro2000** [nix-community/disko#219]
I want to write the disk format option into the normal nixos configuration and access attributes like networking.hostname or import other nix files via imports.

**Comment by Lassulus** [comment]
you can do that alreadu?

**Comment by SuperSandro2000** [comment]
You can't. I tried using imports and it didn't work.

**Comment by Lassulus** [comment]
so, you install the module (either via flakes or one of the other ways described in the README). then you can write `disko.devices = ...` somewhere in your configuration. you can use all the usual nixos tools there. to run the formatScript you can do something like this:

`$(nix build --print-out-paths --no-link --extra-experimental-features 'nix-command flakes' --no-write-lock-file -L '.#nixosConfigurations."hetzner-cloud".config.system.build.disko')`

**Comment by SuperSandro2000** [comment]
I didn't know that. I tried supplying the file using module features via disko-file.nix.
