### ISSUE TITLE
deviceNumbering heuristic doesn't work for LVM partitions

### ISSUE THREAD

**Issue by seirl** [nix-community/disko#226]
I can't give `/dev/mapper/XXXX` to disko because deviceNumbering cannot detect it properly. I am not sure it is always correct to just use `${dev}${number}` when the prefix is `/dev/mapper`, so I can't just add it to the function as recommended.

It seems to me that it would be a lot more reliable to get the partition children either with sysfs or lsblk, instead of using this heuristic.

```
$ lsblk --json --paths -o NAME -n /dev/nvme0n1
{
   "blockdevices": [
      {"name":"/dev/nvme0n1",
         "children": [
            {"name":"/dev/nvme0n1p1",
               "children": [
                  {"name":"/dev/mapper/vg-lv",
                     "children": [
                        {"name":"/dev/mapper/vg-lv1"}
                     ]
                  },
               ]
            }
         ]
      }
   ]
}
```

**Comment by Lassulus** [comment]
Not sure what you want to do. Why do you need a table on a luks partition? Also we can't use lsblk in disko since we don't have access to stuff outside the sandbox and it would introduce impurities. Except if we can use it to generate the pwrtions purely without reading from the system

**Comment by seirl** [comment]
LVM, not luks. I have an LVM volume on my hypervisor that I use as the block device of a VM.

> Also we can't use lsblk in disko since we don't have access to stuff outside the sandbox and it would introduce impurities.

Ah, indeed. Would it make sense to add a way to override the partition scheme then?

**Comment by Lassulus** [comment]
ah, what is the correct numbering scheme for a table on a lv? wen can probably fix the code to use the correct numbering in that case?

**Comment by seirl** [comment]
It is the standard "append a number at the end". But I don't think it's guaranteed at all, /dev/mapper can contain anything, not only LVM partitions.

I guess we could have it and see if anyone complains later 😛

**Comment by Lassulus** [comment]
ah yeah, I guess we can add the default case of ${dev}${number} also for /dev/mapper and also add an option to the table type to override it in case the autodetection doesn't work?

**Comment by seirl** [comment]
Yeah, that sounds very reasonable, I opened a PR for the first part that's easy enough to write.
