### ISSUE TITLE
btrfs encryption with dmcrypt?

### ISSUE THREAD

**Issue by wbehrens-on-gh** [nix-community/disko#246]
as the title says, does disko support btrfs encryption using dmcrypt and is there an example?

**Comment by Lassulus** [comment]
do you mean btrfs inside a LUKS container or is this different?

**Comment by wbehrens-on-gh** [comment]
> do you mean btrfs inside a LUKS container or is this different?

Yes, I got confused, the examples only show using lvm.

**Comment by tiredofit** [comment]
I too am interested in this example of BTRFS within a LUKS container.

How I'd do it manually: ..

```
cryptsetup luksFormat /dev/disktocrypt 
cryptsetup luksOpen /dev/disktocrypt pool0_0
mkfs.btrfs /dev/mapper/pool0_0
mount /dev/mapper/pool0_0 /mnt
btrfs subvolume create /mnt/root 
....
```
