### ISSUE TITLE
BTRFS Swapfile

### ISSUE THREAD

**Issue by Lord-Valen** [nix-community/disko#262]
I'd like to be able to designate a swap subvolume and have disko automatically create a swapfile.
Related: https://github.com/nix-community/disko/issues/179

**Comment by Alxandr** [comment]
How about just adding a "type" to btrfs subvols, and allow a type of "swap"? If the type is "swap", a size (`swap.size`?) also needs to be configured, and if they are configured, disko creates the swap and configures nixos to use it.

**Comment by steveej** [comment]
is https://github.com/nix-community/disko/pull/440 enough to satisfy this issue?

**Comment by Mic92** [comment]
I think so.
