### ISSUE TITLE
`disko` is always formatting

### ISSUE THREAD

**Issue by yellowhat** [nix-community/disko#264]
Hi,
I have just started experimenting with `nixos` thanks to `nixos-anywhere`.

For now I am just testing on a VM with 2 disks: one for the OS and one for the data.

The `disk-config.nix` file is:

```nix
{ disks ? [ "/dev/vda" "/dev/vdc" ], ... }: {
  disk = {
    main = {
      type = "disk";
      device = builtins.elemAt disks 0;
      content = {
        type = "table";
        format = "gpt";
        partitions = [
          {
            name = "boot";
            start = "0";
            end = "1M";
            flags = [ "bios_grub" ];
          }
          {
            name = "ESP";
            start = "1M";
            end = "512M";
            bootable = true;
            content = {
              type = "filesystem";
              format = "vfat";
              mountpoint = "/boot";
            };
          }
          {
            name = "root";
            start = "512M";
            end = "100%";
            content = {
              type = "filesystem";
              format = "xfs";
              mountpoint = "/";
            };
          }
        ];
      };
    };

    data = {
      type = "disk";
      device = builtins.elemAt disks 1;
      content = {
        type = "table";
        format = "gpt";
        partitions = [
          {
            name = "data";
            start = "0%";
            end = "100%";
            content = {
              type = "filesystem";
              format = "xfs";
              mountpoint = "/data";
            };
          }
        ];
      };
    };
  };
}
```

I have noticed that every time I run:

```console
nix run github:numtide/nixos-anywhere -- --flake .#server --debug k8s@127.0.0.1
``` 
both disks are formatted.

For the OS disk that's absolutely fine as I would prefer to reinstall the OS from scratch.

For the data disk I am not able to find an option in `disko` that allows to not format a partition if the condition are already met, for example the table is already `gpt`, the size is correct, the filesystem is correct, ...

That behaviour should be more aligned to a declarative approach.

Infact the Ansible task `community.general.parted` and `community.general.filesystem` have this type of behaviour.

Thanks

**Comment by phaer** [comment]
Yes, that's expected behavior. Might be a good idea to mention that more explicitly in the README.

> For the data disk I am not able to find an option in disko that allows to not format a partition if the condition are already met, for example the table is already gpt, the size is correct, the filesystem is correct, ...

It's always a balance between features and the complexity of the implementation. PRs would be welcome, but what's your use case here? You should be good to re-install by just omitting your data disk from the config here.

**Comment by yellowhat** [comment]
Super I will keep an eye on the project.
Thanks

**Comment by Toomoch** [comment]
Is this still expected? I just nuked my installation (luckily without any data, as it was new) after changing my ZFS dataset on a secondary drive. I assumed at most it would format the secondary drive, but apparently it nuked every drive included in my disko configuration.

What would be the right procedure for updating my ZFS dataset without formatting the drives?
Thanks

**Comment by Lassulus** [comment]
if you use diskoScript it will format all the drives, since today (https://github.com/nix-community/disko/pull/568) this shouldn't happen anymore if you just use the formatScript with --mode format or --mode create. but since this was merged today it's still not fully tested :)
