### ISSUE TITLE
`diskoScript` depends on `bash` but does not add it to PATH

### ISSUE THREAD

**Issue by fooker** [nix-community/disko#279]
Running `system.build.diskoScript` from a environment  without bash (like a systemd service) fails. This is because of `bash` not being inherited from the calling environment and not being added to `PATH` in the script itself.

The failing call seems be right here: https://github.com/nix-community/disko/blob/4823509bb3b014dc85abefc13efcfa076d36338a/lib/default.nix#L264

The work-around is to add `pkgs.bash` to the calling environment. But it would be convenient to have `bash` added to the `PATH` of the scripts or infer it from the calling script.

**Comment by Lassulus** [comment]
Why was this reopened? Did I forget it somewhere?

**Comment by phaer** [comment]
Not sure either, tbh - must have been a wrong click or so?have
