### ISSUE TITLE
Feature request: Support tmpfs mounts

### ISSUE THREAD

**Issue by Baitinq** [nix-community/disko#28]
It would be extremely useful if disko supported creating tmpfs partitons. 

As an example, I use a tmpfs partition mounted on / to achieve non persistance.

e.g.
`mount -t tmpfs none /`

**Comment by Lassulus** [comment]
hmm, but adding a tmpfs device is already quite easy with nixos. you just add them to `fileSystems."/some/path" = { device = "tmpfs"; fsType = "tmpfs" };`

**Comment by Baitinq** [comment]
@Lassulus but that wouldnt work with the tsp-create/mount bootstraping workflow right?

**Comment by Lassulus** [comment]
you don't actually need a root partition for /mnt. Problem with tmpfs is, that the current config is device oriented and tmpfs doesn't really have a device so question would be where we should put it in the config.

**Comment by Baitinq** [comment]
@Lassulus that's true. Maybe we could have a special none device? Maybe @Mic92 could help us with a better idea

**Comment by Lassulus** [comment]
so with the new topLevel oriented config, we could actually have a tmpfs device type (like mdadm/zfs). there would be no nesting so it would just be an `attrsOf tmpfs` or `listOf tmpfs`

**Comment by Mic92** [comment]
I think this could be even generalized a bit. There is a bunch of are bunch filesystems that do not need a device: nfs, fuse...

**Comment by Mic92** [comment]
filesystem could be allowed on toplevel maybe.

**Comment by Lassulus** [comment]
> filesystem could be allowed on toplevel maybe.

maybe you have an example?

**Comment by Mic92** [comment]
```
  deviceLessFilesystem = {
    tmp = {
      type = "deviceLessFilesystem";
      format = "tmpfs";
      mountpoint = "/tmp";
    };
  };
```

**Comment by Mic92** [comment]
Or we add a special device called `nodev`?

**Comment by Lassulus** [comment]
we now have https://github.com/nix-community/disko/pull/70, hopefully that's good enough :)
