### ISSUE TITLE
Support for BTRFS subvolumes to be created but not mounted

### ISSUE THREAD

**Issue by rogarb** [nix-community/disko#288]
Hi,

I have a slightly more complex BTRFS layout than the classical "flat" one:
```
$ sudo btrfs subvolume list -t -a /mnt
ID	gen	top level	path	
--	---	---------	----	
256	1051	5		DATA
257	11	5		SYSTEM
258	15	5		VOLATILE
259	924	258		<FS_TREE>/VOLATILE/cache
260	1637	257		<FS_TREE>/SYSTEM/nix
261	1054	256		<FS_TREE>/DATA/nixos
262	14	256		<FS_TREE>/DATA/home
263	1901	262		<FS_TREE>/DATA/home/user
264	1635	259		<FS_TREE>/VOLATILE/cache/user
265	1836	256		<FS_TREE>/DATA/nixos-config
```
In this layout, the subvolumes `DATA`, `SYSTEM` and `VOLATILE` are not meant to be mounted but rather act as upper level "hidden folder" for other subvolumes.

I hoped to be able to reproduce this layout by declaring such "hidden suvolumes" with:
```
[...]
content = {
  type = "btrfs";
  [...]
  subvolumes = {
    "DATA" = { };
    "SYSTEM" = { };
    "VOLATILE" = { };
    [...]
  };
};
```
as I could read in the btrfs related example file, but this leads to having those filesystems mounted as `/<NAME>`, which I don't want.
They need to be declared though in order to create the subvolumes they contain, otherwise `disko` raises an error.

I came up with [a solution](https://github.com/rogarb/disko/tree/btrfs-fix) by adding a `dontMount` option for the subvolumes, and I modified `_mount` accordingly.

Is that a good solution? If so I shall open a PR.

**Comment by cvoges12** [comment]
@rogarb Shouldn't this issue be closed as the solution has already been merged?

**Comment by rogarb** [comment]
> @rogarb Shouldn't this issue be closed as the solution has already been merged?

Yes sorry for the delay.
