### ISSUE TITLE
Label disks?

### ISSUE THREAD

**Issue by yajo** [nix-community/disko#29]
[In the installation instructions](https://nixos.org/manual/nixos/stable/#sec-installation-installing), it seems recommended to identify disks by label (`/dev/disk/by-label/nixos` and friends).

It would be very nice if disko could add labels to disks when creating the filesystems.

**Comment by Baitinq** [comment]
I'll implement this as soon as #27 is merged

**Comment by Mic92** [comment]
I think #27 also add create options for mkfs to make this feasible.

**Comment by Baitinq** [comment]
@Mic92 I dont think you can use mkfs to label a partition, but I might be wrong on that.

**Comment by Mic92** [comment]
Yeah I also think it needs to be done per filesystem: 

Fileystem | package | set label | show label
-- | -- | -- | --
ext2/ext3/ext4 | e2fsprogs | sudo e2label /dev/sda1 NEUES_LABEL sudo tune2fs -L NEUES_LABEL /dev/sda1 | sudo e2label /dev/sda1  sudo tune2fs -l /dev/sda1
ReiserFS | reiserfsprogs | sudo reiserfstune -l NEUES_LABEL /dev/sda1 | sudo debugreiserfs
JFS | jfsutils | sudo jfs_tune -L NEUES_LABEL /dev/sda1 | sudo jfs_tune -l
XFS | xfsprogs | xfs_admin -L NEUES_LABEL /dev/sda1 | xfs_admin -l
FAT | dosfstools | sudo fatlabel /dev/sdb1 NEUES_LABEL | sudo fatlabel /dev/sdb1
FAT | mtools | sudo mlabel -i /dev/sdb1 ::NEUES_LABEL | sudo mlabel -i /dev/sdb1 -s ::
FAT | mtools und Skript (siehe unten) | sudo ./set_msdos_label.sh /dev/sdb1 NEUES_LABEL |  
NTFS | ntfs-3g (ab Ubuntu 11.10) | sudo ntfslabel /dev/sdb1 NEUES_LABEL | sudo ntfslabel /dev/sdb1
Swap | util-linux | sudo swaplabel -L NEUES_LABEL /dev/sda1 | sudo swaplabel /dev/sda1

**Comment by yajo** [comment]
According to https://github.com/nix-community/disko/pull/30/files#r956295248, a workaround for disk labeling is to use a GPT table and set the label as `part-type`.

**Comment by Lassulus** [comment]
This should be done in #31
