### ISSUE TITLE
error: attribute 'disks' missing

### ISSUE THREAD

**Issue by lutzgo** [nix-community/disko#296]
Hey thank you for this great piece of software. I ran into an issue I could not fix nor determine the cause of. The following disko-file of mine worked for the commands
`nix run github:nix-community/disko --no-write-lock-file -- -m create`
and
`nix run github:nix-community/disko --no-write-lock-file -- -m create`.

So my layout is created and mounted. But when I try to build my system (`nix build .#nixosConfigurations.<hostname>.config.system.build.toplevel`) with the same disko-file, I get the following error:
```
error: attribute 'disks' missing

       at /nix/store/b6vnb230hgq98bbp7xpgszm7bk2m0bz5-source/lib/modules.nix:506:28:

          505|         builtins.addErrorContext (context name)
          506|           (args.${name} or config._module.args.${name})
             |                            ^
          507|       ) (lib.functionArgs f);
(use '--show-trace' to show detailed location information)
```

Here is my disko-file:
```
{
  disks ? [
    "/dev/disk/by-id/nvme-Samsung_SSD_960_EVO_1TB_XXXXXXXXXXXXXXX"
  ],
  ...
}: {
  disko.devices = {
    disk.nvme = {
      type = "disk";
      device = builtins.elemAt disks 0;
      content = {
        type = "table";
        format = "gpt";
        partitions = [
          {
            name = "bootcode";
            start = "0";
            end = "1M";
            part-type = "primary";
            flags = ["bios_grub"];
          }
          {
            name = "efiboot";
            fs-type = "fat32";
            start = "1MiB";
            end = "1GiB";
            bootable = true;
            content = {
              type = "filesystem";
              format = "vfat";
              mountpoint = "/boot";
            };
          }
          {
            name = "swap";
            start = "1GiB";
            end = "17GiB";
            content = {
              type = "swap";
              randomEncryption = true;
            };
          }
          {
            name = "zroot";
            start = "17GiB";
            end = "100%";
            content = {
              type = "zfs";
              pool = "rpool";
            };
          }
        ];
      };
    };
    zpool = {
      rpool = {
        type = "zpool";
        rootFsOptions = {
          acltype = "posixacl";
          canmount = "off";
          checksum = "edonr";
          compression = "zstd";
          dnodesize = "auto";
          encryption = "aes-256-gcm";
          keyformat = "passphrase";
          keylocation = "prompt";
          mountpoint = "none";
          normalization = "formD";
          relatime = "on";
          xattr = "sa";
          "com.sun:auto-snapshot" = "false";
        };
        options = {
          ashift = "12";
          autotrim = "on";
        };
        postCreateHook = ''
          zfs snapshot rpool@empty
        '';

        datasets = {
          # zfs uses cow free space to delete files when the disk is completely filled
          reserved = {
            options = {
              canmount = "off";
              mountpoint = "none";
              reservation = "5GiB";
            };
            type = "zfs_fs";
          };
          home = {
            type = "zfs_fs";
            options.mountpoint = "legacy";
            mountpoint = "/home";
            options."com.sun:auto-snapshot" = "true";
          };
          persist = {
            type = "zfs_fs";
            options.mountpoint = "legacy";
            mountpoint = "/persist";
            options."com.sun:auto-snapshot" = "true";
          };
          nix = {
            type = "zfs_fs";
            options.mountpoint = "legacy";
            mountpoint = "/nix";
            options = {
              atime = "off";
              canmount = "on";
              "com.sun:auto-snapshot" = "true";
            };
          };
          root = {
            type = "zfs_fs";
            options.mountpoint = "legacy";
            mountpoint = "/";
          };
        };
      };
    };
  };
}
```

**Comment by Lassulus** [comment]
hey thank you. The error is in how you integrate your disko-file into your configuration I guess. do you just use imports = [ ./disko-file ]; ?

**Comment by lutzgo** [comment]
Wow, thank you for coming back so fast. In fact I use it as a module (freely adapted from [Setting up my machines: nix style](https://aldoborrero.com/posts/2023/01/15/setting-up-my-machines-nix-style/). Here is my complete configuration: [nix-it-up](https://codeberg.org/lutzgo/nix-it-up).

**Comment by Lassulus** [comment]
ah, so the problem is disks is not in specialArgs and the nixos import functionality then tries to find disks in specialArgs and gives up if it's not there. sadly this is one of the points where nixos modules are not lazy.

for a better solution (although I haven't tested that yet) I would suggest creating an option or harcoding the device in the disko config without that fancy arg stuff (which I only introduced because the tests needed it this way, but it's basically gone in my big refactor here: https://github.com/nix-community/disko/pull/294)

if you want to try out the options method, do something like this:
```
{ config, lib, ... }: {
  options.disks = lib.mkOption {
    type = lib.types.listOf lib.types.str;
    default = [ "/dev/disk/by-id/nvme-Samsung_SSD_960_EVO_1TB_XXXXXXXXXXXXXXX" ];
  };
  disko.devices = {
    disk.nvme = {
      type = "disk";
      device = builtins.elemAt config.disks 0;
      content = {
      .... same as before ....
```

you can then override that anywhere in your nixos configuration with 

```
disks = [ "/dev/someotherdev" ];
```

but if you don't really want to change disks at some point, you can just hardcode it by changing your config into this:

```
  disko.devices = {
    disk.nvme = {
      type = "disk";
      device = "/dev/disk/by-id/nvme-Samsung_SSD_960_EVO_1TB_XXXXXXXXXXXXXXX";
      content = {
      .... same as before ....
```

hopefully that made it clear, if you have more questions, feel free to ask here :)

**Comment by Lassulus** [comment]
sadly the module method breaks the cli args method, I still to find a better way in the CLI for that :) but maybe I rewrite the CLI to just use a nixos config and then it extracts the create and mount scripts from there.

**Comment by lutzgo** [comment]
Thank you very much. I tried the first solution just out of curiosity, but it threw an error, so I went with the easy (hardcoded, disk-specific) way. Maybe I have try the harder way, when I need it with another machine.

Thank you for fixing this.
