### ISSUE TITLE
Documentation errors ?

### ISSUE THREAD

**Issue by mrVanDalo** [nix-community/disko#3]
* I think this you mean `disko.create` [here](https://github.com/nix-community/disko#master-boot-record) ? 
`(pkgs.writeScriptBin "tsp-create" (disko.mount cfg))`

* You use https://cgit.lassul.us/disko/  [here](https://github.com/nix-community/disko#master-boot-record), don't you mean https://github.com/nix-community/disko/?

* Why use a json file for configuration, wouldn't be it nicer to use nix to define the partition table?

**Comment by Mic92** [comment]
`disco.create` was fixed. I would agree with the rest. I'm pretty sure, @Lassulus would accept your PR rather quickly.

**Comment by Lassulus** [comment]
guess this is all fixed now
