### ISSUE TITLE
Can't rollback zfs dataset before mounting drives

### ISSUE THREAD

**Issue by kaikikokuke** [nix-community/disko#312]
First of all thanks for the great and exciting project and everyone working on it!

I want to have an impermanent root with zfs. I have the following **zfs.nix** file for setting up my disk:

```
{disks ? ["/dev/vdx"], ...}: {
  disko.devices = {
    disk = {
      x = {
        type = "disk";
        device = builtins.elemAt disks 0;
        content = {
          type = "gpt";
          partitions = {
            ESP = {
              size = "512M";
              type = "EF00";
              content = {
                type = "filesystem";
                format = "vfat";
                mountpoint = "/boot";
              };
            };
            zfs = {
              size = "100%";
              content = {
                type = "zfs";
                pool = "zroot";
              };
            };
          };
        };
      };
    };
    zpool = {
      zroot = {
        type = "zpool";
        rootFsOptions = {
          "com.sun:auto-snapshot" = "false";
          acltype = "posixacl";
          # ashift = "13";
          canmount = "off";
          compression = "zstd";
          devices = "off";
          dnodesize = "legacy";
          encryption = "aes-256-gcm";
          keyformat = "passphrase";
          # keylocation = "file:///tmp/secret.key";
          keylocation = "prompt";
          mountpoint = "/";
          normalization = "formD";
          relatime = "on";
          xattr = "sa";
        };
        # mountpoint = "/";
        postCreateHook = ''
          zfs set keylocation="prompt" "zroot";
        '';

        datasets = {
          "local" = {
            type = "zfs_fs";
            options.mountpoint = "none";
          };
          "local/root" = {
            type = "zfs_fs";
            options.mountpoint = "legacy";
            mountpoint = "/";
            postCreateHook = ''
              zfs snapshot zroot/local/root@blank
            '';
          };
          "local/nix" = {
            type = "zfs_fs";
            mountpoint = "/nix";
          };
          "safe" = {
            type = "zfs_fs";
            options.mountpoint = "none";
          };
          "safe/home" = {
            type = "zfs_fs";
            mountpoint = "/home";
            options.mountpoint = "legacy";
          };
          "rpool/safe/presist" = {
            type = "zfs_fs";
            mountpoint = "/presist";
            options.mountpoint = "legacy";
          };
        };
      };
    };
  };
}
```

I have setup disko as a NixOS module in a flake and also using nixos-unstable for nixpkgs like so:

```
inputs = {
    # Disko for partitioning
    disko.url = "github:nix-community/disko";
    disko.inputs.nixpkgs.follows = "nixpkgs";
};

outputs = {self, disko, ...} 
{
    nixosConfigurations = {
      machine = nixpkgs.lib.nixosSystem {
        specialArgs = {inherit inputs outputs;};
        modules = [
          ./hosts/machine/configuration.nix
          sops-nix.nixosModules.sops
          disko.nixosModules.disko
          ./hosts/machine/zfs.nix
          {
            _module.args.disks = ["/dev/nvme0n1"];
          }
        ];
      };
    };
}
```

the dataset is not rolled back to the snapshot when I add this to the config:

```
{
  boot.initrd.postDeviceCommands = lib.mkAfter ''
    zfs rollback -r zroot/local/root@blank
  '';
}
```
I also did not have success changing the disk configuration by adding **_preMountHook_** to the device config file like so:

```
...
        datasets = {
          "local" = {
            type = "zfs_fs";
            options.mountpoint = "none";
          };
          "local/root" = {
            type = "zfs_fs";
            options.mountpoint = "legacy";
            mountpoint = "/";
            postCreateHook = ''
              zfs snapshot zroot/local/root@blank
            '';
          
            preMountHook = ''
              zfs rollback zroot/local/root@blank
            '';

          };
          "local/nix" = {
            type = "zfs_fs";
            mountpoint = "/nix";
          };
          "safe" = {
            type = "zfs_fs";
            options.mountpoint = "none";
...
```

Are there any other ways of achieving this, which I have overlooked?

Thanks in advance for any answers.

**Comment by phaer** [comment]
> I also did not have success changing the disk configuration by adding preMountHook to the device config file like so:

Those hooks only run when disko runs, while the disk is partitioned. So `postCreateHook` is the right place to create the snapshot, but `preMountHook` is probably not what you want if it should be rolled back to a blank state on each boot.

> the dataset is not rolled back to the snapshot when I add this to the config:

Can you verify if `zfs rollback -r zroot/local/root@blank` is actually executed during boot? Does it log an error? (i.e. if you have [boot.initrd.systemd.enable](https://search.nixos.org/options?channel=23.05&from=0&size=50&sort=relevance&type=packages&query=initrd.systemd) enabled in your `configuration.nix`, `boot.initrd.postDeviceCommands` would not apply.

You could also check whether that command works from a running system (would probably need to be hard rebooted afterwards)

**Comment by kaikikokuke** [comment]
Thanks @phaer for the quick and helpful reply. 

> Can you verify if zfs rollback -r zroot/local/root@blank is actually executed during boot? Does it log an error? 

No. I  can't seem to find any logs indicating that it is running.

> i.e. if you have [boot.initrd.systemd.enable](https://search.nixos.org/options?channel=23.05&from=0&size=50&sort=relevance&type=packages&query=initrd.systemd) enabled in your configuration.nix, boot.initrd.postDeviceCommands would not apply.

Yes I have `boot.initrd.systems.enable` set to `true`. That would explain why I can't see the command being run.

> You could also check whether that command works from a running system (would probably need to be hard rebooted afterwards)

Yes `zfs rollback -r zroot/local/root@blank`works. I needed to hard reboot the machine afterwards. 

Is it correct then, that I need to write a systemd unit file which does the rollback before any zfs datasets are mounted? Do you have any suggestions on how to do this?

**Comment by phaer** [comment]
> Is it correct then, that I need to write a systemd unit file which does the rollback before any zfs datasets are mounted? Do you have any suggestions on how to do this?

Yes, that's exactly what's needed here as the (synchronous, scripted) `boot.initrd.postDeviceCommands` isn't run anymore.

i.e. copied from https://matrix.to/#/#impermanence:nixos.org:
  ```
  boot.initrd.systemd.services.rollback = {
    description = "Rollback ZFS datasets to a pristine state";
    serviceConfig.Type = "oneshot"
    unitConfig.DefaultDependencies = "no";
    wantedBy = [
      "initrd.target"
    ]; 
    after = [
      "zfs-import-zroot.service"
    ];
    before = [ 
      "sysroot.mount"
    ];
    path = with pkgs; [
      zfs
    ];
    script = ''
      set -ex
      zfs rollback -r zroot/local/root@blank && echo "rollback complete"
    '';
  };
```

**Comment by iFreilicht** [comment]
It seems that this has been solved. Feel free to re-open if I missed something :)
