### ISSUE TITLE
Support clearing partition data before creation for GPT type

### ISSUE THREAD

**Issue by ktrinh-anduril** [nix-community/disko#315]
Hi, I'm currently running into an issue where if I run the creation script for a device of type `gpt` more than once, after the first time, it will always fail unless I do `sgdisk -Z` since it looks like sgdisk rightly refuses to destroy the current partitioning data. It would be nice if there is an option in disko that enables running `sgdisk -Z` before starting the usual creation of the device.

**Comment by Mic92** [comment]
If this is really an issue we probably should just use sgdisk -Z by default.

**Comment by Lassulus** [comment]
We have the destroyScript or diskoScript which do that. IMHO create alone shouldn't be destructive

**Comment by ktrinh-anduril** [comment]
Thank you! I didn't know destroyScript existed, I will use that instead
