### ISSUE TITLE
More deterministic output?

### ISSUE THREAD

**Issue by yajo** [nix-community/disko#32]
I'm having a common problem with disko. It seems to expect all binaries to be reachable within the script context.

That has its pros and its cons. The pro is that you can use the package version you want, as long as it is exposed in the script's `$PATH`. The con is that it's not very ergonomic unless you're running in a NixOS machine with these imports present: https://github.com/nix-community/disko/blob/adf901d58155ca268d15351fff164d3ef38a0890/tests/lib.nix#L29-L32

My specific use case: using hetzner's rescue system (currently based on Debian 11) to format the drives using disko and install nixos. Thus, I'm not on a nixos machine and disko becomes too unpredictable.

My current solution is to wrap the script within an environment that contains all those dependencies, like this:

```nix
let
  pkgs = import <nixpkgs> {};
  tsp-create = import ./disko-create;
  wrapScript = pkgs: script:
    let
      diskoEnv = pkgs.symlinkJoin {
        name = "diskoEnv";
        paths = with pkgs; [
          # Device and partition tools
          cryptsetup
          lvm2.bin
          mdadm
          parted

          # Packages that provide a mkfs.* binary
          btrfs-progs
          dosfstools
          e2fsprogs
          f2fs-tools
          nilfs-utils
          util-linux
          xfsprogs
        ];
      } ;
    in pkgs.writeScript "wrapped" ''
      #!${pkgs.bash}/bin/bash
      export PATH=${diskoEnv}/bin:$PATH
      ${tsp-create}
    '';
```

As you can see, this is very anti-ergonomic and required a lot of research time to see which packages provide the binaries that disko expects to be present.

Options to fix the problem:
1. Disko can provide a helper function that returns such an environment and the script wrapper. Quite similar to upstreaming that snippet and adding some tests to it.
2. Disko accepts a `pkgs` input, from where to obtain all packages. Then, replace all calls to `parted` for `${pkgs.parted}/bin/parted`, and the same for all other binaries.

I guess option 1 fits better. What do you think?

**Comment by Lassulus** [comment]
i would create a meta field called dependencies. which would return a list of packages or alternatively an environment.

**Comment by zimbatm** [comment]
https://github.com/abathur/resholve might also come in handy

**Comment by Lassulus** [comment]
I guess this is now done. the *Script outputs (from default.nix) now set their PATH to have all dependencies they need. If there is still more to do. please reopen or open a new issue
