### ISSUE TITLE
Why is `keyFile` deprecated?

### ISSUE THREAD

**Issue by StillerHarpo** [nix-community/disko#320]
I want to generate a encrypted disk with `nixos-anywhere`. Therefore I use this command:
```bash
nixos-anywhere \
  --disk-encryption-keys /tmp/secret.key <(echo -n $(pass nixosRpi4Encryption)) \
 ...
```
With `keyFile = "/tmp/secret.key";` it works. But with `settings.keyFile=/tmp/secret.key` `luks` fails on startup, because it want's to unlock with `/tmp/secret.key` which isn't available

**Comment by Lassulus** [comment]
Ah yeah that's indeed right. We should probably rename keyFile to passwordFile or installKeyFile to make this clear and dedeprecate it :)

**Comment by Lassulus** [comment]
PR would be appreciated since I'm quite busy on cccamp right now

**Comment by StillerHarpo** [comment]
Done https://github.com/nix-community/disko/pull/323

**Comment by dehnert** [comment]
With the PR merged, can this issue be closed?

**Comment by iFreilicht** [comment]
Yeah I'd say so. Thank you for bringing it up!
