### ISSUE TITLE
Setting luks sector size leads to error "Device size is not aligned to requested sector size."

### ISSUE THREAD

**Issue by nadir-ishiguro** [nix-community/disko#328]
Hi, 
thank you a lot for this amazing tool. 

I'm not able to figure out how to specify extraArgs for luks partitions. I'm specifically interested in setting sector size and encryption algorithms, which I normally do manually with `cryptsetup luksFormat --sector-size 4096` (for example).

I figured using something like `extraArgs = ["--sector-size 4096"];` would work, but that's apparently not an option.

Am I missing something obvious?

**Comment by phaer** [comment]
Close, it's called `extraFormatArgs`, https://github.com/nix-community/disko/blob/4eed2457b053c4bbad7d90d2b3a1d539c2c9009c/lib/types/luks.nix#L70

**Comment by nadir-yttrium** [comment]
Thank you very much. 

               ```
 extraFormatArgs = [
                  "--sector-size 4096"
                ];
```
 Was what I was looking for.

Sadly, there's [this issue](https://gitlab.com/cryptsetup/cryptsetup/-/issues/585) with cryptsetup where it can't respect the sector size setting for partitions that don't align with it. 

You get met with `Device size is not aligned to requested sector size.`

I remember having that issue in the past and so far the only solution seems to be to make sure any created partitions have the proper size to begin with. No problem for manual setups, but maybe something to consider for disko.

**Comment by phaer** [comment]
> No problem for manual setups, but maybe something to consider for disko.

Can you elaborate what we should do on the disko-side about this? Automatically calculating one from the others isn't trivial to get right, especially as we currently just pass the sizes to cli tools but don't really have a layer where that would fit, i think. Curios about what you've got in mind :)

(if you find time to update title, this might be easier to find; as the thread isn't really about `extraFormatArgs` anymore?

**Comment by nadir-yttrium** [comment]
Sorry, I hadn't noticed your answer until now. I hope the changed title fits the issue better.

As I have absolutely no idea how disko works and am very new to nix, I'm short on ideas on how to solve the issue. 

On the manual side, in my experience it's enough to make sure that partitions are 1MiB-aligned. If disko already does that, I'm not sure what goes wrong.

**Comment by rudolfvesely** [comment]
`sgdisk` needs alignment. More info in: https://github.com/nix-community/disko/pull/362

**Comment by iFreilicht** [comment]
It seems that #362 has fixed this. I'll close it for now, but feel free to re-open if the issue persists.
