### ISSUE TITLE
Error on nixos-install

### ISSUE THREAD

**Issue by oneproxima** [nix-community/disko#332]
Warning: New to disko and relatively new to Nix

When: when running nixos-install -v
Error:

```
evaluating file '/mnt/etc/nixos/disko-config.nix'
error: 'functionArgs' requires a function

       at /nix/store/p2bmnfbfp2cpqlsa0nffb9c9zc8ybwml-nixos-23.05.2975.a16f7eb56e88/nixos/lib/trivial.nix:443:10:

          442|     then f.__functionArgs or (lib.functionArgs (f.__functor f))
          443|     else builtins.functionArgs f;
             |          ^
```

my /mnt/etc/nixos/configuration.nix

```
imports =
  [ # Include the results of the hardware scan.
    ./hardware-configuration.nix
    "${builtins.fetchTarball "https://github.com/nix-community/disko/archive/master.tar.gz"}/module.nix"
  ];
  disko.devices = pkgs.callPackage ./disko-config.nix {
   disks = [ "/dev/sda" ]; # replace this with your disk name i.e. /dev/nvme0n1
  };
```

/mnt/etc/nixos/disko-config.nix
```
{
  disko.devices = {
    disk = {
      main = {
        type = "disk";
        device = "/dev/disk/by-id/ata-CT500MX500SSD1_2223E638BA62";
        content = {
          type = "gpt";
          partitions = {
            boot = {
              size = "1M";
              type = "EF02"; # for grub MBR
            };
            ESP = {
              size = "512M";
              type = "EF00";
              content = {
                type = "filesystem";
                format = "vfat";
                mountpoint = "/boot";
              };
            };
            root = {
              size = "100%";
              content = {
                type = "filesystem";
                format = "ext4";
                mountpoint = "/";
              };
            };
          };
        };
      };
    };
  };
}
```

Troubleshooting that I've done so far:
removing
```
disko.devices = pkgs.callPackage ./disko-config.nix {
   disks = [ "/dev/sda" ]; # replace this with your disk name i.e. /dev/nvme0n1
  };
```

give me a different error:
```
error:
       Failed assertions:
       - The ‘fileSystems’ option does not specify your root file system.
```
 Which I believe is expected. Any help in getting the disko config pulled into the nixos configuration would be great :)

**Comment by oneproxima** [comment]
the resulting --show-trace as well
`
valuating file '/mnt/etc/nixos/disko-config.nix'
error:
       … while evaluating the attribute 'config.system.build.toplevel'

       at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:326:9:

          325|         options = checked options;
          326|         config = checked (removeAttrs config [ "_module" ]);
             |         ^
          327|         _module = checked (config._module);

       … while evaluating the attribute 'unmatchedDefns'

       at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:671:7:

          670|       # Transforms unmatchedDefnsByName into a list of definitions
          671|       unmatchedDefns =
             |       ^
          672|         if configs == []

       … while evaluating call site

       at «none»:0: (source not available)

       … while calling anonymous lambda

       at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/attrsets.nix:539:10:

          538|     attrs:
          539|     map (name: f name attrs.${name}) (attrNames attrs);
             |          ^
          540|

       … while evaluating call site

       at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/attrsets.nix:539:16:

          538|     attrs:
          539|     map (name: f name attrs.${name}) (attrNames attrs);
             |                ^
          540|

       … while calling anonymous lambda

       at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:678:46:

          677|         else
          678|           concatLists (mapAttrsToList (name: defs:
             |                                              ^
          679|             map (def: def // {

       … while evaluating call site

       at «none»:0: (source not available)

       … while calling anonymous lambda

       at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:664:22:

          663|         # Propagate all unmatched definitions from nested option sets
          664|         mapAttrs (n: v: v.unmatchedDefns) resultsByName
             |                      ^
          665|         # Plus the definitions for the current prefix that don't have a matching option

       … while evaluating the attribute 'unmatchedDefns'

       at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:671:7:

          670|       # Transforms unmatchedDefnsByName into a list of definitions
          671|       unmatchedDefns =
             |       ^
          672|         if configs == []

       … while evaluating call site

       at «none»:0: (source not available)

       … while calling anonymous lambda

       at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:594:46:

          593|       # an attrset 'name' => list of submodules that define ‘name’.
          594|       defnsByName = byName "config" (module: value:
             |                                              ^
          595|           map (config: { inherit (module) file; inherit config; }) (pushDownProperties value)

       … while evaluating call site

       at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:595:69:

          594|       defnsByName = byName "config" (module: value:
          595|           map (config: { inherit (module) file; inherit config; }) (pushDownProperties value)
             |                                                                     ^
          596|         ) configs;

       … while calling 'pushDownProperties'

       at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:826:24:

          825|   */
          826|   pushDownProperties = cfg:
             |                        ^
          827|     if cfg._type or "" == "merge" then

       … while evaluating call site

       at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:830:52:

          829|     else if cfg._type or "" == "if" then
          830|       map (mapAttrs (n: v: mkIf cfg.condition v)) (pushDownProperties cfg.content)
             |                                                    ^
          831|     else if cfg._type or "" == "override" then

       … while calling 'pushDownProperties'

       at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:826:24:

          825|   */
          826|   pushDownProperties = cfg:
             |                        ^
          827|     if cfg._type or "" == "merge" then

       … while evaluating call site

       at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:830:52:

          829|     else if cfg._type or "" == "if" then
          830|       map (mapAttrs (n: v: mkIf cfg.condition v)) (pushDownProperties cfg.content)
             |                                                    ^
          831|     else if cfg._type or "" == "override" then

       … while calling 'pushDownProperties'

       at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:826:24:

          825|   */
          826|   pushDownProperties = cfg:
             |                        ^
          827|     if cfg._type or "" == "merge" then

       … while evaluating the attribute 'content'

       at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:951:14:

          950|     { _type = "if";
          951|       inherit condition content;
             |              ^
          952|     };

       … while evaluating call site

       at «none»:0: (source not available)

       … while calling 'g'

       at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/attrsets.nix:595:19:

          594|           g =
          595|             name: value:
             |                   ^
          596|             if isAttrs value && cond value

       … while evaluating call site

       at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/attrsets.nix:598:20:

          597|               then recurse (path ++ [name]) value
          598|               else f (path ++ [name]) value;
             |                    ^
          599|         in mapAttrs g;

       … while calling anonymous lambda

       at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:248:72:

          247|           # For definitions that have an associated option
          248|           declaredConfig = mapAttrsRecursiveCond (v: ! isOption v) (_: v: v.value) options;
             |                                                                        ^
          249|

       … while evaluating the attribute 'value'

       at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:759:9:

          758|     in warnDeprecation opt //
          759|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          760|         inherit (res.defsFinal') highestPrio;

       … while evaluating the option `disko.devices':

       … while evaluating the attribute 'mergedValue'

       at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:794:5:

          793|     # Type-check the remaining definitions, and merge them. Or throw if no definitions.
          794|     mergedValue =
             |     ^
          795|       if isDefined then

       … while evaluating the attribute 'values'

       at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:788:9:

          787|       in {
          788|         values = defs''';
             |         ^
          789|         inherit (defs'') highestPrio;

       … while evaluating the attribute 'values'

       at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:887:7:

          886|     in {
          887|       values = concatMap (def: if getPrio def == highestPrio then [(strip def)] else []) defs;
             |       ^
          888|       inherit highestPrio;

       … while evaluating call site

       at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:774:17:

          773|         # Process mkMerge and mkIf properties.
          774|         defs' = concatMap (m:
             |                 ^
          775|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))

       … while calling anonymous lambda

       at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:774:28:

          773|         # Process mkMerge and mkIf properties.
          774|         defs' = concatMap (m:
             |                            ^
          775|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))

       … while evaluating definitions from `/mnt/etc/nixos/configuration.nix':

       … while evaluating call site

       at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:775:137:

          774|         defs' = concatMap (m:
          775|           map (value: { inherit (m) file; inherit value; }) (builtins.addErrorContext "while evaluating definitions from `${m.file}':" (dischargeProperties m.value))
             |                                                                                                                                         ^
          776|         ) defs;

       … while calling 'dischargeProperties'

       at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:846:25:

          845|   */
          846|   dischargeProperties = def:
             |                         ^
          847|     if def._type or "" == "merge" then

       … while evaluating the attribute 'value'

       at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:599:44:

          598|       defnsByName' = byName "config" (module: value:
          599|           [{ inherit (module) file; inherit value; }]
             |                                            ^
          600|         ) configs;

       … while evaluating call site

       at /mnt/etc/nixos/configuration.nix:14:19:

           13|   ];
           14|   disko.devices = pkgs.callPackage ./disko-config.nix {
             |                   ^
           15|    disks = [ "/dev/sda" ]; # replace this with your disk name i.e. /dev/nvme0n1

       … while calling 'callPackageWith'

       at /nix/store/p2bmnfbfp2cpqlsa0nffb9c9zc8ybwml-nixos-23.05.2975.a16f7eb56e88/nixos/lib/customisation.nix:128:35:

          127|   */
          128|   callPackageWith = autoArgs: fn: args:
             |                                   ^
          129|     let

       … while evaluating call site

       at /nix/store/p2bmnfbfp2cpqlsa0nffb9c9zc8ybwml-nixos-23.05.2975.a16f7eb56e88/nixos/lib/customisation.nix:141:10:

          140|         # Filter out arguments that have a default value
          141|         (lib.filterAttrs (name: value: ! value)
             |          ^
          142|         # Filter out arguments that would be passed

       … while calling 'filterAttrs'

       at /nix/store/p2bmnfbfp2cpqlsa0nffb9c9zc8ybwml-nixos-23.05.2975.a16f7eb56e88/nixos/lib/attrsets.nix:305:5:

          304|     # The attribute set to filter
          305|     set:
             |     ^
          306|     listToAttrs (concatMap (name: let v = set.${name}; in if pred name v then [(nameValuePair name v)] else []) (attrNames set));

       … while evaluating call site

       at /nix/store/p2bmnfbfp2cpqlsa0nffb9c9zc8ybwml-nixos-23.05.2975.a16f7eb56e88/nixos/lib/customisation.nix:131:15:

          130|       f = if lib.isFunction fn then fn else import fn;
          131|       fargs = lib.functionArgs f;
             |               ^
          132|

       … while calling 'functionArgs'

       at /nix/store/p2bmnfbfp2cpqlsa0nffb9c9zc8ybwml-nixos-23.05.2975.a16f7eb56e88/nixos/lib/trivial.nix:440:18:

          439|   */
          440|   functionArgs = f:
             |                  ^
          441|     if f ? __functor

       error: 'functionArgs' requires a function

       at /nix/store/p2bmnfbfp2cpqlsa0nffb9c9zc8ybwml-nixos-23.05.2975.a16f7eb56e88/nixos/lib/trivial.nix:443:10:

          442|     then f.__functionArgs or (lib.functionArgs (f.__functor f))
          443|     else builtins.functionArgs f;
             |          ^
          444|


`

**Comment by phaer** [comment]
The thing in ´disko-config.nix´ needs to be a function, i.e.

```
{disks, ...}: {
  disko.devices = {
[...]
````

You can then use that variable instead of hard-coding the path in the config, i.e. 

```
        device = "/dev/disk/by-id/ata-CT500MX500SSD1_2223E638BA62";
```

becomes

```
        device = builtins.head disks;
```

**Comment by oneproxima** [comment]
Success, thank you @phaer ! Below are my updated configs for anyone in the future. 

/mnt/etc/nixos/configuration
```
imports =
  [ # Include the results of the hardware scan.
    ./hardware-configuration.nix
    "${builtins.fetchTarball "https://github.com/nix-community/disko/archive/master.tar.gz"}/module.nix"
  ];

  disko.devices = import ./disko-config.nix {
    disks = [ "/dev/sda" ];
  };
```

/mnt/etc/nixos/disko-config.nix
```
{disks ? [ "/dev/sda" ], ...}: {
  disk.sda = {
    type = "disk";
    device = "/dev/disk/by-id/ata-CT500MX500SSD1_2223E638BA62";
    content = {
      type = "gpt";
      partitions = {
        boot = {
          size = "1M";
          type = "EF02"; # for grub MBR
        };
        ESP = {
          size = "512M";
          type = "EF00";
          content = {
            type = "filesystem";
            format = "vfat";
            mountpoint = "/boot";
          };
        };
        root = {
          size = "100%";
          content = {
            type = "filesystem";
            format = "ext4";
            mountpoint = "/";
          };
        };
      };
    };
  };
}
```
