### ISSUE TITLE
madm generates incorrect devices names in the nixos configuration

### ISSUE THREAD

**Issue by Mic92** [nix-community/disko#38]
mdadm uses the hostname in addition to the raid name during assembling the raid.

I.e. the device path is called `/dev/md/dev1:boot ` on host `dev1`, whereas disko currently uses `/dev/md/boot` in its fstab:

```
[root@dev1:~]# ls -la /dev/md/dev1\:boot 
lrwxrwxrwx 1 root root 8 Sep  5 15:55 /dev/md/dev1:boot -> ../md127
```

**Comment by Lassulus** [comment]
will be fixed by #43
