### ISSUE TITLE
Option to hide LUKS passwords when using cli utility

### ISSUE THREAD

**Issue by MartinLoeper** [nix-community/disko#385]
Currently, the LUKS password is displayed in plaintext when using the disko cli utility to format or mount the disks.
It would be nice if there was an option to hide logs containing sensitive data.

I stumbled across this issue as I am currently writing a custom ISO installer for our company.

**Comment by Mic92** [comment]
Is this shown by default or when using --debug?

**Comment by MartinLoeper** [comment]
It is shown by default when using `disko --mode mount "XXXX" --arg disks "XXXX" --root-mountpoint "XXXX"`. It looks like some `set -x` kind of stuff.

**Comment by Lassulus** [comment]
We can add a debug parameter (which I would leave at true for now. Otherwise bugreports will be way worse) which you can disable then. Does this sound like a good enough solution?

**Comment by Mic92** [comment]
I think this should solve the issue: https://github.com/nix-community/disko/pull/395

**Comment by iFreilicht** [comment]
Seems like this is fixed, then. Please re-open the issue if you find it's not!
