### ISSUE TITLE
Partition label not being set correctly 

### ISSUE THREAD

**Issue by robbins** [nix-community/disko#389]
I'm noticing that the partition name set by sgdisk isn't reflected in /dev/disk/by-partlabel.
When I run `sudo disko --mode disko hosts/linux/bulldozer/disko.nix --debug` I get the following failed output: 
https://katb.in/bosavixecib

I only see `/dev/disk/by-partlabel/disk-_dev_disk_by-id_ata-Samsung_SSD`.

I'm trying to setup my partitions such that / is on a ZFS dataset, and then I have /persist on a separate ZFS dataset, and /boot as a separate partition.
My Disko config:
```
{ lib, ... }:
{
  disko.devices.disk = lib.genAttrs [ "/dev/disk/by-id/ata-Samsung_SSD_860_EVO_250GB_S3YHNX0K836387Z" ]
    (disk: {
      type = "disk";
      device = disk;
      content = {
        type = "gpt";
	partitions = {
	  ESP = {
            start = "1MiB";
	    end = "1024MiB";
	    type = "EF00";
	    content = {
	      type = "filesystem";
	      format = "vfat";
	      mountpoint = "/boot";
	    };
	  };
	  SWAP = {
	    start = "1024MiB";
	    end = "9216MiB";
	    content = {
	      type = "swap";
	      randomEncryption = true;
	      resumeDevice = true;
	    };
	  };
	  ZFS = {
	    start = "9216MiB";
	    end = "100%";
	    content = {
	      type = "zfs";
	      pool = "bulldozer";
	    };
	  };
	};
      };
    });
  zpool = {
    bulldozer = {
      type = "zpool";
      options = {
        ashift = "13";
	autotrim = "on";
      };
      rootFsOptions = {
        atime = "off";
	compression = "lz4";
	xattr = "sa";
	mountpoint = "none";
        canmount = "off";
	acltype = "posixacl";
	encryption = "aes-256-gcm";
	keyformat = "passphrase";
	keylocation = "prompt";
	normalization = "formD";
	"com.sun:auto-snapshot" = "false";
      };
      postCreateHook = ''
        zfs snapshot -r bulldozer@blank
	zfs set keylocation="prompt" "bulldozer";
	'';
      datasets = {
        local.type = "zfs_fs";
	"local/nix" = {
	  type = "zfs_fs";
	  options.mountpoint = "/nix";
	};
	"persist" = {
	  type = "zfs_fs";
	  options.mountpoint = "/persist";
	};
	system.type = "zfs_fs";
	"system/root" = {
	  type = "zfs_fs";
	  mountpoint = "/";
	};
      };
    };
  };
}
```

**Comment by Lassulus** [comment]
I would guess the label is to long. Can you try with a shorter disk attribute name? Maybe I should hash the label if it gets to long

**Comment by robbins** [comment]
You're right, using a shorter disk name did the trick, thanks.

However, now I'm facing an issue with the partitioning. For some reason it's unable to create the Swap partition: https://katb.in/esiqihoniga. Not sure if the start/end positions are incorrect somehow...

**Comment by Mic92** [comment]
Maybe the `--set-alignment` parameter conflicts with the start and end options?

```
+ sgdisk --set-alignment=2048 --align-end --new=2:1024MiB:9216MiB --change-name=2:disk-S3YHNX0K836387Z-SWAP --typecode=2:8300 /dev/disk/by-id/ata-Samsung_SSD_860_EVO_250GB_S3YHNX0K836387Z
Could not create partition 2 from 2097152 to 18874368
Unable to set partition 2's name to 'disk-S3YHNX0K836387Z-SWAP'!
Could not change partition 2's type code to 8300!
Error encountered; not saving changes.
```

`2099200` seems now better aligned than what sgdisk tried to choose in the error. So in the end you might end up with a better performing filesystem using size.

**Comment by Mic92** [comment]
I think you should always use `9216M` instead of `9216MiB`, otherwise sgdisk cannot align sizes.

**Comment by robbins** [comment]
Thanks, used `size` and the `M` prefix and it partitions successfully.

**Comment by mibmo** [comment]
> @robbins: I would guess the label is to long. Can you try with a shorter disk attribute name? Maybe I should hash the label if it gets to long

I think this might still be a good idea; you can't always just use a shorter name, i.e. if you have a USB drive and have to address it by `/dev/disk/by-id` to get persistence.
