### ISSUE TITLE
FR: Explicit partition number option

### ISSUE THREAD

**Issue by cvoges12** [nix-community/disko#403]
Currently, partitions are sorted by alphabetical ASCII order by side effect of how nix orders attribute sets. If this is not the desired behavior, there is no way to reorder the partitions except by naming hacks for partition labels.

My proposal is for a `partNum` option that can be used for setting the exact order of a partition.

**Comment by Lassulus** [comment]
There is priority which can be used for that

**Comment by cvoges12** [comment]
Does priority work with lowest priority number first? If not, I feel like this is kind of the opposite of what I want as it would have reverse ordering.

**Comment by Lassulus** [comment]
https://github.com/nix-community/disko/blob/master/lib/types/gpt.nix#L38

**Comment by cvoges12** [comment]
Ah, okay. I'll close this then. Thanks.
