### ISSUE TITLE
btrfs subvolumes are not added as filesystems

### ISSUE THREAD

**Issue by ners** [nix-community/disko#418]
NixOS fails to build with the [btrfs subvolumes](https://github.com/nix-community/disko/blob/master/example/luks-btrfs-subvolumes.nix) example, with the following error:

```
error:
       … while calling the 'head' builtin

         at /nix/store/902j4afzd3glcviwv1kzkqq3bb05y736-source/lib/attrsets.nix:820:11:

          819|         || pred here (elemAt values 1) (head values) then
          820|           head values
             |           ^
          821|         else

       … while evaluating the attribute 'value'

         at /nix/store/902j4afzd3glcviwv1kzkqq3bb05y736-source/lib/modules.nix:807:9:

          806|     in warnDeprecation opt //
          807|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          808|         inherit (res.defsFinal') highestPrio;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error:
       Failed assertions:
       - The ‘fileSystems’ option does not specify your root file system.
```

For added emphasis, the last line of the error is most telling:
```
The ‘fileSystems’ option does not specify your root file system.
```

Looking at the implementation of disko, I don't see any provisions for using btrfs submodules as mounted filesystems. Can you clarify?

**Comment by Lassulus** [comment]
They should be added here: https://github.com/nix-community/disko/blob/master/lib/types/btrfs.nix#L128 the test also seems to boot. So that should work

**Comment by ners** [comment]
Apologies, I seem to have been using the module wrong. All good, the example works as intended. :slightly_smiling_face:
