### ISSUE TITLE
Config works in VM using installTest but install fails on hardware

### ISSUE THREAD

**Issue by djacu** [nix-community/disko#426]
I've created a ZFS disko configuration and have been using `installTest` to verify that the configuration would work. After being satisfied with my configuration, I loosely followed the `quickstart.md` guide to install NixOS. It completely the installation but after reboot, it was not able to find the root pool and could not complete the boot process. I even added my own checks and could see them in the `installTest` logs so I know things were working properly.

Details below.

The repo I was using at the specific commit hash:
https://github.com/djacu/nixos-config/tree/a0153b5e69e38e13be46207becc7b947e8d8774d

The command I used to test the configuration in a VM.
`nix build .#nixosConfigurations.adalon.config.system.build.installTest -L`

The steps I used to install on my laptop.

1. start a new shell with git `nix-shell -p git`
2. Clone and `cd` to my repo
3. `sudo nix run github:nix-community/disko --extra-experimental-features nix-command --extra-experimental-features flakes -- --mode disko ./hosts/adalon/disko-config.nix`
4. `sudo nixos-generate-config --no-filesystems --root /mnt`
5. Copy my repo into the mounted disk and cd to it: `cp nixos-config /mnt/etc/nixos/ -r`
6. Copy the `hardware-configuration.nix` into hosts/adalon/
7. Modify the `configuration.nix` file to import the `hardware-configuration.nix`
8. `sudo nixos-install --flake .#adalon`
9. reboot

After rebooting, these are the messages I see
```shell
<<< NixOS Stage 1 >>>

loading module i915...
loading module zfs...
loading module spl...
loading module dm_mod...
running udev...
Starting systemd-udevd version 254.3
starting device mapper and LVM...
importing root ZFS pool "rpool"..............................................
cannot import 'rpool': more than one matching pool
import by numeric ID instead
cannot import 'rpool': more than one matching pool
import by numeric ID instead
mounting rpool/root on /...
mount: mounting rpool/root on /mnt-root/ failed: No such file or directory retrying...
mount: mounting rpool/root on /mnt-root/ failed: No such file or directory retrying...
mount: mounting rpool/root on /mnt-root/ failed: No such file or directory retrying...
mount: mounting rpool/root on /mnt-root/ failed: No such file or directory retrying...
mount: mounting rpool/root on /mnt-root/ failed: No such file or directory retrying...
mount: mounting rpool/root on /mnt-root/ failed: No such file or directory retrying...

An error occured in stage 1 of the boot process, which must mount the root filesystem on '/mnt-root' and then start stage 2. Press one of the following keys:

  r) to reboot immediatly
  *) to ignore the error and continue
```

Here is the `disko-config.nix` file I use to format the disks. It imports the file below.

```nix
# disko-config.nix
let
  device = "/dev/disk/by-id/nvme-WD_BLACK_SN850_1TB_204178806629";

  disko-config = import ../../disko;
in
  disko-config {inherit device;}
```

```nix
# disko/default.nix
{device, ...}: {
  disko.devices = {
    disk = {
      nvme = {
        type = "disk";
        inherit device;
        content = {
          type = "gpt";
          partitions = {
            biosboot = {
              size = "1M";
              type = "EF02";
            };
            efiboot = {
              type = "EF00";
              size = "1G";
              content = {
                type = "filesystem";
                format = "vfat";
                mountpoint = "/boot";
              };
            };
            swap = {
              size = "1G";
              type = "8200";
              content = {
                type = "swap";
                randomEncryption = true;
                resumeDevice = true; # resume from hiberation from this device
              };
            };
            zroot = {
              size = "100%";
              content = {
                type = "zfs";
                pool = "rpool";
              };
            };
          };
        };
      };
    };

    zpool = {
      rpool = {
        type = "zpool";
        rootFsOptions = {
          acltype = "posixacl";
          canmount = "off";
          checksum = "edonr";
          compression = "zstd";
          dnodesize = "auto";
          # encryption does not appear to work in vm test; only use on real system
          #encryption = "aes-256-gcm";
          #keyformat = "passphrase";
          #keylocation = "file:///tmp/secret.key"; # must be set during initial installation step
          mountpoint = "none";
          normalization = "formD";
          relatime = "on";
          xattr = "sa";
          "com.sun:auto-snapshot" = "false";
        };
        options = {
          ashift = "12";
          autotrim = "on";
        };
        #postCreateHook = ''
        #  # last argument must be same as as the pool attrname
        #  zfs set keylocation="prompt" "rpool";
        #'';

        datasets = {
          home = {
            type = "zfs_fs";
            options.mountpoint = "legacy";
            mountpoint = "/home";
            options."com.sun:auto-snapshot" = "true";
            postCreateHook = "zfs snapshot rpool/home@empty";
          };
          persist = {
            type = "zfs_fs";
            options.mountpoint = "legacy";
            mountpoint = "/persist";
            options."com.sun:auto-snapshot" = "true";
            postCreateHook = "zfs snapshot rpool/persist@empty";
          };
          nix = {
            type = "zfs_fs";
            options.mountpoint = "legacy";
            mountpoint = "/nix";
            options = {
              atime = "off";
              canmount = "on";
              "com.sun:auto-snapshot" = "true";
            };
            postCreateHook = "zfs snapshot rpool/nix@empty";
          };
          root = {
            type = "zfs_fs";
            options.mountpoint = "legacy";
            mountpoint = "/";
            postCreateHook = ''
              zfs snapshot rpool/root@empty
              zfs snapshot rpool/root@lastboot
            '';
          };
        };
      };
    };
  };
  disko.tests.extraChecks = ''
    print("HIIIIIIIIIIIIIIIIIIII")
    print(machine.succeed("pwd"))
    print(machine.succeed("vim --version"))
    print(machine.succeed("lslogins bakerdn"))
    print(machine.succeed("cat /etc/nix/nix.conf"))
    print(machine.succeed("alejandra -V"))
    print(machine.succeed("nmcli --version"))
  '';
}
```

**Comment by Mic92** [comment]
Have you run `nixos-generate-config --no-filesystems --root /mnt`? You are likely missing the nvme kernel driver to load the block device. The configuration generated by this command should have it. Something like that might also work: https://github.com/Mic92/dotfiles/blob/6575c3c482e38d8caba20168edc0ecb93ee26dcb/nixos/eve/hardware-configuration.nix#L13

**Comment by Mic92** [comment]
Cannot find it here: https://github.com/djacu/nixos-config/blob/a0153b5e69e38e13be46207becc7b947e8d8774d/hosts/adalon/configuration.nix

**Comment by phaer** [comment]
I am bit confused by the error message:

> cannot import 'rpool': more than one matching pool

Might be misleading, as @Mic92s suggestion seens plausible to me as well. But if the error persists with the nvme module, it might be worth double checking whether there is another zpool (i.e. is there a second disk? what does `zpool import` show on the machine?

**Comment by djacu** [comment]
@Mic92 Yes I import the `hardware-configuration.nix` file per steps 4-7 I mentioned above. And I've tried this multiple times so it isn't a one off fluke. For reference,  the `hardware-configuration.nix` file looks similar to this but without all the `fileSystem` options.
https://github.com/djacu/dotfiles-framework/blob/main/system/hardware-configuration-zfs.nix

@phaer Pretty sure I checked once and there was only a single zpool but I'll check again.

**Comment by Mic92** [comment]
You can add `boot.debug1devices` to your kernel cmdline. Than you will be dropped into a shell from which you can run `lsblk` to see what devices it can find. Also `modprobe` for the drivers that might be missing. You can also run `lsmod` to compare device drivers you can see in the installer vs in the booted system.

**Comment by djacu** [comment]
Thanks all for the help. I resolved the issue by stripping the config down to the bare minimum and building it back up from there. It now works and you can see the working config in #456 where I found an interesting issue related to adding a swap partition.
