### ISSUE TITLE
Can't change default `networking.hostId` value when using`zpool` disko config

### ISSUE THREAD

**Issue by sbc64** [nix-community/disko#434]
I don't know whether to make the issue in this repository or at https://github.com/nix-community/nixos-anywhere, even though I'm using `nixos-anywhere` it seems that the executing scripts recide in this repository.

Here is the disko config I'm trying to use:

```nix
# disc-config.nix
{
  lib,
  config,
  ...
}:{
  # This doesn't work
  networking.hostId = lib.mkForce "00022319"; 
  # This works
  # networking.hostId = lib.mkForce "8425e349";
  
  
  disko.devices = {
    disk.main = {
      device = lib.mkDefault "/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_38446325";
      type = "disk";
      content = {
        type = "gpt";
        partitions = {
          boot = {
            name = "boot";
            size = "500M";
            type = "EF02";
          };
          esp = {
            name = "ESP";
            size = "1G";
            type = "EF00";
            content = {
              type = "filesystem";
              format = "vfat";
              mountpoint = "/boot";
            };
          };
          zfs = {
            size = "100%";
            content = {
              type = "zfs";
              pool = "zroot";
            };
          };
        };
      };
    };
    zpool = {
      zroot = {
        type = "zpool";
        rootFsOptions = {
          compression = "zstd";
          "com.sun:auto-snapshot" = "false";
        };
        mountpoint = "/";
        postCreateHook = "zfs snapshot zroot@blank";
        datasets = {
          nextcloud = {
            type = "zfs_fs";
            mountpoint = "/nextcloud";
            options = {
              "com.sun:auto-snapshot" = "true";
              "userprop:access" = "nextcloud";
              mountpoint = "legacy";
            };
          };
        };
      };
    };
  };
}
```

If I use `networking.hostId = "<something other than 8425e349>"`, I get greated with the following booting sequence:
<img width="1799" alt="Screenshot 2023-10-27 at 07 42 21" src="https://github.com/nix-community/nixos-anywhere/assets/10123236/ab238158-36c0-4f42-86de-4f3ce43bb5c2">

I have not been able to find out how `disko` sets the current `8425e349` hostId since all the results I see are in the test libraries: https://github.com/search?q=repo%3Anix-community%2Fdisko+8425e349&type=code

How can I set my own `networking.hostId` value, or do I have to change after the first boot sequence is done, if changing is at all possible?

**Comment by Mic92** [comment]
The hostid comes from here: https://github.com/nix-community/nixos-images/blob/87bccdbdfbeb07e0c4fb4c2ec3d71986e8fa24d9/nix/noninteractive.nix#L52
There can currently only be changed by rebuilding the installer image. We have some `zpool export` step that is supposed to solve this issue, but it seems to be not always be effective?

**Comment by Mic92** [comment]
Does this fix the issue? https://github.com/nix-community/nixos-anywhere/pull/239

**Comment by Mic92** [comment]
Let's wait for feedback.

**Comment by phaer** [comment]
Ah thanks, I did not close this - Github did so automatically because of the PRs message. Its clever enough to interpret "fixes", but not clever enough to understand "potentially" :D

**Comment by sbc64** [comment]
This solved the issue.

Thank you very much for your stupendus speed!
