### ISSUE TITLE
Incompatibility of `nixosModules.hardware-amazon` with disko configuration

### ISSUE THREAD

**Issue by katexochen** [nix-community/disko#441]
I'm using disko and nixos anywhere to describe my wanted disk configuration and install NixOS on an AWS VM. I tried to use the hardware-amazon module from srvos, however, the module seems to be incompatible with disko as it sets fileSystem options:

```
$ nix run github:numtide/nixos-anywhere -- --flake .#aws -i ~/.ssh/some_key ec2-user@some_host
       [ ... ]
       error: The option `fileSystems."/".fsType' has conflicting definition values:
       - In `/nix/store/8kfifw0fxdhgsas8ywy9jikzgz2h2aa4-source/flake.nix': "btrfs"
       - In `/nix/store/8kfifw0fxdhgsas8ywy9jikzgz2h2aa4-source/nixos/modules/virtualisation/amazon-image.nix': "ext4"
       Use `lib.mkForce value` or `lib.mkDefault value` to change the priority on any of these definitions.
```

As bot settings come from a module, there doesn't seem to be a way I could give one module precedence over the other.

Here is an example config triggering that problem:

```nix
{
  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixpkgs-unstable";
    srvos.url = "github:numtide/srvos";
    srvos.inputs.nixpkgs.follows = "nixpkgs";
    disko.url = "github:nix-community/disko";
    disko.inputs.nixpkgs.follows = "nixpkgs";
  };
  outputs = { self, nixpkgs, srvos, disko }: {
    nixosConfigurations.aws = nixpkgs.lib.nixosSystem {
      system = "x86_64-linux";
      modules = [
        srvos.nixosModules.hardware-amazon
        disko.nixosModules.disko
        {
          disko.devices.disk.nvme0n1 = {
            device = "/dev/nvme0n1";
            type = "disk";
            content = {
              type = "gpt";
              partitions = {
                ESP = {
                  type = "EF00";
                  size = "500M";
                  content = {
                    type = "filesystem";
                    format = "vfat";
                    mountpoint = "/boot";
                  };
                };
                root = {
                  size = "100%";
                  content = {
                    type = "btrfs";
                    extraArgs = [ "-f" ];
                    subvolumes = {
                      "@" = {
                        mountpoint = "/";
                      };
                    };
                  };
                };
              };
            };
          };
        }
      ];
    };
  };
}

```

The amazon fileSystem options are set by the amazon-image module in nixpkgs:

https://github.com/NixOS/nixpkgs/blob/6e53b4f5de8dc7387a0e62370f3e8c71aee89151/nixos/modules/virtualisation/amazon-image.nix#L32-L43

---
@zimbatm reported as promised on twitter ;)

**Comment by zimbatm** [comment]
I moved the issue as this is a compatibility problem between disko and the NixOS profiles that ship with nixpkgs.

I'm not sure what's the best.

Is disko supposed to control the whole `fileSystems` prefix and override all the values? Or should the upstream profiles be setting their values using `lib.mkDefault` (or some other idea I didn't think about) ?

**Comment by yangm97** [comment]
> Is disko supposed to control the whole fileSystems prefix and override all the values?

That would be an issue for systems which use disko for provisioning the base os but later on add pet mounts (i.e. a zfs data pool).

**Comment by iFreilicht** [comment]
So, this is a nixpkgs issue then, right? We can't do anything about this in disko?

**Comment by Lassulus** [comment]
not really, other than upstreaming disko and using disko in the amazon image at some point ;)

**Comment by iFreilicht** [comment]
Then I would say we close this issue :)
