### ISSUE TITLE
Example swap.nix enables mutually exclusive options randomEncryption and resumeDevice.

### ISSUE THREAD

**Issue by manueljacob** [nix-community/disko#448]
[Example swap.nix](https://github.com/nix-community/disko/blob/2d7d77878c5d70f66f3d676ff66708d8d4f9d7df/example/swap.nix#L31-L32) enables both randomEncryption and resumeDevice. According to the [NixOS option documentation](https://github.com/NixOS/nixpkgs/blob/b5953ae45d2de05b33eba1e7b2c2a198f12e0c29/nixos/modules/config/swap.nix#L20-L22), hibernating from swap partitions with random keys does not work and enabling this option could lead to data loss.

**Comment by iFreilicht** [comment]
This was fixed in #455
