### ISSUE TITLE
trace: warning: mdadm: Neither MAILADDR nor PROGRAM has been set. This will cause the `mdmon` service to crash.

### ISSUE THREAD

**Issue by tmarkov** [nix-community/disko#451]
When using `disko` with an `mdadm` raid0 on unstable (based on the example in this repo), I get a warning, `trace: warning: mdadm: Neither MAILADDR nor PROGRAM has been set. This will cause the `mdmon` service to crash.`

AFAIK it's caused by enabling [boot.swraid.enable](https://search.nixos.org/options?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=swraid) without having any additional configuration (see [boot.swraid.mdadmConf](https://search.nixos.org/options?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=swraid)). But I'm not sure where to go from here.

Here's my disko config: https://pastebin.com/0Z8U3cPb

**Comment by phaer** [comment]
> trace: warning: mdadm: Neither MAILADDR nor PROGRAM has been set. This will cause the mdmon service to crash.

mdmon is a daemon that would send you an email or call a program of your liking if the kernel notifies it that i.e. one of the disks in your raid broke.

>  But I'm not sure where to go from here.

Depends on what you want: If you don't need such notifications or have other monitoring tools watch that for you, you could simply ignore it.
If you need them and got a mail setup on that host, just set  MAILADDR=my@fancy.email in boot.swraid.mdadmConf or refer to man mdadm.conf and the PROGRAM parameter to i.e. send yourself a push notification via a different messaging system


(I don't think that's a disko-specific issue, so nixpkgs might be a better place to discuss if you think this warning is out of place)

**Comment by xdevs23** [comment]
I just did

```
  boot.swraid.mdadmConf = ''
    MAILADDR=nobody@nowhere
  '';
```

I very rarely need to connect a md (raid) drive, so I just need mdadm occasionally, and I don't use the RAID functionality (anymore), so I just find it very annoying to see that warning in red every time.
