### ISSUE TITLE
upgrade to 23.11 forgets "raid1" module in initrd

### ISSUE THREAD

**Issue by ManoftheSea** [nix-community/disko#457]
I was happily using a device with disko defining a logical-volume that was a raid1.  I upgraded to NixOS 23.11, and upon reboot, discovered that dm-mapper couldn't add the device to the mapping table.  This was my first update since Nov 1, using flakes, so it's possible the change is unrelated to the upgrade.

I fixed this by adding boot.initrd.availableKernelModules = ["raid1"].  This makes me think that somehow, Disko no longer does the right thing for a device using disko.devices.lvm_vg."mypool".lvs."myvolume".lvm_type = "raid1"

**Comment by Mic92** [comment]
fixed in https://github.com/nix-community/disko/pull/463
