### ISSUE TITLE
Alignment

### ISSUE THREAD

**Issue by mightyiam** [nix-community/disko#460]
Plan: go through each command that mutates the disk and deduce whether it affects the topic of alignment. List them as a comment here.

**Comment by Mic92** [comment]
I am not following what the purpose of this exercise is?

**Comment by mightyiam** [comment]
I watched your talk. One of the questions was about alignment. Alignment of partitions to physical sectors. Whether Disko takes care of that. Your answer was no. Is that still the case?

**Comment by Mic92** [comment]
We now got https://github.com/nix-community/disko/pull/362
If you find more alignment issues, please let us know.
