### ISSUE TITLE
Disko doesn't consider Advanced Format sectors when aligning disks

### ISSUE THREAD

**Issue by ManoftheSea** [nix-community/disko#472]
I understand that disks should be aligned to 1 megabyte boundaries.  Disko produces a script that gives "--set-alignment=2048" to sgdisk in all cases.  On a 4k disk, this is an 8 megabyte alignment, the proper value is 256 for 1M alignment.

One possible command is "blockdev --getss /dev/disk-name", which returns the logical sector size.  Divide 1M by the returned value, you get the needed alignment.

**Comment by iFreilicht** [comment]
This has been fixed in #509
