### ISSUE TITLE
Documentation Examples Confusion Due to Disk Name "vdb"

### ISSUE THREAD

**Issue by stephenandary** [nix-community/disko#473]
When looking at the examples for disko, any example that is not hybrid names a disk "vdb" irrespective of related disk. This can be slightly confusing. I personally thought this was Disko syntax that was necessary.

e.g. The below example could be disk.vda = {} instead? 
```
{ disks ? [ "/dev/vda" ], ... }: {
  disko.devices = {
    disk = {
      vdb = {
```

**Comment by Lassulus** [comment]
Ah, yeah I overlooked the example in the main README. luckily this now got removed, so it should be less confusing now?

**Comment by Mic92** [comment]
I assume this was fixed by https://github.com/nix-community/disko/pull/475/files ?
