### ISSUE TITLE
Need Help partitioning

### ISSUE THREAD

**Issue by Rafi1018** [nix-community/disko#485]
Hey there, I am new to NixOS & Disko & I want to dual boot NixOS & Windows 10 for which I need to create a disko config file.
I want to allocate 40 GB for swap & rest for the system. It did be great if anyone can help me create it & personally I also created one give here :

```nix
#Disk configuration for dual-booting NixOS with Windows 10
  disko.devices = {
    disk = {
      nvme0n1 = {
        device = "/dev/nvme0n1";
        type = "disk";
        content = {
          type = "gpt";
          partitions = {
            # Windows partitions (existing)
            ESP = {
              type = "EF00";  # EFI partition type
              size = "100M";
              content = {
                type = "filesystem";
                format = "vfat";
                mountpoint = "/boot";
              };
            };
            # NixOS partitions
            swap = {
              start = "373.766G";  # start point for swap
              size = "40G";
              content = {
                type = "swap";
              };
            };
            root = {
              start = "413.766G";  # After swap partition
              size = "100%";  # Take all remaining space
              content = {
                type = "filesystem";
                format = "ext4";
                mountpoint = "/";
              };
            };
          };
        };
      };
    };
  };
}
```

**Comment by Toby222** [comment]
Probably a bit late with the response, but the [quickstart](https://github.com/nix-community/disko/blob/master/docs/quickstart.md) mentions that dual booting is not supported.
Perhaps that should also be in the README

**Comment by Mic92** [comment]
Dual-booting can work if you first install NixOS and than Windows. The issue is that disko takes full ownership of the disk and will remove any other partitions.

**Comment by Rafi1018** [comment]
gotcha thanks

**Comment by kamack38** [comment]
@Rafi1018 sorry for mentioning you, but did you find a way to dual boot Windows and NixOs using disko? Did installing NixOs first and then leaving empty space for Windows work?

**Comment by Rafi1018** [comment]
> @Rafi1018 sorry for mentioning you, but did you find a way to dual boot Windows and NixOs using disko? Did installing NixOs first and then leaving empty space for Windows work?

No, I actually never tried it & using only linux now. But I guess you can use my provided disko config adjusting everything according to your disk configuration.
