### ISSUE TITLE
Hardcoded 2048-sector alignment is excessive for 4Kn disks

### ISSUE THREAD

**Issue by intelfx** [nix-community/disko#497]
The gpt partition table support in disko seems to hardcode a 2048-sector alignment:

https://github.com/nix-community/disko/blob/8a9e89d4669c8b6820ae7c7574f68908892fa5f3/lib/types/gpt.nix#L113

This only makes sense for 512-byte sector disks; for 4K-native disks this results in 8 MiB alignment which is excessive.

---

Does it even make sense to explicitly specify the alignment value, given that sgdisk already defaults to 1 MiB alignment using whatever sector size is reported by the disk?

**Comment by Mic92** [comment]
This is contradicting the original message of this PR: https://github.com/nix-community/disko/pull/362

> The following command:
> `sgdisk --new=4:0:-0 /dev/xda`
> will work but unless the overall disk size is aligned to 4k, the new partition will not be > aligned to 4k.
> `--set-alignment=2048 --align-end` aligns new partitions to 1 MiB (2048 sectors). This enables for example `--sector-size=4096` for `cryptsetup luksFormat`.

**Comment by Mic92** [comment]
Is there a way to specify bytes instead of sectors?

**Comment by intelfx** [comment]
> This is contradicting the original message of this PR

I believe what matters for the goal described in #362 is `--align-end`, not `--set-alignment 2048`:

```
# truncate -s 123456789 test.img

# losetup -f --show test.img
/dev/loop1
losetup: test.img: Warning: file does not fit into a 512-byte sector; the end of the file will be ignored.

# sgdisk --align-end --new=4:0:-0  /dev/loop1
Creating new GPT entries in memory.
Warning: The kernel is still using the old partition table.
The new table will be used at the next reboot or after you
run partprobe(8) or kpartx(8)
The operation has completed successfully.

# gdisk -l /dev/loop1
GPT fdisk (gdisk) version 1.0.9.1

Partition table scan:
  MBR: protective
  BSD: not present
  APM: not present
  GPT: present

Found valid GPT with protective MBR; using GPT.
Disk /dev/loop1: 241126 sectors, 117.7 MiB
Sector size (logical/physical): 512/512 bytes
Disk identifier (GUID): 254E2E19-9744-46F6-9DC9-3D6B761DA635
Partition table holds up to 128 entries
Main partition table begins at sector 2 and ends at sector 33
First usable sector is 34, last usable sector is 241092
Partitions will be aligned on 2048-sector boundaries
Total free space is 3491 sectors (1.7 MiB)

Number  Start (sector)    End (sector)  Size       Code  Name
   4            2048          239615   116.0 MiB   8300

# bc <<< "(239615+1-2048)/2048"
116.00000000000000000000
```

**Comment by Mic92** [comment]
cc @rudolfvesely

**Comment by Mic92** [comment]
I guess than we should drop `--set-alignment` and only keep `--align-end`

**Comment by rudolfvesely** [comment]
> for 4K-native disks this results in 8 MiB alignment which is excessive

I completely agree that 8 MiB is excessive. Btw. @intelfx  , do you have an example of a cloud provider / hardware that shows up on Linux as 4k? All modern SSDs are 4k or more inside (physically) but outside (on Linux) they still show up as 512.

> I guess than we should drop --set-alignment and only keep --align-end.

I found this: https://www.rodsbooks.com/gdisk/advice.html

> When you specify a partition size in MiB or larger units, the partition-size end-alignment is automatic. It's only the last partition that might be affected by this policy, which is automatic in gdisk and cgdisk but must be activated by the new -I/--align-end option to sgdisk. You can override the feature by specifying an exact end sector in sgdisk, including by copying the end sector specified on the prompt line that shows the valid end sector values.

So dropping `--set-alignment` should work and @intelfx tested that on a loop device above (thank you for testing).

@intelfx :
Could you please confirm that the alignment with `--align-end` is in MiB regardless if you give sgdisk a specific size in MiB or no size at all?

**Comment by intelfx** [comment]
> I guess than we should drop `--set-alignment` and only keep `--align-end`.

Yes, that's my impression as well.

**Comment by rudolfvesely** [comment]
> Yes, that's my impression as well. I'll make a PR.

@intelfx Did you see my questions?

**Comment by intelfx** [comment]
@rudolfvesely No, sorry, the GitHub app didn't load the comment for some reason and my mail is broken atm.

> Could you please confirm that the alignment with --align-end is in MiB regardless if you give sgdisk a specific size in MiB or no size at all?

Yes, except when you give it a specific size that is not a multiple of a MiB (but that's also the case when the alignment was explicitly specified).
