### ISSUE TITLE
Feature Request: please support ZFS

### ISSUE THREAD

**Issue by mkgvt** [nix-community/disko#5]
Having lost some important files to bit rot, I've switched to using ZFS exclusively. Would you please consider supporting ZFS, both unencrypted and natively-encrypted?

**Comment by Mic92** [comment]
I think @Lassulus would accept zfs support but I don't think he would implement it.

**Comment by Lassulus** [comment]
I actually use zfs on 2-3 systems now :D Maybe I will come around to implement it

**Comment by Mic92** [comment]
I am happy to test. My recommendation is to split formatting partitions to have a separate pool option that zfs-formatted partitions are assigned to and on the pools are number of datasets are defined.

**Comment by Mic92** [comment]
We had yesterday a discussion on how to support this feature and lassulus is implementing this now.

**Comment by Lassulus** [comment]
https://github.com/nix-community/disko/pull/27
