### ISSUE TITLE
label use partlabel instead of label

### ISSUE THREAD

**Issue by Simon-Kenn** [nix-community/disko#515]
hello everyone,
Is it possible to set label from disko ? The partition options set partlabel instead.

Thanks

**Comment by Lassulus** [comment]
partition labels are automatically generated and are used to mount/format the disks.

for filesystem labels you can use something like `extraArgs = "-L myLabel";` inside the filesystem type. Although the usage can differ for different filesystems.

**Comment by Simon-Kenn** [comment]
It work perfectly, thanks !

**Comment by Mic92** [comment]
Untested but something like this:

```diff
{
  disko.devices = {
    disk = {
      vdb = {
        device = "/dev/disk/by-id/some-disk-id";
        type = "disk";
        content = {
          type = "gpt";
          partitions = {
            ESP = {
              type = "EF00";
              size = "500M";
              content = {
                type = "filesystem";
                format = "vfat";
                mountpoint = "/boot";
              };
            };
            root = {
              size = "100%";
              content = {
                type = "filesystem";
                format = "ext4";
                mountpoint = "/";
+               extraArgs = "-L myLabel";
              };
            };
          };
        };
      };
    };
  };
}

```

**Comment by ritiek** [comment]
Have tested, this seems to work:
```nix
extraArgs = [ "-LmyLabel" ];
```

Had to also remove the space after `-L` flag otherwise it seems to be treated as a literal and so the label would evaluate as `\x20myLabel`.
