### ISSUE TITLE
Disko bcachefs install error

### ISSUE THREAD

**Issue by walseb** [nix-community/disko#516]
Hello!

I wanted to try out bcachefs, and followed the quick guide here.

After I run the installer, at the end, I got an error that bcachefs isn't supported. The reason is that bcachefs isn't included in Linux until Linux 6.7 (https://www.reddit.com/r/linux/comments/17kgxnp/bcachefs_has_been_merged_into_linux_67/) and the current NixOS installer runs an older kernel.

The fix is to build the ISO yourself with the latest kernel (without ZFS, as the build fails otherwise):
```
{ config, pkgs, ... }:
{
  imports = [
    <nixpkgs/nixos/modules/installer/cd-dvd/installation-cd-minimal-new-kernel-no-zfs.nix>
  ];
}
```
to build it, you need to run: `nix-build '<nixpkgs/nixos>' -A config.system.build.isoImage -I nixos-config=iso.nix`

Should this be included somewhere in the guide until 6.7 gets included in the installer? My first reaction after getting the error was to search here.

**Comment by walseb** [comment]
While I got further along with the latest kernel, I still get an error relating to bcachefs when running `nixos-generate-config`. I tried simply cloning my config and using the `hardware-configuration.nix` from my previous installation, but now it won't boot.
Perhaps `boot.supportedFilesystems = [ "bcachefs" ];` is needed when building the ISO, as detailed here: https://nixos.wiki/wiki/Bcachefs

**Comment by Mic92** [comment]
Yes. The kernel in the NixOS ISO is not new enough. You have to build your own.
