### ISSUE TITLE
btrfs creating snapshot of root beetween _create and _mount 

### ISSUE THREAD

**Issue by Simon-Kenn** [nix-community/disko#517]
Pretty new to disko and btrfs, i'm not sure it's a disko problem but maybe you can help me.

i create a btrfs root partition with 4 subvolume (nix, persist and swap), after using the command for formating my disk,
i am unable to use the command `btrfs subvolume snapshot -r /mnt/root /mnt/root-blank` after the script process, in my current understanding it should be done after creating the subvolume and before mounting them.

Is there a way to use a command beetween the _create and _mount part in a declarative way ?

The goal is to erase root beetween every reboot

**Comment by Simon-Kenn** [comment]
I didn't see, the postCreateHook options, i close the issue

**Comment by trueNAHO** [comment]
I suppose you resolved it with: https://github.com/Simon-Kenn/nixOs-sample/blob/main/nixos/disk.nix#L34-L39?
