### ISSUE TITLE
Support for day 2 operations like resizing

### ISSUE THREAD

**Issue by tboerger** [nix-community/disko#524]
Hello maintainers, this is really a great project but are there any plans to support day 2 operations like resizing partitions or volumes in case of LVM? Or even the addition of new partitions?

**Comment by Mic92** [comment]
Yes. It's on the wish list. @Lassulus could we not use partially systemd-repartd for this?

**Comment by dehnert** [comment]
I'm not sure of the limitations, but the incremental support in #568 probably helps with some things along these lines.

**Comment by dehnert** [comment]
I think this is a dup of #295

**Comment by iFreilicht** [comment]
Yes, I would say so, too.
