### ISSUE TITLE
security hole /boot and /boot/loader/random-seed

### ISSUE THREAD

**Issue by i-am-logger** [nix-community/disko#527]
I'm using disko to setup the partitions of my system via flake. 

started to get these warnings recently:

![image](https://github.com/nix-community/disko/assets/1440852/b79b45fb-9e00-4fea-8ef3-9b7552e42b87)

the proposed solution without disko is
```
  fileSystems."/boot" = {
    options = [ "umask=0077" ];
  };
```

though not sure how to set it with disko

**Comment by phaer** [comment]
> though not sure how to set it with disko

Exactly the same (if your disko config contains a /boot). Disko does configure the filesystems attribute, but those settings get merged with your own ones via the nixos module system

**Comment by Lassulus** [comment]
```
...
partitions = {
  boot = {
    type = "EF00";
    size = "500M";
	content = {
      type = "filesystem";
      format = "vfat";
      mountOptions = [ "umask=0077" ];
    };
  };
};
```

**Comment by iFreilicht** [comment]
Thank you for pointing this out! All the examples and documentation reflect this now.
