### ISSUE TITLE
Converting an existing system to use disko?

### ISSUE THREAD

**Issue by jh-devv** [nix-community/disko#570]
Hey!

Is converting an existing system to use disko, via reading the `/etc/fstab` possible?

This would help transferring my system and the flake to use impermanence!

**Comment by Mic92** [comment]
No. There is no such thing.

**Comment by Mic92** [comment]
The fstab alone would also not provide enough informations to do this. It doesn't contain partition information.

**Comment by jh-devv** [comment]
> The fstab alone would also not provide enough informations to do this. It doesn't contain partition information i.e. size, type etc

Oh yeah, I probably have to manually do that based on my FSTab and partition table.

**Comment by Lassulus** [comment]
There is no such thing yet, but there could be. Probably not in the nixos module code directly, but we could build something with python or jq?

**Comment by Mic92** [comment]
Maybe we can fund some UI for a graphical partition editor eventually?
