### ISSUE TITLE
How do I use disko command line?

### ISSUE THREAD

**Issue by guilhermehas** [nix-community/disko#58]
I am with files:

`flake.nix`
```nix
{
  inputs.disko.url = "github:nix-community/disko";
  inputs.disko.inputs.nixpkgs.follows = "nixpkgs";

  outputs = { self, nixpkgs, disko }: rec {
    # change `yourhostname` to your actual hostname
    nixosConfigurations.nixos = nixpkgs.lib.nixosSystem {
      # change to your system:
      system = "x86_64-linux";
      modules = [
        ./configuration.nix
        disko.nixosModules.disko
      ];
    };
    defaultPackage.x86_64-linux = nixosConfigurations.nixos.config.system.build.toplevel;
  };
}
```

`configuration.nix`
```nix
{
  pkgs,
  lib,
  ...
}:
{
  boot.loader.grub.devices = [ "/dev/sda" ];
  system.stateVersion = "22.05";
  # checkout the example folder for how to configure different diska layouts
  disko.devices = {
    disk.sda = {
      device = "/dev/sda";
      type = "disk";
      content = {
        type = "table";
        format = "gpt";
        partitions = [
          {
            type = "partition";
            name = "ESP";
            start = "1MiB";
            end = "100MiB";
            bootable = true;
            content = {
              type = "filesystem";
              format = "vfat";
              mountpoint = "/boot";
            };
          }
          {
            name = "root";
            type = "partition";
            start = "100MiB";
            end = "100%";
            part-type = "primary";
            bootable = true;
            content = {
              type = "filesystem";
              format = "ext4";
              mountpoint = "/";
            };
          }
        ];
      };
    };
  };
}
```

When I try to use `disko -f #nixosConfiguration`, I got an error:
```
error: syntax error, unexpected end of file

       at «string»:1:1:

            1|
             | ^
```

**Comment by Lassulus** [comment]
I have this repo here which I used for testing https://github.com/Lassulus/flakes-testing
basically you need to put your disko config additionally into diksoConfiguration.$hostname. then you can use the disko cli with `-f $flakeurl#$hostame`

**Comment by Lassulus** [comment]
If you have more questions, or ideas for a better interface I'm happy to help :)

**Comment by guilhermehas** [comment]
If I run:
```sh
disko --flake github:Lassulus/flakes-testing#fnord
```
it works.

But if I try to run:
```sh
 git clone git@github.com:Lassulus/flakes-testing.git
 cd flakes-testing
 disko --flake .#fnord
 ```
 It does not work with error:
 ```
 error: syntax error, unexpected '.'

       at «string»:1:1:

            1| .
             | ^
 ```

**Comment by zarelit** [comment]
@guilhermehas  I'm using "." with dry-run to work locally and inspect the script. `nix-build` wants a full URI so you can work around this by using something like `disko -m create --dry-run --flake "path:$(pwd)#fnord"`

**Comment by guilhermehas** [comment]
Thanks for the suggestion. It worked.

**Comment by Lassulus** [comment]
I basically copied the flake eval code from nixos-install. if "." is something we want to support I can add that

**Comment by zarelit** [comment]
@Lassulus I think it would be useful to support, especially when the flake is private and you just move the directory of the repo around instead of letting nix fetch it. The `path:` workaround would accidentally bring in the store secrets that are in the .gitignore so it would be nice to have nix itself "resolve" the flake URI, but it will bring jq in the closure
TBF the above command is copied from nixos-shell :grin:

**Comment by Lassulus** [comment]
can you add a new issue? I will implement it probably next week. maybe this week if I can find some time

**Comment by guilhermehas** [comment]
> @guilhermehas I'm using "." with dry-run to work locally and inspect the script. `nix-build` wants a full URI so you can work around this by using something like `disko -m create --dry-run --flake "path:$(pwd)#fnord"` or better make nix resolve it beforehand: `nix flake metadata --extra-experimental-features "nix-command flakes" --json -- "." | jq -r .url`

This command is not working anymore:
```sh
disko -m create --dry-run --flake "path:$(pwd)#fnord
```
I received the error:
```
error: evaluation aborted with the following error message: 'fnord does not exist'
```

I don't know if I am doing anything different or if the code is now broken.

**Comment by Lassulus** [comment]
do you have my flakes-testing repo cloned? I moved stuff around a bit to test a new way to declare the partiton script. otherwise, I don't think I changed any of the flakes logic in disko in the last couple of days, but I could be mistaken

**Comment by guilhermehas** [comment]
> do you have my flakes-testing repo cloned? I moved stuff around a bit to test a new way to declare the partiton script. otherwise, I don't think I changed any of the flakes logic in disko in the last couple of days, but I could be mistaken

Your new commit broke in flakes-testing broke it.
It is now working in an old version of it.

**Comment by onny** [comment]
> > do you have my flakes-testing repo cloned? I moved stuff around a bit to test a new way to declare the partiton script. otherwise, I don't think I changed any of the flakes logic in disko in the last couple of days, but I could be mistaken
> 
> Your new commit is broken in flakes-testing. It is now working in an old version of it.

Can you give an example? Currently I'm unable to get it working :(
