### ISSUE TITLE
QUESTION: neededForBoot option

### ISSUE THREAD

**Issue by aShabat** [nix-community/disko#594]
How can I add neededForBoot or another nixos options to a filesystem? Right now I'm doing it outside of disko module, but would prefer to have a way of configuring it with disko.

**Comment by Lassulus** [comment]
doing it via fileSystems is the expected way. Not sure if we want to replicate all fileSystems options in disko?

**Comment by jpds** [comment]
Dup of #192.

**Comment by iFreilicht** [comment]
> Not sure if we want to replicate all fileSystems options in disko?

The linked thread gives an example where this flag would influence the behavior of disko itself. That seems to be decent justification.

> Dup of `#192`.

Agreed.
