### ISSUE TITLE
CLI fails to run if there is no nixpkgs channel

### ISSUE THREAD

**Issue by emilazy** [nix-community/disko#60]
I run flake-only setups, so any invocation of the CLI leads to `error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I)`. Ideally it'd pin to the nixpkgs `disko` was built with, but failing that `builtins.getFlake` could be used (in impure mode only).

**Comment by Lassulus** [comment]
hmm, usually the cli is for installations. To better understand the usecase it would be good to know how you typically install a new system?

**Comment by emilazy** [comment]
Yeah I think pinning nixpkgs would be ideal. My use case here was trying to evaluate a configuration on a flakes-only local desktop with `--dry-run` before pushing it to a server, which also ran into Darwin compatibility issues (#64 should help with that, but there's also #59).

**Comment by Lassulus** [comment]
is this still a problem?

**Comment by emilazy** [comment]
Seems to work now.
