### ISSUE TITLE
typo in the docs?

### ISSUE THREAD

**Issue by bam80** [nix-community/disko#607]
https://github.com/nix-community/disko/blob/1efd500e9805a9efbce401ed5999006d397b9f11/docs/disko-install.md?plain=1#L131-L133

What I need to make sure? The phrase seems broken to me.

**Comment by iFreilicht** [comment]
Thank you for the heads-up! Please have a look at the linked PR and let me know if this helps.

**Comment by bam80** [comment]
Yes, that helped. Thanks.
