### ISSUE TITLE
Can't specify sizes relative to end of disk

### ISSUE THREAD

**Issue by emilazy** [nix-community/disko#61]
`end = "-8GiB";` will cause `parted` to try to parse `-8GiB` as options and bail out. `--` should be passed before the partitioning commands, as called out in [the `parted` manual](https://www.gnu.org/software/parted/manual/html_node/mkpart.html).

**Comment by Lassulus** [comment]
should be fixed by c60f20ceffd9cd662aad8482dd1bdeed472d75c2
