### ISSUE TITLE
how to to pass flake `self` using `specialArgs`?

### ISSUE THREAD

**Issue by bam80** [nix-community/disko#611]
https://github.com/nix-community/disko/blob/b8785a1c37f6176b6bc3d2939df329ab3a8f226c/docs/disko-install.md?plain=1#L187-L188

Could you clarify how exactly I could pass the flake `self` using `specialArgs`?

Thank you.

**Comment by Mic92** [comment]
I would appreciate if you could update the documentation, now that the question is answered in discourse.
