### ISSUE TITLE
How can I migrate my setup to Disko (without losing data)?

### ISSUE THREAD

**Issue by AndersonTorres** [nix-community/disko#619]
Hello!
I want to test Disko in my [current setup](https://github.com/atorres1985-junkyard/etc/blob/trunk/nixos-configs/pantera/hardware-configuration.nix).
Is it possible to convert this to Disko without requiring things like a full reinstall?

**Comment by Mic92** [comment]
Generally speaking no. We have very limited support to make some operation idempotent:
https://github.com/nix-community/disko/pull/595 https://github.com/nix-community/disko/pull/568
