### ISSUE TITLE
diskoImagesScript creates host's user home dir with some garbage leftovers

### ISSUE THREAD

**Issue by pedohorse** [nix-community/disko#622]
after running `nix build .#nixosConfigurations.myhost.config.system.build.diskoImagesScript` the resulting image has additional home dir created for host's user that ran the command (the user itself is not created, and that dir is owned by root). 

That dir contains single `.nix-defexpr` dir with `channels`->`/tmp/state/profiles/per-user/root/channels` broken link.

I assume that's some leftovers from building process that should not be there.

**Comment by Mic92** [comment]
Weird. No idea where these are coming from. We don't have this string in any of our code.

**Comment by Mic92** [comment]
Ok. Can you make a pull request?

**Comment by pedohorse** [comment]
oh, I can try, but i've just recently discovered this repo and don't know much about all features and commands disco provides, so can you point me towards where I should look to add that cleanup?

from a brief look it seems that cleanup should be added somewhere here, no?
https://github.com/nix-community/disko/blob/cb1d6fba694ab3887600d606106f5a044ba1712c/lib/make-disk-image.nix#L73-L74

**Comment by Mic92** [comment]
We should probably clear out as much as possible environment variables. Does overriding home has any other side effects?

**Comment by pedohorse** [comment]
I've just cleaned up everything, except origBuilder though preVM script

but it relies on env being passed through `xchg/saved-env` file, and I'm not sure if this is a spec, or implementation detail for `vmRunCommand`

here's an example: https://github.com/nix-community/disko/pull/639

It does seem to work fine, but i only tested a few configs for `config.system.build.diskoImagesScript`, nothing else
