### ISSUE TITLE
Can disko-install support functions similar to nixos-rebuild --build-host?

### ISSUE THREAD

**Issue by I-Want-ToBelieve** [nix-community/disko#637]
Compiling using a remote host is useful for devices with very weak CPU performance

**Comment by Kreyren** [comment]
+1 i am unable to build my `github:kreyren/nixos-config#tsvetan` on OLIMEX Teres-I as trying to process the config on the device itself causes it to halt.

**Comment by Kreyren** [comment]
Declaring `builders` in `nix.conf`` can be used to manage this issue, potentially also through the `--option` flag as `--option builders 'ssh://somewhere x86_64-linux'`
