### ISSUE TITLE
How to use `sops-nix` when first partitioning disk with `disko`?

### ISSUE THREAD

**Issue by poperigby** [nix-community/disko#641]
How do I go about using `sops-nix` to supply a LUKS password when I'm first partitioning my disks?

This is the Nix file I define my disks in:

```nix
{ config, ... }:

{
    # Setup the primary disk
    disko.devices.disk.primary = {
        device = "/dev/nvme0n1";
        type = "disk";
        content = {
            type = "gpt";
            partitions = {
                esp = {
                    # This code corresponds to a EFI system partition
                    type = "EF00";
                    size = "500M";
                    content = {
                        type = "filesystem";
                        format = "vfat";
                        mountpoint = "/boot";
                    };
                };
                root = {
                    # Take up the rest of the space on the disk
                    size = "100%";
                    content = {
                        name = "root";
                        type = "luks";
                        passwordFile = config.sops.secrets."snowy/luks_password".path;
                        settings.allowDiscards = true;
                        content = {
                            type = "btrfs";
                            subvolumes = {
                                "@" = {
                                    mountpoint = "/";
                                    mountOptions = [ "noatime" ];
                                };
                                "@home" = {
                                    mountpoint = "/home";
                                    mountOptions = [ "compress=zstd" "noatime" ];
                                };
                                "@nix" = {
                                    mountpoint = "/nix";
                                    mountOptions = [ "compress=ztsd" "noatime" ];
                                };
                            };
                        };
                    };
                };
            };
        };
    };

    sops.secrets = {
        "snowy/luks_password" = {};
    };
}
```

Then I partition with this command:

```bash
sudo disko --mode disko --flake ~/config#snowy
```

I then get this output:

```
trace: true
these 2 derivations will be built:
  /nix/store/dg8x1iflyrpkbn2fpl0w2qb1ghbdlnx6-disko.drv
  /nix/store/7qaqxkbwkxj78k3nkfgqy9ddnr30j9dy-disko.drv
building '/nix/store/dg8x1iflyrpkbn2fpl0w2qb1ghbdlnx6-disko.drv'...
building '/nix/store/7qaqxkbwkxj78k3nkfgqy9ddnr30j9dy-disko.drv'...
umount: /mnt: not mounted
++ realpath /dev/vda
+ disk=/dev/vda
+ lsblk -a -f
NAME  FSTYPE   FSVER            LABEL                      UUID                                 FSAVAIL FSUSE% MOUNTPOINTS
loop0 squashfs 4.0                                                                                    0   100% /nix/.ro-store
loop1
loop2
loop3
loop4
loop5
loop6
loop7
sr0   iso9660  Joliet Extension nixos-minimal-24.05-x86_64 1980-01-01-00-00-00-00                     0   100% /iso
vda
+ lsblk --output-all --json
+ bash -x
++ dirname /nix/store/pin3a1kj24rp3axk9f1f0n00yxgr7div-disk-deactivate/disk-deactivate
+ jq -r --arg disk_to_clear /dev/vda -f /nix/store/pin3a1kj24rp3axk9f1f0n00yxgr7div-disk-deactivate/disk-deactivate.jq
+ set -fu
++ zdb -l /dev/vda
++ sed -nr 's/ +name: '\''(.*)'\''/\1/p'
+ zpool=
+ [[ -n '' ]]
+ unset zpool
++ lsblk /dev/vda -l -p -o type,name
++ awk 'match($1,"raid.*") {print $2}'
+ md_dev=
+ [[ -n '' ]]
+ wipefs --all -f /dev/vda
+ dd if=/dev/zero of=/dev/vda bs=440 count=1
1+0 records in
1+0 records out
440 bytes copied, 0.000254363 s, 1.7 MB/s
+ lsblk -a -f
NAME  FSTYPE   FSVER            LABEL                      UUID                                 FSAVAIL FSUSE% MOUNTPOINTS
loop0 squashfs 4.0                                                                                    0   100% /nix/.ro-store
loop1
loop2
loop3
loop4
loop5
loop6
loop7
sr0   iso9660  Joliet Extension nixos-minimal-24.05-x86_64 1980-01-01-00-00-00-00                     0   100% /iso
vda
++ mktemp -d
+ disko_devices_dir=/tmp/tmp.ZGKrk7K4Uw
+ trap 'rm -rf "$disko_devices_dir"' EXIT
+ mkdir -p /tmp/tmp.ZGKrk7K4Uw
+ device=/dev/vda
+ imageSize=2G
+ name=primary
+ type=disk
+ device=/dev/vda
+ efiGptPartitionFirst=1
+ type=gpt
+ blkid /dev/vda
+ sgdisk --clear /dev/vda
Creating new GPT entries in memory.
The operation has completed successfully.
+ sgdisk --align-end --new=1:0:+500M --change-name=1:disk-primary-esp --typecode=1:EF00 /dev/vda
The operation has completed successfully.
+ partprobe /dev/vda
+ udevadm trigger --subsystem-match=block
+ udevadm settle
+ sgdisk --align-end --new=2:0:-0 --change-name=2:disk-primary-root --typecode=2:8300 /dev/vda
The operation has completed successfully.
+ partprobe /dev/vda
+ udevadm trigger --subsystem-match=block
+ udevadm settle
+ device=/dev/disk/by-partlabel/disk-primary-esp
+ extraArgs=()
+ declare -a extraArgs
+ format=vfat
+ mountOptions=('defaults')
+ declare -a mountOptions
+ mountpoint=/boot
+ type=filesystem
+ blkid /dev/disk/by-partlabel/disk-primary-esp
+ grep -q TYPE=
+ mkfs.vfat /dev/disk/by-partlabel/disk-primary-esp
mkfs.fat 4.2 (2021-01-31)
+ additionalKeyFiles=()
+ declare -a additionalKeyFiles
+ askPassword=
+ device=/dev/disk/by-partlabel/disk-primary-root
+ extraFormatArgs=()
+ declare -a extraFormatArgs
+ extraOpenArgs=()
+ declare -a extraOpenArgs
+ initrdUnlock=1
+ keyFile=
+ name=root
+ passwordFile=/run/secrets/snowy/luks_password
+ settings=(['allowDiscards']='1')
+ declare -A settings
+ type=luks
+ blkid /dev/disk/by-partlabel/disk-primary-root
+ blkid /dev/disk/by-partlabel/disk-primary-root -o export
+ grep -q '^TYPE='
+ cryptsetup -q luksFormat /dev/disk/by-partlabel/disk-primary-root --key-file /dev/fd/63
++ set +x
cat: /run/secrets/snowy/luks_password: No such file or directory
Nothing to read on input.
+ rm -rf /tmp/tmp.ZGKrk7K4Uw
```

**Comment by Kreyren** [comment]
Same problem with ragenix, it seems to be looking for the secret on the booted system that is used for deployment so i workarounded that by adding a file to `/run/agenix/myfile` with the password that then successfully deploys, but this is terrible solution security-wise.

**Comment by Ai-Elias** [comment]
I am also interested in knowing what the proper way to pass in sops-nix secrets into the disko config is as I get the  "No such file or directory" exception currently aswell. It seems that adding in the "config" parameter as a requirement is not enough.

**Comment by Mic92** [comment]
sops-nix requires a system activation, so it won't work well outside the installed system unless you manually unpack the key to the target location prior to sops-nix.

So the only work around I currently see is that the NixOS installer needs to have the secret in very same location i.e. `/run/secrets/snowy/luks_password`.
If you use nixos-anywhere for installation you can use the `--disk-encryption-keys` flag to automate this.

**Comment by Mic92** [comment]
But another question, given your example configuration, how should password file works in general? Even if disko would provide the key file, it won't be available at boot time anyway, rendering an unbootable system.

**Comment by poperigby** [comment]
Hmm, that's a good point. So we'll just have to manually move around our disk encryption files?

**Comment by Mic92** [comment]
But where do you store the encryption key? If you put it into another unencrypted partition, than you could as well not encrypt your disk at all.

**Comment by poperigby** [comment]
Wait a second, you don't need to store the password file anywhere. The password just needs to be read by Disko for the intial encryption setup and then you type it in every time you boot.

**Comment by poperigby** [comment]
I think you would just need sops to decrypt your LUKS password and place it in `/tmp` to be used with something like this: https://github.com/nix-community/disko/blob/5f7bdc72053380270f2a88690a14292c63cd5643/example/luks-interactive-login.nix#L25

It would only be needed for the first time setup.

**Comment by Kreyren** [comment]
Or like considering that i can make it work by supplying the secrets in `/run/agenix/myfile` -> Just make a management that places the secrets from a generatable bootable media?

**Comment by poperigby** [comment]
Yes, but that would be less convenient because you would have to copy over both your password file and encryption key for agenix/sops-nix.

**Comment by Kreyren** [comment]
> Yes, but that would be less convenient because you would have to copy over both your password file and encryption key for agenix/sops-nix. -- @poperigby (https://github.com/nix-community/disko/issues/641#issuecomment-2138292247)

Like if you want convidience we can probably grab the files from the `secrets.nix` and decrypt them in the `/run/agenix` prior to the system initialization.. At least that seems like the most sane path of least resistance to me.

**Comment by poperigby** [comment]
This is what I came up with in my custom installation script:

```bash
export SOPS_AGE_KEY_FILE=$AGE_KEY_FILE
${sops}/bin/sops --decrypt --extract "['$TARGET_HOST']['luks_password']" "$CONFIG_DIR/secrets/secrets.yaml" > /tmp/luks_password
```

**Comment by tobiasBora** [comment]
> But where do you store the encryption key? If you put it into another unencrypted partition, than you could as well not encrypt your disk at all.

The use-case I have in mind is the following: I want my system to boot automatically (I want it to be reliable so I don't want to type the password at every reboot for now as the system may reboot due to a power shortage… maybe I'll change my mind later), but I also want to encrypt the ZFS partition so that ZFS incremental raw backup is encrypted automatically (this will be sent to an external server I may not trust). Hence, I was thinking to put in the `/boot` EFI partition a file with the key to be used by the current system, and I won't, of course, backup this file to my untrusted server. Curious to see how easy it is to do, ideally combining sops (to hide the password in my git repo), disko, and nixos-anywhere…
