### ISSUE TITLE
`disko-install` and traditional installation both lead to an infinite blinking cursor after download and build finish

### ISSUE THREAD

**Issue by AidanWelch** [nix-community/disko#663]
It may be an issue in my flake so here it is:

```nix
{
  inputs.nixpkgs.url = "github:nixos/nixpkgs?ref=nixos-unstable";
  inputs.disko.url = "github:nix-community/disko";
  inputs.disko.inputs.nixpkgs.follows = "nixpkgs";

  outputs = { self, disko, nixpkgs }: {
    nixosConfigurations.mymachine= nixpkgs.legacyPackages.x86_64-linux.nixos [
      ./configuration.nix
      disko.nixosModules.disko
      {
        disko.devices = {
          disk = {

            main = {
              device = "/dev/nvme0n1";
              type = "disk";
              content = {
                type = "gpt";
                partitions = {
                  ESP = {
                    type = "EF00";
                    size = "500M";
                    content = {
                      type = "filesystem";
                      format = "vfat";
                      mountpoint = "/boot";
                    };
                  };
                  root = {
                    size = "100%";
                    content = {
                      type = "filesystem";
                      format = "ext4";
                      mountpoint = "/";
                    };
                  };
                };
              };
            };
            
            internal = {
              device = "/dev/mmcblk1";
              type = "disk";
              content = {
                type = "gpt";
                partitions = {
                  root = {
                    end = "-1G";
                    content = {
                      type = "filesystem";
                      format = "ext4";
                      mountpoint = "/mnt/internal";
                    };
                  };
                  encryptedSwap = {
                    size = "10M";
                    content = {
                      type = "swap";
                      randomEncryption = true;
                      priority = 100;
                    };
                  };
                  plainSwap = {
                    size = "100%";
                    content = {
                      type = "swap";
                      discardPolicy = "both";
                      resumeDevice = true;
                    };
                  };
                };
              };
            };

          };
        };
      }
    ];
  };
}
```

And I tried

`sudo nix --experimental-features "nix-command flakes" run "github:nix-community/disko#disko-install" -- --write-efi-boot-entries --flake "/mnt/sd/nixos#mymachine"`

as well as

`sudo nix --experimental-features "nix-command flakes" run github:nix-community/disko -- --mode disko --flake "/mnt/sd/nixos#mymachine"`

both with the same result
![photo_2024-06-03_21-02-01](https://github.com/nix-community/disko/assets/35280359/1822c239-fa95-4a5a-a7a6-f1400dad26a2)

**Comment by Lassulus** [comment]
do you have internet on the installer? usually there should be some output either way. you can try running a nix repl and do `:lf /mnt/sd/nixos` in there and then try to build the formatScript directly:
`:b nixosConfiguration.mymachine.config.system.build.diskoScript`

**Comment by AidanWelch** [comment]
`:lf /mnt/sd/nixos` failed at first so I had to run `nix flake update --experimental-features "nix-command flakes"` in the dir because the repl I guess has an option passed to not update flakes.   After fixing that, `:b nixosConfigurations.mymachine.config.system.build.diskoScript` worked, but before that I tried `disko-install` again, so I don't think the lack of the flake-lock was a problem.  How do I now call the built format script?

**Comment by AidanWelch** [comment]
Actually, found it in `/nix/store/[hash]-disko/bin/disko`, it formatted without issue when executed so I don't know why the other commands failed.

**Comment by iFreilicht** [comment]
> Actually, found it in `/nix/store/[hash]-disko/bin/disko`, it formatted without issue when executed so I don't know why the other attempts failed.

Just for future reference, the repl should display output something like this:

```
nix-repl> :b nixosConfigurations.junction.config.system.build.diskoScript

This derivation produced the following outputs:
  out -> /nix/store/446i7qiah03nxfkmbv2wr69qdfyjrbvr-disko
```

The `out` path is a link to the script.

Anyway, did you manage to fix this issue?

**Comment by AidanWelch** [comment]
> Anyway, did you manage to fix this issue?

Sorry, I don't remember, but I assume that means I did.

**Comment by iFreilicht** [comment]
No worries, then I'll just close this issue for now. Feel free to reopen it if you find this is still a problem.

In case you're not OP and found this issue in your search for a solution, please open a new issue and link this one instead of posting a reply here :)
