### ISSUE TITLE
Argument doesn't exist `--write-to-disk </dev/disk>` but is documented

### ISSUE THREAD

**Issue by dvaerum** [nix-community/disko#664]
Hey,

I can see that the argument `--write-to-disk </dev/disk>` is documented here:

https://github.com/nix-community/disko/blob/master/docs/disko-images.md?plain=1#L73-L76

But I have not been able to find the function anywhere in the code, but I was able to find the 3 other arguments (`--pre-format-files`, `--post-format-files` and `--build-memory`) which were documented along with `--write-to-disk`
https://github.com/nix-community/disko/blob/master/lib/make-disk-image.nix#L128-L153

So, is the argument `--write-to-disk` something there is coming in the future, or is it a mistake?

**Comment by pinpox** [comment]
Still present in master: https://github.com/nix-community/disko/blob/380847d94ff0fedee8b50ee4baddb162c06678df/docs/disko-images.md?plain=1#L107

**Comment by iFreilicht** [comment]
Thank you, opened  #860 to fix this
