### ISSUE TITLE
Use Disko with "nixos-rebuild build-vm"

### ISSUE THREAD

**Issue by arjan-s** [nix-community/disko#668]
My system configs are all using Disko for partitioning and mounting, which is fantastic. However, sometimes I would like to test stuff without rebooting, so I would like to use `nixos-rebuild build-vm` for that. That doesn't seem to be supported currently, because booting the VM results in the boot process waiting indefinitely for the root partition to be found.

I've found the same question [at least here](https://discourse.nixos.org/t/use-disko-with-nixos-rebuild-build-vm-with-bootloader-or-something-similar/44895) and [possibly here](https://discourse.nixos.org/t/how-to-create-a-virtual-machine-with-a-filesystem-defined-by-nixos-virtualisation-module/43396), which sadly didn't receive any answers.

My question is how hard this would be to achieve, and additionally whether it can be added to the documentation somewhere.

**Comment by brianmcgee** [comment]
I was thinking of something similar as I was playing around with the `vmVariant` config and the `config.system.build.vm` target to try and simulate my desktop machine, disk setup and all. @Lassulus pointed out there's the `config.system.build.installTest` which will spin up a VM and check your `disko` config can install correctly. 

It would be nice of that could be re-purposed to mix in the necessary config to `vmVariant` so you can fire up an interactive VM instead.

**Comment by Mic92** [comment]
If you manually import this module in your nixos configuration: https://github.com/NixOS/nixpkgs/blob/717c708df2ed4488bff130f9c34c16de7b419f4a/nixos/modules/virtualisation/build-vm.nix#L9
you should be able to debug what's going on with the `config.fileSystems` in when loading your nixos configuration into a nix repl: https://nixos-and-flakes.thiscute.world/best-practices/debugging

**Comment by Mic92** [comment]
Interestingly build-vm now works on my machine? Does someone has a broken configuration for me?

**Comment by Enzime** [comment]
Closing this as it should be working as of #713

If you're running flakes, you can run:

```
nix run .#nixosConfigurations.<hostname>.config.system.build.vmWithDisko
```

There's also documentation available here: https://github.com/nix-community/disko/blob/master/docs/interactive-vm.md
