### ISSUE TITLE
[regression?] disko generatesdd unbootable fstab after nixos-rebuild

### ISSUE THREAD

**Issue by ppenguin** [nix-community/disko#695]
On a vps instance (I usually update them with `nixinate` from a dev host and occasionally reboot) I suddenly had an unbootable nixos, because `disko` generated

`/etc/fstab`:

```
# Filesystems.
/dev/disk/by-partlabel/disk-vda-root / ext4 x-initrd.mount,defaults 0 1
/dev/disk/by-partlabel/disk-vda-ESP /boot vfat defaults 0 2
```

where in fact:
```
[root@nixos:/]# ls -la /dev/disk/by-partlabel/
total 0
drwxr-xr-x  2 root root  80 Jul  2 15:39 .
drwxr-xr-x 11 root root 220 Jul  2 15:40 ..
lrwxrwxrwx  1 root root  10 Jul  2 15:39 ESP -> ../../vda1
lrwxrwxrwx  1 root root  10 Jul  2 15:39 root -> ../../vda2
```

I didn't change `disko.nix` since the last working version, I just updated `nixpkgs`. (Since it's a multi-host flake and this particular server hadn't been updated a long time I'm not sure what the last working version was based on).

Specifying the label explicitly (as in #515) didn't have any effect, so I finally specified the filesystems manually instead of via disko, to make the system bootable again...

**Comment by Mic92** [comment]
Looks you have switched but from table="gpt" to the gpt type, but you didn't update the labels manually as described here: https://github.com/nix-community/disko/blob/master/docs/table-to-gpt.md

**Comment by ppenguin** [comment]
> Looks you have switched but from `table="gpt"` to the gpt type, but you didn't update the labels manually as described here:
> 
> https://github.com/nix-community/disko/blob/master/docs/table-to-gpt.md#create-gpt-partition-labels

@Mic92 Thanks, yes indeed I hadn't done the re-labelling since I was completely unaware of that requirement. Not sure if there would have been a way to avoid this, like a big fat warning or detection logic in the activation script? Or maybe there was but not visible for remote deploys (`nixinate` and `deploy-rs`)?

Anyway, that might be becoming moot as this propagates in the installed base (even though I had this happen again with soime pain a week ago on another server because I had all but forgotten about it while focusing on going from `nixinate` to `deploy-rs`).

**Comment by Mic92** [comment]
This would need to be done at runtime, so unsure how. However affected systems usually can be rolled back at least.
