### ISSUE TITLE
NILFS2 support?

### ISSUE THREAD

**Issue by dmadisetti** [nix-community/disko#704]
https://docs.kernel.org/filesystems/nilfs2.html

Would you be open to a PR?

**Comment by dmadisetti** [comment]
Might work out of the box. Will report back

**Comment by dmadisetti** [comment]
Yeah, this works out of the box. `nilfs-utils` is required though: https://search.nixos.org/packages?channel=24.05&from=0&size=50&sort=relevance&type=packages&query=nilfs-utils

And possibly the `nilfs2` kernel module (Not sure, I did both at the same time, but `modprobe nilfs2` might be fine without requiring reboot if it is required)

**Comment by Mic92** [comment]
disko can pull in additional tools automatically depending on the filesystem. Checkout this: https://github.com/nix-community/disko/pull/740

**Comment by dmadisetti** [comment]
Oh nice. Will add and test if I format my system.

Thanks
