### ISSUE TITLE
control inode amount

### ISSUE THREAD

**Issue by teto** [nix-community/disko#707]
I would like to increase in some way the number of inodes for an ext4 system. It's for a gitlab runner where i usually hit the inode limit before the disk space limit. I am evaluating disko for that purpose, is it possible to achieve this level of configuration ?

**Comment by iFreilicht** [comment]
Yes, indeed. You can use `extraArgs` for this, which will be joined with spaces and passed to `mkfs.ext4`:

```nix
...
{
  type = "filesystem";
  format = "ext4";
  extraArgs = [ "-N" 123456789012345 ];
  mountpoint = "/";
}
...
```

**Comment by teto** [comment]
cool ty
