### ISSUE TITLE
Impermanence with /nix bind mount and disko-install

### ISSUE THREAD

**Issue by beviu** [nix-community/disko#718]
Hi, thanks for this great project.

I would like to use disko with [impermanence](https://nixos.wiki/wiki/Impermanence). In my desired setup, I have a single filesystem that is the persistent filesystem. It is mounted at `/persistent` and the initrd bind mounts `/nix` to `/persistent/nix` (and likewise for the other persisted directories). However, during installation I do want that filesystem to be mounted at `/` so that `nixos-install` can write to `/nix`.

Currently, I use set the `mountpoint` option in my disko configuration to `/persistent` and use `lib.mkForce` to change the mountpoint path in my NixOS configuration.

I propose adding an option for specifying a separate mountpoint used only during installation: #717.

**Comment by iFreilicht** [comment]
To be perfectly honest, this feels like an uncommon edge-case that you already have a solution for. I'm not sure adding an option like you propose is worth implementing.

Plus, as discussed in the PR, the `mount` mode doesn't distinguish between installation and regular operation right now. Another solution would be to turn your `disk-config.nix` into a function with a default argument. For example:

```nix
{
  installation ? false
}:
{
  disko.devices = {
     ...
     mountpoint = if installation then "/" else "/persistent";
     ...
  };
}
```

And then run disko with `--arg installation true` during installation.

Granted, I didn't try this, but it should work.

**Comment by beviu** [comment]
Oh yes this is a great idea, thank you! I agree that it's an uncommon edge case 😅. I will close this issue.

**Comment by MagicRB** [comment]
This is still an issue. And `--arg installation true` is not a nice solution in my opinion
