### ISSUE TITLE
How to declare BTRFS Quotas (qgroups, squotas)

### ISSUE THREAD

**Issue by Ai-Elias** [nix-community/disko#733]
What is the correct way to create BTRFS quotas using this tool? For my simple case, I just need to simply limit the maximum size of by /home subvolume.

Apologies if there is an example or some documentation for this out in the wild, I couldn't find it after extensive searching.

**Comment by Mic92** [comment]
I don't think there is any support for this. There are some hooks that can run your own code. But you can also start by defining what disko configuration should look like and what commands you want it to run and maybe someone can pick it up.

**Comment by Ai-Elias** [comment]
That's unfortunate, I imagine the problem here is that BTRFS doesn't expose qgroups as a mount option, instead having a command to control this behavior. Either way, going to close this.

**Comment by Lassulus** [comment]
commands are fine to control that behaviour, it's just that no one put in the time to build an interface in disko to that command :) for a start you can run those commands in the postCreateHook of the btrfs filesystem you use and maybe, at a later point, we can add some options to disko.

**Comment by Ai-Elias** [comment]
That sounds like it should work fine. Thank you!
