### ISSUE TITLE
zpool is not created due to stubborn fs signature 

### ISSUE THREAD

**Issue by ghostbuster91** [nix-community/disko#734]
Hi, 

It seems that `sgdisk --clear` &/or `wipefs -a` are not enough to clear fs signatures. 

This problematic because if the fs signatures are not cleared correctly `blkid` will report them causing the disko script to malfunction. 

I was finally able to get rid of these signatures by manually writing zeros to the partition header:
```
sudo dd if=/dev/zero of=/dev/sda1 bs=1M count=100
```

For me it caused issues with the zfs script: https://github.com/nix-community/disko/blob/276a0d055a720691912c6a34abb724e395c8e38a/lib/types/zpool.nix#L81

Note that I was not able to replicate it on oracle VM. It was only happening on a real machine.

**Comment by Mic92** [comment]
We should switch to `zpool labelclear -f` instead.

**Comment by ghostbuster91** [comment]
fyi: I was able to get rid of the offensive signature by calling `wipefs -a` for each partition separately. Before I was calling it only on the disk itself (e.g. `/dev/sda`)

**Comment by Mic92** [comment]
I thought we were already doing this: https://github.com/nix-community/disko/blob/4e719b38fa7c85f4f65d0308ca7084c91e7bdd6d/disk-deactivate/disk-deactivate.jq#L39

But I also heard from other sources that wipefs itself won't pick up all zfs signatures: https://github.com/util-linux/util-linux/issues/1228

**Comment by ghostbuster91** [comment]
I didn't use `disko-deactivate` script, only the `disko-format` as I no longer had access to the old disko config.

**Comment by Mic92** [comment]
disko-deactivate is used in disko format. It uses the new configuration to wipe disks rather than the old one.

**Comment by ghostbuster91** [comment]
So, it makes sense that it didn't work as it didn't iterate over all old parts. 
Shall we add into disko repository a guideline on how to manually clear signatures etc?

**Comment by Mic92** [comment]
I believe this was fixed in https://github.com/nix-community/disko/pull/757
let me know if it still persist.
