### ISSUE TITLE
grub on mbr with zfs: unkown filesystem

### ISSUE THREAD

**Issue by ghostbuster91** [nix-community/disko#735]
I have migrated my disko configuration from the legacy table into a gpt one following the [migration guide](https://github.com/nix-community/disko/blob/master/docs/table-to-gpt.md)

Here is a PR from migration: https://github.com/ghostbuster91/nixos-server/pull/7/files#diff-3b8cce8266b6ce43b4f9ca48abfdf2cd6570adb44bef43d1a9ce3b3723b6e621R1

The installation passes but after the reboot grub is unable to recognized filesystem:
```
GRUB loading.
Welcome to GRUB!

error: unknown filesystem.
Entering rescue mode...
grub rescue> _
```

Changing the filesystem to something else like `ext4` fixes the issue. (That is how I ran into #734 )

**Comment by Mic92** [comment]
I would suggest to use a boot partition with a kernel/initrd. I don't think there is anyone really maintaining the zfs support in grub properly. Many features are missing.

**Comment by Mic92** [comment]
Apparently there is also this option `zpool create -o compatibility=grub2`, which you have to use.

**Comment by ghostbuster91** [comment]
> I would suggest to use a boot partition with a kernel/initrd. 

You mean something like below? 

```nix
       content = {
          type = "gpt";
          partitions = {
            grub = {
              size = "1M";
              type = "EF02";
              priority = 1;
            };
            boot = {
              size = "512M";
              content = {
                type = "filesystem";
                format = "vfat";
                mountpoint = "/boot";
              };
              priority = 2;
            };
            root = {
              size = "100%";
              content = {
                type = "zfs";
                pool = "rpool1";
              };
              priority = 4;
            };
          };
        };
```

With only this change the grub was able to launch but it hung while trying to load the kernel:
![image](https://github.com/user-attachments/assets/05fa2a0f-30dd-4190-9edd-93756588e877)

I wanted to try with the `compatibility` option set but I am constantly running now into another issue:
`mkfs vfat /dev/disk/by-partlabel/disk-sda-root` - cannot open `/dev/disk/by-partlabel/disk-sda-root`
same happens with other commands like `mkswap` or `mkfs` for boot partition. 
Sometimes the script gets to `zpool create` and then fails with the same error. 

Not sure what is the cause of it...

**Comment by ghostbuster91** [comment]
Alright, I was finally able to complete the installation after couple of retries (I removed the swap partition which minimized the amount of points where the failure can occur and changed the size of root partition to a fixed value). 

The separate `/boot` partition together with `zpool create -o compatibility=grub2` worked :) 

Still, it would be great to fix the issue with `cannot open /dev/disk/by-partlabel/disk-sda-root`

**Comment by ghostbuster91** [comment]
After some thinking I realized that I am not sure if zfs + grub has ever been working for me before, so I can't say if there is any regression. Also it doesn't seem like based on what was shared. It is just a limitation of these two (grub and zfs) when combined. 

Given that I was able to successfully boot the system I am going to close it and open a new issue for the `cannot open` error.
