### ISSUE TITLE
Add a `--version` command

### ISSUE THREAD

**Issue by iFreilicht** [nix-community/disko#745]
Right now, it's impossible to see which version of disko I'm running. Nixpkgs shows it:

![Screenshot 2024-08-22 at 17 33 05](https://github.com/user-attachments/assets/cb65675c-aa53-45e8-b241-3223f12556de)

but I can't verify whether I'm running the latest release:

```
$ disko --version
aborted: disko config must be an existing file or flake must be set
$ which disko
/nix/store/ply01w0y86dipp2n2ysfi7cs2xgj4pvw-disko/bin/disko
```

The only way to know is to check out the commit of nixpkgs I have installed and look at the code of `pkgs/by-name/di/disko/package.nix`.

It would be nicer if there was a `--version` command. Not sure how this could best be implemented, though.

**Comment by Mic92** [comment]
I would make a .version file that the version is read from and a release script that would bump this version as well as tagging the commit.

Here is release script that I took inspiration from in the past: https://github.com/nix-community/harmonia/blob/master/scripts/create-release.sh

**Comment by Enzime** [comment]
Seems like GitHub glitched out and closed this prematurely
