### ISSUE TITLE
incompatibility with srvos.nixosModules.hardware-hetzner-cloud

### ISSUE THREAD

**Issue by sedlund** [nix-community/disko#748]
disko adds the device in my disko config to `boot.loader.grub.devices` - `/dev/sda`

this is a single disk hetzner vm.

when including `srvos.nixosModules.hardware-hetzner-cloud` it also adds the default device name for hetzner to `boot.loader.grub.device`

https://github.com/nix-community/srvos/blob/9810f43ff22a10b6f70c38d6085ac6c201b26640/nixos/hardware/hetzner-cloud/default.nix#L16

this causes `boot.loader.grub.devices` to have `/dev/sda` twice in the list, causing this error on eval:

```
        Failed assertions:
       - You cannot have duplicated devices in mirroredBoots
```

```
nix-repl> nixosConfigurations.hetz.config.boot.loader.grub.device
"/dev/sda"

nix-repl> nixosConfigurations.hetz.config.boot.loader.grub.devices
[ "/dev/sda" "/dev/sda" ]

nix-repl> :p nixosConfigurations.hetz.config.boot.loader.grub.mirroredBoots
[ { devices = [ "/dev/sda" "/dev/sda" ]; efiBootloaderId = null; efiSysMountPoint = "/boot"; path = "/boot"; } ]
```

To fix I have to:

> boot.loader.grub.devices = lib.mkForce ["/dev/sda"];

**Comment by Mic92** [comment]
Indeed. We should detect if disko is used in srvos.

**Comment by Mic92** [comment]
cc @zimbatm

**Comment by Mic92** [comment]
nix-repl> nixosConfigurations.turingmachine.config.disko.devices != []
true

**Comment by Mic92** [comment]
nix-repl> nixosConfigurations.turingmachine.options ? disko
true

**Comment by Mic92** [comment]
@sedlund please try https://github.com/nix-community/srvos/pull/491

**Comment by sedlund** [comment]
@Mic92 Tests good for me.  Thanks!
