### ISSUE TITLE
Quickstart clarification around hybrid-partition

### ISSUE THREAD

**Issue by devinrsmith** [nix-community/disko#753]
Hi, I followed the [Quickstart Guide](https://github.com/nix-community/disko/blob/master/docs/quickstart.md) along with minimal modifications to [example/boot-raid1.nix](https://github.com/nix-community/disko/blob/master/example/boot-raid1.nix).

When I ran the `nixos-install` command, I saw the following logs near the end:

```
...
Initializing machine ID from random generator.
File system "/dev/md127" is not located on a partitioned block device.
Traceback (most recent call last):
  File "/nix/store/9xx6apil1zzf0hqpif2zy6ysbldj7vk8-27nxgnrgasg7kcaqwsclrx0p6gyc8sj1-systemd-boot", line 397, in <module>
    main()
  File "/nix/store/9xx6apil1zzf0hqpif2zy6ysbldj7vk8-27nxgnrgasg7kcaqwsclrx0p6gyc8sj1-systemd-boot", line 380, in main
    install_bootloader(args)
  File "/nix/store/9xx6apil1zzf0hqpif2zy6ysbldj7vk8-27nxgnrgasg7kcaqwsclrx0p6gyc8sj1-systemd-boot", line 295, in install_bootloader
    subprocess.check_call([f"{SYSTEMD}/bin/bootctl", f"--esp-path={EFI_SYS_MOUNT_POINT}"] + bootctl_flags + ["install"])
  File "/nix/store/5w07wfs288qpmnvjywk24f3ak5k1np7r-python3-3.11.9/lib/python3.11/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/nix/store/ws3nzqfc8dhbibi9vb57zwvj6nlaky0p-systemd-255.9/bin/bootctl', '--esp-path=/boot', 'install']' returned non-zero exit status 1.
...
```

This seemed concerning, but furthermore, it seemed like the `nixos-install` command actually _succeeded_ (potentially an issue to raise with NixOS?).

I figured it would be best to _not_ restart and to see if something was wrong in the configuration. After re-reading and trying some different things, I tried to apply step 7e "If you chose the hybrid-partition scheme" and that seemed to work, ie switching to `boot.loader.grub.enable = true`.

I was originally under the impression the hybrid-partition scheme only applied to [example/hybrid.nix](https://github.com/nix-community/disko/blob/master/example/hybrid.nix) (and the others that start with "hybrid-"), but it seems like this is targeted at any configuration that has boot type EF02 and ESP type EF00 partitions? If so, it might be good to either prefix all such nix files with "hybrid" and/or to specifically add a comment in each relevant example files with some sort of comment describing "hybrid-partitioning". I think it would also be good to better define hybrid-partition scheme in the quickstart to help others avoid this potential mistake.

Tangent: is there a way to use systemd-boot with mdadm boot?

**Comment by Mic92** [comment]
If you boot from an EFI system, I would recommend not to use raid for your /boot. I have seen this breaking depending on the EFI firmware. With grub you can use `mirroredBoots` as commented out here: https://github.com/Mic92/dotfiles/blob/8fe93df19d47c8051e569a3a72d72aa6fbf66269/nixos/eve/modules/disko.nix#L35
With systemd-boot the same approach would also be possible. However it's not implemented in nixos's bootloader install script.

**Comment by Mic92** [comment]
The idea here is to have two identical ESP boot partition and have the bootloader in a standard place that is looked up by the EFI firmware. If one disk fails, the firmware should still be able to find the other disk.

**Comment by Mic92** [comment]
systemd-boot doesn't allow you to install the bootloader on such devices.
