### ISSUE TITLE
documentation/help: unclear how to use disko in a flake-based setup "idiomatically"

### ISSUE THREAD

**Issue by ppenguin** [nix-community/disko#77]
I've been struggling to use `disko` in the way I *thought* it was intended to be used, since the documentation is a bit "silo'd".

So how I thought it would go (after much *trial&horror*):

1. on install target (`myserver`):
   - boot a live-USB image (in my case a headless server)
   - `lsblk`
2. on dev machine:
   - make `disko.nix` with partitions in it acc. to `lsblk` output
   - define minimal `configuration.nix` acc. to example with `create` and `mount` scripts
   - define a flake which realises from above and `disko` and `nixpkgs` an output, e.g. `myserver-partitioning`
   - `ssh -A <nixos-live-session>`
3. on `myserver`:
   - `nixos-rebuild build --flake  "gitblabla:/me/mysysflake#myserver-partitioning"`
   - `result/sw/bin/disko-create` (observe how partitions and file systems are created)
   - do some minimal mounts (`/` and `/boot` (?)) into `/mnt`
   - generate `hardware-configuration.nix`
4. on dev machine:
   - copy `hardware-configuration.nix` from `myserver`
   - make final system flake, referring to same `disko.nix` (for `fileSystems`), with output `nixosConfigurations.myserver`
5. on `myserver`:
   - `nixos-install --root /mnt --flake "gitblabla:/me/mysysflake#myserver"`

Something like this (still ongoing with the last step, and step (3) didn't actually go like that: I had to clone the repo into the live session and mess with it locally.)

:question:  Is this at all something like the intended usage scenario? And if not, how to achieve the "fresh install from flake" case then?

It is a bit unfortunate that the example has `tsp-create` instead of `disko-create` and it is entirely unclear how you're supposed to get the create script in the easiest way. 
And it stops working as soon as you actually do "the right thing" (?) and define the partitions in `disko.nix` that is imported via the `module` system (i.e. `imports = [ ./disko.nix ]`), because then the attribute set for `config.disko.devices` is assigned during "normal" config merging.
Wat worked for me in this case is write the scripts like so (i.e. in the "minimal" `configuration.nix`:
```nix
{
	environment.systemPackages = with pkgs; [
		(pkgs.writeScriptBin "disko-create" (config.system.build.formatScript))
		(pkgs.writeScriptBin "disko-mount" (config.system.build.mountScript))
	];
}
```

Also not clear from the example/README: how to refer to exactly what kind of `disko-config` when wanting to use the `cli`.

So summarising: it would be a great help to *untangle* the instructions for `cli`, `flake`, ... usage and to focus on the actual use case, which is *partitioning before install*.

**Comment by Mic92** [comment]
Here is an example flake: https://github.com/Lassulus/flakes-testing/blob/master/flake.nix

**Comment by Mic92** [comment]
This is the workflow is used in nixos-remote: https://github.com/numtide/nixos-remote/blob/f4235fead39ec6053eca4362008b4f626f9460f6/nixos-remote#L162

After using kexec it uses nix copy to upload and execute the script before doing the nixos install

**Comment by Mic92** [comment]
Any help to improve the documentation is appreciated.

**Comment by aidenscott2016** [comment]
@Mic92 what kind of help do you need? I would like to be learn how to use this module so maybe I can contribute a few paragraphs once I understand it a bit better

Maybe you could start by stating how you expect a typical desktop user to use this. I have made a couple of successful installs using disko through a few methods learned from reading various issues here. I imagined that given a valid `hardware-config.nix` and `disko.nix` running `sudo nix-install --flake .#hostname` would "just work" and go ahead and create and mount the partitions I want. Is that supported?

**Comment by jackinloadup** [comment]
@aidenscott2016 disko, as I understand, does not yet perform any tasks while `nixos-install` is run. Disko exposes two scripts, `disko-create` and `disko-mount`,  which need to be run before installing to prep the storage medium and place it where the installer is expecting. 

You can see how I have used disko recently [in this thread](https://github.com/nix-community/disko/pull/95#issuecomment-1396358647). There are likely many other valid usage strategies that can be used or could be explored.

**Comment by ppenguin** [comment]
@Mic92 Thanks for the info (sorry for the belated reply, I kinda lost track, but am now actually deploying the next vps...)
I'm a bit under time pressure, but if/when I get some clean epiphany I'll consider if I can contribute to the docs as well...

**Comment by aidenscott2016** [comment]
thank you @jackinloadup that's really helpful. I did manage to get it working for myself in the end after piecing together information from various issues. I hope to have some time in the next few days which I hope I can use to put some more words on the README at least

**Comment by Mic92** [comment]
@aidenscott2016 Thanks. I am currently in the process of also documenting nixos-remote.
We hired also a technical writer to work on disko, but it would be great if you could put your text in some form in writing and than we can give it to them to improve (the technical writer is not an expert on nix/nixos).

**Comment by ppenguin** [comment]
> ..., but I am also in the process to document this project https://github.com/numtide/nixos-remote/

Small update: I did the last VPS deployment with my multi-host-flake and an adoption of `nixos-remote` which has `kexec` functionality removed, since I didn't want to risk failure because I have less than 2GB RAM (and I had a nixos live-CD already booted in the VPS). I quickly dumped the adaptation [here](https://gist.github.com/ppenguin/78e017b2410a9fee955e60f9eb9f3394)

It worked like a charm.

I'm now doing pretty much all my server updates from my dev host with 

```
NIX_SSHOPTS=-t nixos-rebuild switch --target-host $tgthost --use-remote-sudo --flake .#tgthost
```

while refining and committing the config

**Comment by Mic92** [comment]
You can actually already use `nixos-remote` with the normal nixos unstable installer. If `nixos-remote` sees `VARIANT=installer` in `/etc/os-release` than it will not try to kexec again.

**Comment by Mic92** [comment]
@aidenscott2016 I started to draft out an installation tutorial. If you want to take a look: https://pad.lassul.us/MHuZ0A65Ru2cXoFNexsnTw#
Just feel free to edit (i.e. by adding a flake based workflow)

**Comment by Lassulus** [comment]
> @Mic92
> 
> > Note that Disko will **remove** existing partitions!
> 
> Does that mean one needs to delete the import to Disko once the installation is over? I assumed Disko was declarative…

Only if you run the zap_creatE_mount script or the create script. you have to explicitly execute those. it doesn't automatically run on nixos-rebuild

**Comment by filipdutescu** [comment]
was looking for examples to do precisely this and besides the linked resources, I see there is - at the time of this comment - a section in the [docs](https://github.com/nix-community/disko/blob/master/docs/HowTo.md#installing-nixos-module) going over a Flake setup. is the presented example not an idiomatic way to use disko with flakes? i am a bit confused since it is marked as recommended - again, at the time of the comment.

**Comment by Mic92** [comment]
The documentation wasn't there at the time this comment was made I think.

**Comment by ppenguin** [comment]
> The documentation wasn't there at the time this comment was made I think.

Thanks! Sorry for forgetting about this and keeping it open. Yes, the docs are much better now, thanks for the great project. It's especially nice to use e.g. for quick provisioning of similar VPS!

**Comment by aidenscott2016** [comment]
@Mic92 my bad I didn't see this reply until just now
