### ISSUE TITLE
Feature Request: Add confirmation option for each disk when running script

### ISSUE THREAD

**Issue by adam248** [nix-community/disko#772]
When running `disko` could you add an option flag like `--confirm` or something like that. (Or just make it the default behaviour and add `--yes` flag to auto-confirm all.

This feature will pause the script before each device and ask the user to confirm that they wish to format that disk (sda or sdb etc...).

`Do you wish to wipe, partition, format and mount "/dev/sda"? [ Yes / no (skip) / abort ]`  

also `y` `n` or `a` are shortcuts to each option and Yes is the default (if you just press enter).

This will be nicer than running `--dry-run` then reviewing the final script each time.

Or you could allow a way to only do one disk from the disko-config.nix? but that seems like it would require interactive mode or something.

Thanks

**Comment by iFreilicht** [comment]
I think both options are reasonable. The first is somewhat similar to #725, but more granular.

**Comment by adam248** [comment]
> I think both options are reasonable. The first is somewhat similar to #725, but more granular.

sorry, i didn't see that one. I will close this issue and use #725 to continue the conversion.
