### ISSUE TITLE
disko-images documentation error

### ISSUE THREAD

**Issue by ForgottenBeast** [nix-community/disko#773]
Hi,
When going through the documentation to create disko images there is an error.

# Steps to reproduce:

- copy the flake.nix from https://github.com/nix-community/disko/blob/master/docs/disko-images.md to a new, empty folder
- copy simple-efi.nxi
- run the provided command `nix build .#nixosConfigurations.myhost.config.system.build.diskoImagesScript`

# system used to reproduce
- Nixos 24.05

# result

       error:
       … while calling the 'head' builtin

         at /nix/store/l3amk5lsakpc93him5kry24kax23sn4h-source/lib/attrsets.nix:1575:11:

         1574|         || pred here (elemAt values 1) (head values) then
         1575|           head values
             |           ^
         1576|         else

       … while evaluating the attribute 'optionalValue.value'

         at /nix/store/l3amk5lsakpc93him5kry24kax23sn4h-source/lib/modules.nix:868:5:

          867|
          868|     optionalValue =
             |     ^
          869|       if isDefined then { value = mergedValue; }

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: value is null while a set was expected

**Comment by Enzime** [comment]
The line:

```
disko.devices.disk.vdb.imageSize = "10G";
```

should actually be:

```
disko.devices.disk.main.imageSize = "10G";
```
