### ISSUE TITLE
`disko-install --flake .#whatever` fails if path to `.` contains spaces

### ISSUE THREAD

**Issue by Jayman2000** [nix-community/disko#780]
Steps to reproduce:

1. Clone the example repo that I created, and make sure that the path to the clone contains at least one space:

    ```bash
    git clone https://gist.github.com/Jayman2000/2de2928816084f9803da262a93ab3aef 'path that contains spaces'
    ```

2. Change directory into your newly created clone:

    ```bash
    cd 'path that contains spaces'
    ```

3. Plug a spare flash drive into your computer.

4. Try to install the repo’s NixOS configuration onto the USB drive:

    ```bash
    sudo disko-install --flake '.#default' --disk main <path-to-usb-drive>
    ```

After you follow those steps to reproduce, you’ll get this error:

<pre><samp>error:
       … while calling the 'getFlake' builtin

         at /nix/store/hg8bn6w53yfd0hpar0va6mh00flfixzx-disko/share/disko/install-cli.nix:10:21:

            9| let
           10|   originalSystem = (builtins.getFlake "${flake}").nixosConfigurations."${flakeAttr}";
             |                     ^
           11|   lib = originalSystem.pkgs.lib;

       error: '/home/jayman/Documents/path that contains spaces' is not a valid URL</samp></pre>

**Comment by Mic92** [comment]
This is an issue with nix 2.18:

```
nix-shell-env % nix-shell -p nixVersions.nix_2_18

[nix-shell:/tmp/vigorous-williamson-Xnqaug/foo bar]$ nix eval --expr 'builtins.getFlake "/tmp/vigorous-williamson-Xnqaug/foo bar"'
warning: unknown experimental feature 'configurable-impure-env'
error:
       … while calling the 'getFlake' builtin

         at «string»:1:1:

            1| builtins.getFlake "/tmp/vigorous-williamson-Xnqaug/foo bar"
             | ^

       error: '/tmp/vigorous-williamson-Xnqaug/foo bar' is not a valid URL
```

Works in nix 2.24:

```
/tmp/vigorous-williamson-Xnqaug/foo bar 50s
nix-shell-env % nix-shell -p nixVersions.nix_2_24

[nix-shell:/tmp/vigorous-williamson-Xnqaug/foo bar]$ nix eval --impure --expr '(builtins.getFlake "/tmp/vigorous-williamson-Xnqaug/foo bar").sourceInfo'
{ lastModified = 1726728008; lastModifiedDate = "20240919064008"; narHash = "sha256-r+Pk1HmklfuwgGiv7jV5RlO5Ym7+YkwFAjcBrHCKGSo="; outPath = "/nix/store/h1m5mjrsspzashm494shxqsx0hpli41a-source"; }
```
