### ISSUE TITLE
Remove AI generated logo

### ISSUE THREAD

**Issue by themg95** [nix-community/disko#781]
The nix community shouldn't stand for AI generated images. Instead a real artist should be commissioned.

**Comment by Mic92** [comment]
Should we let Lassulus draw a picture? https://lassul.us/art.html

**Comment by Lassulus** [comment]
here a first draft: 
![disko](https://github.com/user-attachments/assets/0eb21a5d-ce08-4760-bfd1-c7b71157ddae)

**Comment by geoffreygarrett** [comment]
Just got into the nix space recently. Literally did a double take a moment ago thinking I saved the wrong repository :sweat_smile:

**Comment by shipurjan** [comment]
it's glorious

**Comment by TheMultii** [comment]
<3

**Comment by iFreilicht** [comment]
Thank you for all the love, I'm very happy with the new logo as well. I'll be closing the discussion now as these comments ping maintainers needlessly. Feel free to open a disko logo appreciation thread on Discourse if you want to express your feelings regarding this change :)
