### ISSUE TITLE
[Example] encrypted btrfs raid1

### ISSUE THREAD

**Issue by Sk7Str1pe** [nix-community/disko#799]
```nix
{
  disko.devices = {
    disk = {
      disk0 = {
        type = "disk";
	device = "/dev/sdb";
	content = {
	  type = "gpt";
	  partitions = {
	    crypted2 = {
	      name = "crypt_raidp2";
	      size = "100%";
	      content = {
                type = "luks";
		name = "raidp2"; # this is DM name
	      };
	    };
	  };
	};
      };
      disk1 = {
        type = "disk";
        device = "/dev/sda";
        content = {
          type = "gpt";
          partitions = {
            crypted1 = {
              size = "100%";
	      name = "crypt_raidp1";
              content = {
                type = "luks";
		name = "raidp1";
		content = {
		  type = "btrfs";
		  extraArgs = [ "-f" "-m raid1 -d raid1" "/dev/mapper/raidp2"]; # raidp2 - DM name of 2nd disk
                  subvolumes = {
		    "/" = {
                      mountpoint = "/mnt/SoftWare";
		      mountOptions = [
		        "rw" "relatime" "ssd" "discard=async" "space_cache=v2" "subvolid=5" "subvol=/"
		      ];
		    };
		  };
		};
	      };
	    };
          };
        };
      };
    };
  };
}
```

**Comment by Sk7Str1pe** [comment]
Couldn't open pull request so opened here

**Comment by iFreilicht** [comment]
Have you tested this example? Can you boot from it?

**Comment by Sk7Str1pe** [comment]
I didn't tried to boot from it, I don't use this setup for main system, but yes I managed to get working raid and it seems to be possible to boot with this (if possible to determine 2 LUKS devices in kernel cmdline)

**Comment by Sk7Str1pe** [comment]
> Can you boot from it?

Yes I tested in VM and it's bootable

**Comment by Sk7Str1pe** [comment]
@Lassulus new example, already tested on bare metal. Can be booted.

**Comment by iFreilicht** [comment]
Dude, chill. We'll get to it. If you want this to be merged quickly, make a PR and add a test for it. If you can't or don't want to do that, expect a change like this to take a little while.

**Comment by Sk7Str1pe** [comment]
I can't get how to become a collaborator

**Comment by iFreilicht** [comment]
You have to fork the repository first, see [Fork a respository](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/fork-a-repo#forking-a-repository)
Then, you clone your fork as described in the link above, make the changes you want, and push them.
When you then go back to your fork in the browser, you can open a pull request (see [Creating a Pull Request from a Fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork)).

Once your PR is accepted and merged, the badge "Collaborator" will appear next to your username in discussions. Hope this helps!

**Comment by Sk7Str1pe** [comment]
Yay it helps, thx a lot!
