### ISSUE TITLE
`lvm_vg.lvs` should be ordered

### ISSUE THREAD

**Issue by nurelin** [nix-community/disko#80]
Since `lvcreate` can use remaining free space as percentage, the attribute set of logical volumes should be ordered.

For example, I might want to create a 8GB swap lv and then use the remaining space for my root partition. But if I name my lvs `swap` and `root` then the root partition is created first.

To do this, we could either:

1.  Keep using the alphabetical order of attributes name in `lvs`, just name then differently. Nothing has to be done but it feels weird.
2. Add a order attribute and sort the list before dumping in scripts.
3. Replace the `lvs` Attribute Set with a List.

What do you think ?

**Comment by Lassulus** [comment]
Lists are bad when merging or overriding (already thought about replacing all lists with attrsets). So I guess we add a priority to things where order matters and create them then from highest to lowest priority?
