### ISSUE TITLE
Documentation for the disko configuration format

### ISSUE THREAD

**Issue by s-cerevisiae** [nix-community/disko#817]
Currently for a user to learn and use disko, they have to look through various examples of different setups, since there's no central documentation of the format.
And for something as complex as filesystem setup, this is often not enough for users to infer where can each option be set, what they mean and how to customize them. A quick glance shows that tens of issues are directly related to the configuration being written wrong or misunderstood.

To improve user friendliness and reduce the effort of explaining the format, would you like to create a specification document for the configuration format?

**Comment by s-cerevisiae** [comment]
Just found that it is explained here: https://github.com/nix-community/disko/blob/master/docs/reference.md

**Comment by iFreilicht** [comment]
It would be nice if we could fix this issue. I'm wondering how option documentation is usually generated, I haven't looked into that yet.

**Comment by almereyda** [comment]
> I'm wondering how option documentation is usually generated, I haven't looked into that yet.

It was possible to come up with these examples.

<details><summary>nix-options-doc, mmdoc, Nix Reference Manual</summary>
<p>

- [Thunderbottom/nix-options-doc: Generate multi-format documentation for NixOS module options](https://github.com/Thunderbottom/nix-options-doc?tab=readme-ov-file)
  - [flakes/options.md at main · Thunderbottom/flakes](https://github.com/Thunderbottom/flakes/blob/main/options.md)
- [ryantm/mmdoc: Minimal Markdown Documentation](https://github.com/ryantm/mmdoc)
  - [Introduction | mmdoc](https://ryantm.github.io/mmdoc/)
- [nix/doc/manual/meson.build at 5ae1b5f88b44a14a602b2ac2c4ba6ebf00559b05 · NixOS/nix](https://github.com/NixOS/nix/blob/5ae1b5f88b44a14a602b2ac2c4ba6ebf00559b05/doc/manual/meson.build#L65)
  - [nix-build - Nix 2.30.3 Reference Manual](https://nix.dev/manual/nix/2.30/command-ref/nix-build.html)

</p>
</details> 

While `mmdoc` looks opinionated, a less sophisticated approach is followed by `nmd`, in use at `home-manager` and `skarabox`, for example.

- [nmd: A basic documentation framework for Nixpkgs modules](https://sr.ht/~rycee/nmd/)
  - [\~rycee/nmd - A basic documentation framework for Nixpkgs modules - sourcehut git](https://git.sr.ht/~rycee/nmd)
- [Robert Helgesson / nmd · GitLab](https://gitlab.com/rycee/nmd/)

<details><summary>Examples</summary>
<p>

- [rycee's NUR manual](https://rycee.net/nur-expressions/)
- [Skarabox Manual](https://installer.skarabox.com/)
  - [Appendix A. All Options](https://installer.skarabox.com/options.html)
- Skarabox [Self Host Blocks Manual](https://shb.skarabox.com/)
- [Home Manager Manual](https://nix-community.github.io/home-manager/)
  - [Appendix A. Home Manager Configuration Options](https://nix-community.github.io/home-manager/options.xhtml)
  - [Appendix B. NixOS Configuration Options](https://nix-community.github.io/home-manager/nixos-options.xhtml)
  - [Appendix C. nix-darwin Configuration Options](https://nix-community.github.io/home-manager/nix-darwin-options.xhtml)

</p>
</details> 

Skarabox shows us a medium-scale build infrastructure, which is less complex in comparison to `home-manager`.

- [skarabox/template/README.md at main · ibizaman/skarabox](https://github.com/ibizaman/skarabox/blob/main/template/README.md)
  - [skarabox/.github/workflows/pages.yml at 7470c94f01392a208ebffc8cefdf50602b3eff64 · ibizaman/skarabox](https://github.com/ibizaman/skarabox/blob/7470c94f01392a208ebffc8cefdf50602b3eff64/.github/workflows/pages.yml#L43-L49)
    - [flake.lock: Update · ibizaman/skarabox@7470c94](https://github.com/ibizaman/skarabox/actions/runs/17480763688/job/49650582992#step:5:163)
- [skarabox/docs/normal-operations.md at main · ibizaman/skarabox](https://github.com/ibizaman/skarabox/blob/main/docs/normal-operations.md)
  - [skarabox/flake.nix at 7470c94f01392a208ebffc8cefdf50602b3eff64 · ibizaman/skarabox](https://github.com/ibizaman/skarabox/blob/7470c94f01392a208ebffc8cefdf50602b3eff64/flake.nix#L75-L93)
- [skarabox/docs/default.nix at main · ibizaman/skarabox](https://github.com/ibizaman/skarabox/blob/main/docs/default.nix#L1)
  - [render documentation without deprecated optionsDocBook by considerate · Pull Request #4673 · nix-community/home-manager](https://github.com/nix-community/home-manager/pull/4673/files)

Unfortunately I wasn't able to discern where `nixos-render-docs` in `skarabox/docs/default.nix` comes from nor what it does.

- https://github.com/ibizaman/skarabox/blob/7470c94f01392a208ebffc8cefdf50602b3eff64/docs/default.nix#L9
- https://github.com/ibizaman/skarabox/blob/7470c94f01392a208ebffc8cefdf50602b3eff64/docs/default.nix#L157-L168

If anybody could enlighten me about that, please do.

There's another example for mdBook at `quadlet-nix`. [¹](https://github.com/SEIAROTg/quadlet-nix/tree/main/docs) [²](https://seiarotg.github.io/quadlet-nix/nixos-options.html)

**Comment by ibizaman** [comment]
@almereyda looking back at the code I was confused too but it's simply a [package](https://search.nixos.org/packages?query=nixos-render-docs). In my Skarabox project, a lot is hardcoded. I recently refactored my other project SelfHostBlocks (both use the same underlying code to generate the documentation) to be [more generic](https://github.com/ibizaman/selfhostblocks/blob/main/docs/default.nix#L130-L146). And [it's usage](https://github.com/ibizaman/selfhostblocks/blob/main/flake.nix#L119-L151).

I'd love to split this out in its own repo if you find it useful. It could even be a project in nix-community?

**Comment by almereyda** [comment]
I see the `nmd`/`nixos-render-docs` output clearly as the most simple, straightforward way to produce Nix documentation that I've seen. If that'd be available easily as a reference way of doing (a first take at) Nix module/flake documentation (without search, navigation, …), the better.

**Comment by Malix-Labs** [comment]
One more way is to make it be searchable in https://search.nixos.org (I already opened a PR including it here : NixOS/nixos-search#1052)

There is also https://github.com/water-sucks/optnix, https://github.com/NuschtOS/search and the native [`pkgs.nixosOptionsDoc`](https://github.com/NixOS/nixpkgs/blob/7986d9bfc0f7ea87b50f7c47368275eca6d8cae8/pkgs/top-level/all-packages.nix#L10856-L10864)

The Nix ecosystem has well transitionned out of DocBook XML now

But anyway, starting using any would be better than staying a few more years without a proper comprehensive options reference
