### ISSUE TITLE
Incorrect ZFS command when making zpool(?)

### ISSUE THREAD

**Issue by vennsofar** [nix-community/disko#820]
Hi all, it seems that Disko calls a non-existent command when trying to create a ZPool. It tries to call `mkfs.zfs` which does not exist, instead of something like `zpool create`

Originally I tried to use disko with [this config,](https://raw.githubusercontent.com/vennsofar/nix-one-liner/refs/heads/main/disko-config.nix) and after applying fixes from #765 it does create all the partitions successfully, up to creating the partition where ZFS would occupy, but fails to actually create any ZPool or datasets, but gives no mention of the aforementioned `mkfs.zfs` command (at least within visible terminal history.)

![image](https://github.com/user-attachments/assets/d6aa14cc-4d09-446a-bd9c-51547ce9fa40)

I then tried to use [a modified version of a ZFS template config](https://raw.githubusercontent.com/vennsofar/nix-one-liner/refs/heads/main/zfs-over-legacy.nix) but had no luck with that either, but this config *does* mention the `mkfs.zfs` command, and that it does not exist.

![image](https://github.com/user-attachments/assets/064d7e87-1b95-450b-849d-664ff9bd3b82)

Please note that I ran `sudo wipefs -fa /dev/sda` between using each config file to make sure that they didn't interfere with each other.

**Comment by Enzime** [comment]
Can you post your disko configuration?

**Comment by iFreilicht** [comment]
@Enzime they linked the two configs they tried.

The second config is invalid, because you're using the filesystem type instead of the zfs type:

```nix
primary = {
  size = "100%";
  content = {
    type = "filesystem";
    format = "zfs";
  };
};
```

`filesystem` is a generic type that always uses `mkfs.${format}`. Your first config is correct:

```nix
primary = {
  size = "100%";
  content = {
    type = "zfs";
    pool = "sys";
  };
};
```

And as you correctly observe, it doesn't call the non-existing `mkfs.zfs` command. The question now is, does it even fail at all?

Your config looks correct, and I don't see any errors in the screenshots you posted. If you use `legacy` mountpoints, the datasets will not be mounted by default, you have to do it manually.

What do you see when running `lsblk --fs` after running the first config? 

Also, you should be able to scroll up with the PgUp and PgDown keys.

**Comment by vennsofar** [comment]
It doesn't fail in the sense that the program crashes/errors out, but fails in the sense that there is no sign of anything related to ZFS on the entire drive.
There are no ZPools, datasets, anything at all. 
`lsblk --fs` returns the following:
![image](https://github.com/user-attachments/assets/037fbf86-858d-4356-994b-db5510279be5)
`sudo zpool status`  & `zfs list` returns this:
![image](https://github.com/user-attachments/assets/271a70d9-c5a8-4726-9313-82244900749b)

Aside, but PgUp and PgDown don't scroll for me, they only move in my bash history.
Thank you for the clarification between the `type = "zfs"` and `type = "filesystem"`, though I find it strange that the template taken from this repo is incorrect. Is there a reason for that? Like I mentioned, the second config file was only slightly edited, only removing the second disk which isn't present in my system. Did I miss something?

**Comment by iFreilicht** [comment]
> I find it strange that the template taken from this repo is incorrect.

Where did you find it, exactly? Searching the entire repo for `format ?= ?"zfs"` yields zero results, and all templates we have are tested in VMs by CI on every PR.

---

Ahhhhh haha I figured it out!. Shortened, you config looks like this:

```
{
  disko.devices.disk = {
    main = {
      ...
    };
  };
  zpool = {
    sys = {
      ...
    };
  };
}
```

So you're defining the `disko.devices.disk` and `zpool` options. But you need to define `disko.devices.zpool`. You can either just change the name like this:


```
{
  disko.devices.disk = {
    main = {
      ...
    };
  };
  disko.devices.zpool = {
    sys = {
      ...
    };
  };
}
```

Or nest everything under `disko.devices`:


```
{
  disko.devices = {
    disk = {
      main = {
        ...
      };
    };
    zpool = {
      sys = {
        ...
      };
    };
  };
}
```

**Comment by vennsofar** [comment]
I pulled the example config from https://github.com/nix-community/disko/blob/master/example, which is found under the Overview Section of the README (See below.) 
![image](https://github.com/user-attachments/assets/6088e0c9-8ff4-402d-9038-bf2de937ee8d)

I see, and this does seem to be the case. Adding `disko.devices` to the `zpool` does create the ZPool and all attributes correctly (barring some misconfiguration on my end, it doesn't seem to inherit options like the normal `zfs create` unless I'm totally misreading.
![image](https://github.com/user-attachments/assets/481d6c1a-5849-4d73-ae7f-546e77ed9151)

Side note, is there a more effective method to mount ZFS datasets instead of the legacy format? Is the typical ZFS automount reliable on NixOS at all?

In any case my [updated config](https://github.com/vennsofar/nix-one-liner/blob/main/disko-config.nix) works as expected now, I appreciate the help.

**Comment by vennsofar** [comment]
Well I did some looking, and it turns out that I edited more than I remembered I did, including the `format = "zfs";` bit, so that's my fault.
Ill keep the options inheritance and the mounting stuff in mind, thanks for telling me.
I've done more testing and disko has been reliable since, so all is good here, thank you for the help.

**Comment by iFreilicht** [comment]
Great to hear!

**Comment by Lassulus** [comment]
we could throw an error if we encounter something like
```
  content = {
    type = "filesystem";
    format = "zfs";
  };
```
inside a config? and tell people to use the zfs/zpool types instead
