### ISSUE TITLE
Mergify creates unnecessary merge commits

### ISSUE THREAD

**Issue by iFreilicht** [nix-community/disko#825]
Mergify creates merge commits from master to the PR branch when running `@mergify queue`, which clogs up the history. It would be nicer if it would automatically do a rebase before merging. It can already do that when you run `@mergify rebase` first, but it should really be done automatically.

For an example, see #824

**Comment by Mic92** [comment]
Those should not end up in your git history if you set the merge method to `rebase` https://github.com/Mic92/dotfiles/blob/edafe60c36984ae4cbc43e2ebbfaf9e5aff8d7d2/.mergify.yml#L5

**Comment by Mic92** [comment]
Also the case here: https://github.com/nix-community/disko/commit/bdbdb725d632863bdedb80baabf21327614dd237#diff-a86ce5c61b08a10754303691ed57ad743d863957cb8692d5ec2fc4dc96700ac3R93

**Comment by iFreilicht** [comment]
Yeah, seems like that's not an issue then.
