### ISSUE TITLE
unattended install using disko-install 

### ISSUE THREAD

**Issue by cowboyai** [nix-community/disko#843]
we are working on an unattended installation...

https://github.com/thecowboyai/nixos-flashstor

I have most of this operational and booting fine.

Now i need to setup the zpool on the host drives.

The drive configurations are split so that the image written to the USB is separate from the HOST configuration.

If I try now to do:

sudo nix run 'github:nix-community/disko#disko-install' -- --write-efi-boot-entries --flake .#nixos-flashstor --disk sysboot /dev/sda

I get:

```bash
error: No device passed for disk 'nvme0n1'. Pass `--disk nvme0n1 /dev/name` via commandline
```

It wants to install the drives, but that's not when it should, it should do this on booting the system.

I assume I need to to this all in a systemd activationscript?

If so, how do I output the disko configuration to run?

This is all using Flakes so some of the operation samples from non-nixos systems could apply, but I'm not sure that is the best solution.

optimally, I just call disko from an activation script and if the drives are not set, set them, then mark them set.  I just need a single zpool in raidz2 for 12 matching drives, then MinIO takes over everything else.

This is also a decent example I'd like to add to the docs as I don't see anything like this...

This is basically a different workflow to make Appliances, not a desktop.

Any suggestions are appreciated, even: your doing this totally wrong...

**Comment by cowboyai** [comment]
I'm quite human and have been working with NixOS for quite some time.  I have talked directly with Numtide too.
ok, let be be more clear.

I have an appliance I need to configure.
To do so, I can boot it from USB.
I want to do that deterministically using nix.
so I set the system up, and it boots great from the usb.

now...

I need to configure the disks on the device...

If I do that, when I try to generate the USB, it wants me to also supply the NVMEs, which are on the device, not the installer.
and even then, I wouldn't want to be overwriting the nvme's on the installer when I am making a bootable live drive.

Sorry, I needed to update the main branch which is now done.

What I want to accomplish:
fully configure a destination system that has designated hardware to a live usb device.

I can obviously do this by booting a livecd and using nixos-anywhere and that may be a better option...

This option is to boot from USB, if it works fine, copy the image to eMMC then reboot from eMMC.

**Comment by cowboyai** [comment]
as I understand it...
I need to put ./modules/disko-nas.nix into configuration.nix, while disko-sysboot.nix stays in flake.nix, but I am having trouble figuring out just how to do that without getting infinite recursion.

**Comment by iFreilicht** [comment]
I see you updated the repo a bit after these comments, and you've done basically exactly what I would have suggested; create two separate `nixosConfigurations`, one with just the USB drive for the bootable barebones system, and one that imports the `disko-nas.nix` as an additional module and gets installed with `nixos-anywhere`.

Another option would have been to just run disko against the disko-nas.nix file directly, without the flake.

So is your issue solved now? If so, please close this issue :)

**Comment by cowboyai** [comment]
yes, it is in fact, necessary to do 2 stages, no matter what and nixos-anywhere does appear to solve it, though I get some odd kexec errors that I haven't figured out yet, but that is a nixos-anywhere issue, not disko.
