### ISSUE TITLE
Waiting 10 seconds for key file /tmp/secret.key to appear

### ISSUE THREAD

**Issue by codehia** [nix-community/disko#845]
I am trying to use luks-btrfs-subvolumes with disko-install to install nixos but keep running into the issue in the Question. 

I'm new to nixos so would appreciate any help on possible issues and how to debug this issue.

**Comment by iFreilicht** [comment]
The comment in the example you're using explains what to do:

> disable settings.keyFile if you want to use interactive password entry

change

```nix
              settings = {
                  allowDiscards = true;
                  keyFile = "/tmp/secret.key";
                };
```

to

```nix
              settings = {
                  allowDiscards = true;
                };
```

so you can enter a password interactively. Alternatively, change the path of the keyFile and generate a keyfile yourself at that location so the partition can be unlocked automatically.

**Comment by codehia** [comment]
Wow that worked!!! Thank you.

Can you tell me where the configuration files are (configuration.nix , flake.nix ) ?

**Comment by codehia** [comment]
@iFreilicht Thank you for the help, it worked!

I had a quick follow-up question, I'm not able to find the configuration file and the flake file. I'm assuming disko is used to install the configuration provided and not transfer the config to the final installation, if so is there any way to generate the configuration files and the flake file based on the current configuration?

**Comment by iFreilicht** [comment]
Great! Hmm, what command did you run to install exactly? Usually the configuration is at `/etc/nixos/configuration.nix`. If not, you can generate the initial config with `nixos-generate-config`, but that won't be the current state, it's just an initial default config based on your hardware.

**Comment by codehia** [comment]
I used this command to install `sudo nix run 'github:nix-community/disko/latest#disko-install' -- --write-efi-boot-entries --flake '/tmp/config/etc/nixos#mymachine' --disk main /dev/nvme0n1`.

I was surprised to see no configuration file in /etc/nixos.

I will use the generate config , but hoping there is a better way

**Comment by codehia** [comment]
I see. I will close this issue and go through the exact steps in the new installation.

Thank you!
