### ISSUE TITLE
Building interactive VM fails with called with unexpected argument 'customQemu'

### ISSUE THREAD

**Issue by Nebucatnetzer** [nix-community/disko#850]
When I try to build the interactive VM with `nix run -L '.#nixosConfigurations.test-raspi.config.system.build.vmWithDisko'`

It fails with the following error. It looks like the `customQemu` argument isn't present in Nixpkgs stable 24.05.
This issue here might me related as well: https://github.com/nix-community/disko/issues/758

```
       error: function 'anonymous lambda' called with unexpected argument 'customQemu'

       at /nix/store/lbqj1cndic4121whnx8xm0jgb1c8x4xx-source/pkgs/build-support/vm/default.nix:1:1:

```

**Comment by Nebucatnetzer** [comment]
`diskoImagesScript` fails in the same way.

**Comment by iFreilicht** [comment]
You're correct, I can reproduce this :+1:  I already have an idea how I can fix it.

**Comment by iFreilicht** [comment]
@Nebucatnetzer  #851 should fix this :)
