### ISSUE TITLE
ntfs example

### ISSUE THREAD

**Issue by eqfae** [nix-community/disko#855]
https://github.com/nix-community/disko/issues/130
想知道最新的示例是怎样的 btrfs winbtrfs 哦已经死机4次了 主要是qb 重装qb依旧 卡在正在关机 只能强制重启
现在我想回到ntfs 并借助disko挂载在linux 
I want to know what kind of latest example is btrfs winbtrfs. It has crashed 4 times. The main reason is that qb is reinstalled. qb is still stuck and is shutting down. You can only force a restart.
Now I want to go back to ntfs and mount it on linux with disko
![图片](https://github.com/user-attachments/assets/620cf7b8-7e2f-4099-b2a0-46522325fda4)
win已经不识别了 不过linux还可以
Win no longer recognizes it, but linux is still okay

双系统 需要一个磁盘能被win和linux稳定读写 主要存视频 qb那些
Dual systems require a disk that can be stably read and written by win and linux, mainly storing videos, qb, etc.

**Comment by Mic92** [comment]
You only want to mount but not format it with disko?

**Comment by eqfae** [comment]
> You only want to mount but not format it with disko?

是要用disko格式化并安装 你们添加硬盘是怎么搞的
It's to format and install it with disko. How did you add the hard drive?
```
      t4 = {
        type = "disk";
        device = "/dev/disk/by-id/ata-ST4000VX000-2AG166_ZGY9N42H";
        content = {
          type = "gpt";
          partitions = {
            root = {
              size = "100%";
              content = {
                type = "btrfs";
                extraArgs = [
                  "--label nixos"
                  "-f"
                  "--csum xxhash64"
                  "--features"
                  "block-group-tree"
                ];
                subvolumes =
                  let
                    commonOptions = [
                      "compress=zstd"
                      "noatime"
                      "lazytime"
                      "discard=async"
                      "space_cache=v2"
                      # "compress-force=zstd" # 无法单独设置 通过mount命令检查
                    ];
                  in
                  {
                    "rootfs" = {
                      mountpoint = "/4t";
                      mountOptions = commonOptions ++ [
                        "nodatacow"
                      ];
                    };
                  };

              };
            };
          };
        };
      };
```
单独拿出这个新硬盘的配置 然后 mode disko 然后再添加到flake 如果直接添加到flake就崩溃了 rebuild
Take out the configuration of this new hard disk separately, then mode disko, and then add it to flake. If you add it directly to flake, it will crash. rebuild

**Comment by iFreilicht** [comment]
I'm sorry, I do not understand what you're trying to say.

What is winbtrfs? What is qb? Why is it a problem that "qb" was reinstalled? What crashed? What was the error message? Why did you link this other issue? How does your config have anything to do with ntfs?

Please provide a proper description of what you tried, with the exact commands you ran, the full configuration and the exact error messages you've encountered.

**Comment by eqfae** [comment]
现在我想回到ntfs 并借助disko挂载在linux
Now I want to go back to ntfs and mount it on linux with disko

需要ntfs的示例 只在问题里找到一份旧的

没有日志不知道在哪看 无法关机 卡在正在关机

Examples that require ntfs only find an old copy in the question
There is no log. I don't know where to read it. I can't shut it down. It's stuck. It's shutting down.

**Comment by iFreilicht** [comment]
I've tried to translate the Chinese text with deepl, but this gives a similar result to your translation.

I'm sorry to say that I can't help you. Please provide a proper explanation and a full configuration file like I explained, otherwise I will close this issue.

**Comment by Mic92** [comment]
Maybe you can ask someone on the Chinese Matrix disko channel? #nixos-zhcn:nichi.co

**Comment by eqfae** [comment]
> @eqfae Maybe you can ask someone on the Chinese Matrix disko channel? #nixos-zhcn:nichi.co

好久了 我要的是ntfs示例没有就算了
It's been a long time. I want the ntfs example. If it's not there, forget it.
