### ISSUE TITLE
FEATURE | TPM decryption option

### ISSUE THREAD

**Issue by Sk7Str1pe** [nix-community/disko#861]
TPM became very popular tool for encryption, providing security and ease of usage. I wish I could declare usage of TPM for root/other disk decryption in Disko configurations

**Comment by Mic92** [comment]
It should be possible to use `postCreateHook` like this in example https://github.com/nix-community/disko/blob/856a2902156ba304efebd4c1096dbf7465569454/example/zfs.nix#L58
but using `systemd-cryptenroll` to the TPM as an encryption provider.

**Comment by iFreilicht** [comment]
I agree, this would be a great feature! Basically a new option in [LUKS](https://github.com/nix-community/disko/blob/master/lib/types/luks.nix), something like `enrollTPM` maybe? I'd say a PR that implements this properly with tests would be accepted.
The one criterion would be that this has to be compatible with the existing `keyFile`, `askPassword` etc. options so that you can set a backup mechanism if needed.

**Comment by Sk7Str1pe** [comment]
>  I'd say a PR that implements this properly with tests would be accepted. 
If so I'll try to implement this, wait PR in a week.

**Comment by Sk7Str1pe** [comment]
@iFreilicht I came up with idea of enrolling. Since we cannot add token in live environment, we must do this in installed system. So my idea, if tpmEnroll is set to true in disko configuration, it will create a systemd service which would call systemd-enroll command and, after success, disable itself. This seems to be only solution, is it possible?

**Comment by iFreilicht** [comment]
As discovered in #866, this is not possible to handle for disko.

Enrolling TPM into a LUKS partition is indeed done by `systemd-cryptenroll`, but the nature of TPM prevents this from being done while the installer image is loaded. The following explanation can be verified by referring to [the systemd-cryptenroll(1) manpage](https://man.archlinux.org/man/systemd-cryptenroll.1) and the [article on TPM in the Archwiki](https://wiki.archlinux.org/title/Trusted_Platform_Module):

When a TPM is enrolled into a LUKS partition, the state of one or more TPM PCRs (Platform Configuration Registers) is  written into a new keyslot. The PCRs record (also called "measure") different variables of the system state, one of the most important ones (and the default for `systemd-cryptenroll --tpm-device` being PCR7, which records the Secure Boot status. It contains a list of all bootloaders (and the certificates they were signed with) that participated in the current boot.

This means that this register changes if any of the bootloaders change, which in turn means that the content of this register **is different when running the installer image and when booting the installed system**, so if we were to add an option to enroll a TPM during installation, it would fail to unlock the LUKS partition after rebooting.

PCR7 would also change on every update to  `systemd-boot`, which might leave a user unable to reboot a headless machine after a system update, as sytemd-boot is the one thing we can't revert if boot Other PCRs measure other variables, PCR9 for example records the hashes of all initrds the kernel received during startup.

It might be possible to use PCR15, which measures various values related to connected drives and partitions.

**Comment by iFreilicht** [comment]
@Sk7Str1pe Hmm, that's an interesting suggestion. I do think there's a bit of a usability issue with this, though.

On the installation, it will be fine for the user to leave the USB drive with the `keyFile` plugged in until after the reboot is done or to type in the passphrase. With a passphrase, there is an issue that you might have to type the password in two times (first to unlock the disk, and then a second time to enroll the TPM), and I don't see a good way around that, but maybe this inconvenience is worth the security.

However, as I wrote above, the TPM registers can change even after an installation when `systemd-boot` is updated (or, if you want to utilize additional PCRs, if the kernel or BIOS firmware are updated). This means that we can face a similar issue after every system upgrade!

So maybe I jumped to conclusions a little when saying that it's impossible.

Indeed, a systemd service could be the solution, but it should not disable itself after the first installation. Instead, it needs to run on every boot, ideally *before* the system becomes fully operational, but *after* the LUKS partitions have been unlocked, then it needs to check somehow if it's possible to unlock the LUKS partitions with the TPM, and if that fails, enroll the TPM again.

This is relatively easy if the user has set a passphrase: You just ask them again. But if the user only provided a `keyFile`, and the keyFile is on a USB drive, the systemd service would need to be tell the user that it's missing the keyFile and retry every 5 seconds or so to see if it's available. This allows the user to plug in the usb drive the keyFile was on. However, the user also needs to be able to skip this prompt and re-enroll the TPM manually later (maybe the keyFile is on a network drive, it has to be unlocked with another passphrase, etc.)

All of this is *A LOT* of work to automate something that you can already get as a user by simply typing `systemd-cryptenroll --tpm-device=auto`.

While it's possible, I'm sure there will be additional edge-cases we can't think of right now, so there will be quite a bit of maintenance burden, and I don't think disko is the correct place for much of this functionality.

However, all of this TPM functionality could be implemented in nixpkgs first. If NixOS has a robust way to declaratively enroll TPMs for LUKS partitions, then I think it would be reasonable for disko to add an option as well to make this easier.

# Summary

For now, this is out-of-scope for us. If anyone finds this issue in the future and NixOS indeed implemented declarative TPM enrollment, comment here and re-open the issue.

If you just want to enroll a TPM so you don't have to type your passphrase every time on boot, simply run `systemd-cryptenroll --tpm-device=auto`. Be aware of the limitations and refer to the articles linked above!
