### ISSUE TITLE
passwordFile unlocking immediately fails after providing a password

### ISSUE THREAD

**Issue by JimmJam** [nix-community/disko#872]
I've had good success in creating a disk with all the partitions I would need for a working system using [this](https://github.com/user-attachments/files/17712962/default.txt) config. However, when attempting to boot into the config, I am immediately faced with this error stating that Cryptography Setup failed for my disk, leaving the system unable to find the subsequent LVM partitions.
![image](https://github.com/user-attachments/assets/3af29d0a-b074-431d-ba36-fe3e2e2fb619)

I am using disko-install to set up the drive, attached via USB. The LUKS partition is created successfully, and I am able to successfully use the partuuid to unlock, mount, chroot into, interact, and rebuild the system. The password works as intended everywhere except right here, where the password inexplicably fails and I have no clue why.

Removing and adding a new password from the partition also does not solve the problem. This does NOT occur on an identically partitioned, subpartitioned and labeled drive that was migrated into disko rather than being created with it.

Any ideas?

**Comment by Mic92** [comment]
Please try including the all-hardware.nix profile and check if this solves your problem. My current suspicions is that your hardware-configuration.nix doesn't contain the usb driver for your external drive.

**Comment by JimmJam** [comment]
Was worth a shot, but no dice. I'm running this under QEMU to test, and while I think that solves an issue I was having on my laptop when testing the drive directly (not being prompted for a password at all), I'm still being prompted for the password, and being notified that the drive _was_ found, leaving me very confused.

[hardware.nix](https://github.com/user-attachments/files/17713389/hardware.txt)

![image](https://github.com/user-attachments/assets/3c5a5b31-3251-4f0b-8e88-1a2b9e6141a9)
