### ISSUE TITLE
Is customizing partlabel name generation scheme possible?

### ISSUE THREAD

**Issue by bbaserdem** [nix-community/disko#875]
I'm trying to transition to disko instead of manually partitioning my filesystem. So far a wall I hit is being able to influence the partlabels naming scheme. Currently, the partlabels seems to be named using `disko.devices.disk.MYDISK.type`. Which I don't have a way of influencing, since the config option is from a list.

Is there a way to influence the naming scheme? I can't find in the codebase where exactly the partlabels are generated, besides a reference in [docs/table-to-gpt.md](https://github.com/nix-community/disko/blob/master/docs/table-to-gpt.md)

**Comment by bbaserdem** [comment]
I realized that the related setting is defined  [here](https://github.com/nix-community/disko/blob/9c7de5582ed980715a87fdb60c15e3d59cc750dd/lib/types/gpt.nix#L70). Partitions have a label setting that can be changed.

**Comment by iFreilicht** [comment]
We're working on auto-generating docs for all the types so this should be easier to find out in the future. Glad you found it!
