### ISSUE TITLE
Using lib.makeDiskoTest in my own flake

### ISSUE THREAD

**Issue by johnjameswhitman** [nix-community/disko#881]
I'm working on cleaning up my NixOS configs, and am curious about running some of my own integration tests in CI. I'm also planning to use disko, so was thinking it might be nice to use `lib.makeDiskoTest` with my own layout instead of NixOS's `runNixOSTest`.

Using Disko's own flake checks as inspiration I've got something that's half-working by accessing `disko.lib.makeDiskoTest` directly within my flake; however, doing it this way requires running `nix flake check` with the `--impure` option, which doesn't seem ideal.

When I try to import `lib` like below (my flake is here: https://github.com/johnjameswhitman/kipos/pull/4/files#r1844406285), it fails with an error:

> error: cannot coerce a set to a string: { config = «thunk»; create = «thunk»; createScript = «thunk»; createScriptNoDeps = «thunk»; deepMergeMap = «thunk»; defineHookVariables = «thunk»; deviceList = «thunk»; deviceNumbering = «thunk»; deviceType = «thunk»; disko = «thunk»; «34 attributes elided» }

```nix
    makeTest = import (pkgs.path + "/nixos/tests/make-test-python.nix");
    eval-config = import (pkgs.path + "/nixos/lib/eval-config.nix");
    lib = pkgs.lib;
    diskoLib = import disko.lib { inherit lib makeTest eval-config; };
``` 

Any idea why that might be?

**Comment by iFreilicht** [comment]
You figured out a lot on your own already, props for that!

There's just two pieces missing:

> error: cannot coerce a set to a string: { config = «thunk»; create = «thunk»; createScript = «thunk»; createScriptNoDeps = «thunk»; deepMergeMap = «thunk»; defineHookVariables = «thunk»; deviceList = «thunk»; deviceNumbering = «thunk»; deviceType = «thunk»; disko = «thunk»; «34 attributes elided» }

It's exactly as the error says: `disko.lib` is a set, not a string, but to import something you need to pass a string. You need to do something similar like with `pkgs.path`, except the disko flake doesn't have such an attribute. Instead, you can just append a string to the flake input itself. This will coerce the input into a string.

```
      diskoLib = import (disko + "/lib") { inherit lib makeTest eval-config; };
```

This alone will not be enough; if you now run `nix build .#checks.x86_64-linux.silverAlt` it will download another version of nixpkgs and then end with this:

```
       … while calling the 'findFile' builtin
         at /nix/store/2927l33kdrl0qwzcjks6mrhg7zp6zd2h-source/lib/tests.nix:48:24:
           47|       , extendModules ? null
           48|       , pkgs ? import <nixpkgs> { }
             |                        ^
           49|       , extraTestScript ? ""

       error: cannot look up '<nixpkgs>' in pure evaluation mode (use '--impure' to override)
```

You can fix this by changing the way you invoke `makeTest`:

```
silverAlt = diskoLib.testLib.makeDiskoTest ((import ./tests/silver.nix) // { inherit pkgs; });
```

Now it evaluates, though I didn't run the entire test.

----

This a bit awkward, but I'm not sure if it is fixable. We use `pkgs ? import <nixpkgs>` pretty extensively in many files, but maybe we could eliminate it in some cases? If someone wants to try, feel free :)

**Comment by johnjameswhitman** [comment]
Pleased to say it worked :tada: For posterity, here's are the:
- Run: https://github.com/johnjameswhitman/kipos/actions/runs/12093133627/job/33723758480#step:8:19
- Flake: https://github.com/johnjameswhitman/kipos/blob/3e8fa2a975770ca5147f90ce7e79b6a360272054/flake.nix#L47

Gonna clean up my PR, and play around more with Disko in the mean time. Thanks so much for your help :pray:
