### ISSUE TITLE
disko-install - where did the configuration go?

### ISSUE THREAD

**Issue by tim-elmer** [nix-community/disko#908]
This may be my lack of experience with NixOS talking, but after running `disko-install` as described by [the docs](https://github.com/nix-community/disko/blob/master/docs/disko-install.md) to install to the local machine, I expect the flake's `configuration.nix` to get applied to the new installation - which it is. However, once booted into the resulting installation, the expected `/etc/nixos/configuration.nix` file is absent.

Is this the expected behavior, or did I do something wrong? It seems to me that it'd be desirable to still have the configuration file for modifications and/or troubleshooting.

Actual command:
```
nix --extra-experimental-features nix-command --extra-experimental-features flakes run 'github:nix-community/disko/latest#disko-install' -- --mode format --write-efi-boot-entries --flake '/tmp/config/etc/nixos#mymachine' --disk system /dev/vda
```

`flake.nix`:
```
{
  inputs.nixpkgs.url = "github:nixos/nixpkgs?ref=nixos-unstable";
  inputs.disko.url = "github:nix-community/disko/latest";
  inputs.disko.inputs.nixpkgs.follows = "nixpkgs";

  outputs = { self, disko, nixpkgs }: {
    nixosConfigurations.mymachine = nixpkgs.legacyPackages.x86_64-linux.nixos [
      ./configuration.nix
      disko.nixosModules.disko
      {
        disko.devices = {
          disk = {
            system = {
              type = "disk";
              content = {
                type = "gpt";
                partitions = {
                  esp = {
                    size = "512M";
                    type = "EF00";
                    content = {
                      type = "filesystem";
                      format = "vfat";
                      mountpoint = "/boot";
                      mountOptions = [ "umask=0077" ];
                    };
                  };
                  swap = {
                    size = "4G";
                    content = { type = "swap"; };
                  };
                  nix = {
                    size = "100%";
                    content = {
                      type = "filesystem";
                      format = "ext4";
                      mountpoint = "/";
                    };
                  };
                };
              };
            };
          };
        };
      }
    ];
  };
}
```

**Comment by Mic92** [comment]
Yes. This is expected behavior. `nixos-install` also doesn't write `/etc/nixos/configuration.nix`, nixos-generate-config does. However with disko, any configuration written by `nixos-generate-config` would get vanished the re-partitioning.

**Comment by Enzime** [comment]
A lot of people use [this module](https://github.com/gytis-ivaskevicius/flake-utils-plus/blob/master/lib/options.nix#L24) to copy their flake to `/etc/nix/inputs/self`
