### ISSUE TITLE
Formatting drive hangs

### ISSUE THREAD

**Issue by LUK3ARK** [nix-community/disko#919]
So I simply just have a deploy script, I run NixOS anywhere, when it gets to this stage, it just hangs here indefinitely... the last output is always lsblk.

This just started happening randomly one day and have not been able to fix it since

Previously, I could redeploy many many times a day and it was fine. Then one day, in the last 2-3 weeks, it just doesn't get past this point.

I have a second server and tried to deploy to that, and now the same thing happens there.

```
to the list of known hosts.
+ step Formatting hard drive with disko
+ echo '### Formatting hard drive with disko ###'
### Formatting hard drive with disko ###
+ runSsh /nix/store/dy7irz45kxyrh3q2g1kbz8ari01jirvh-disko
+ ssh -t -i /tmp/tmp.eKjpDWZHal/nixos-anywhere -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no root@my.ip/nix/store/dy7irz45kxyrh3q2g1kbz8ari01jirvh-disko
Warning: Permanently added 'my.ip' (ED25519) to the list of known hosts.
umount: /mnt: not mounted
++ realpath /dev/nvme0n1
+ disk=/dev/nvme0n1
+ lsblk -a -f
```

When I check on the server I am deploying to, I run lsblk and everything is fine no hardware issues no software issues. I'm pretty sure this doesn't have that much to do with the root issue.

Are there any reasons why this would hang? Every time I deploy to any server the same thing happens...

Here is my disko config (specific for one server):
```

{ lib, ... }:
{
  disko.devices = {
    disk = {
      nvme0 = {
        imageSize = "447G";
        device = lib.mkDefault "/dev/nvme0n1";
        type = "disk";
        content = {
          type = "gpt";
          partitions = {
            ESP = {
              name = "EFI_SYSPART";
              size = "512M";
              type = "EF00";
              content = {
                type = "filesystem";
                format = "vfat";
                mountpoint = "/boot/efi";
                mountOptions = [ "defaults" "noatime" ];
              };
            };
            boot = {
              name = "boot";
              size = "1G";
              type = "EF02";
              content = {
                type = "filesystem";
                format = "ext4";
                mountpoint = "/boot";
                mountOptions = [ "defaults" "noatime" ];
              };
            };
            swap = {
              name = "swap";
              size = "64G";  # Combined swap size
              content = {
                type = "swap";
                randomEncryption = false;
              };
            };
            root = {
              name = "root";
              size = "100%";
              content = {
                type = "filesystem";
                format = "ext4";
                mountpoint = "/";
                mountOptions = [ "defaults" "noatime" ];
              };
            };
          };
        };
      };
    };
  };
}

```

**Comment by Lassulus** [comment]
hmm maybe it's an MTU issue. could you try playing around with that? if not, can you run the ssh -t line manually and check if it fails again? maybe also post the content of the generated disko script

**Comment by Mic92** [comment]
Are you using a VPN for deploying?

**Comment by LUK3ARK** [comment]
I will try around with MTU and that right now

+ no VPN used when deploying

**Comment by Mic92** [comment]
If it was MTU, I would have expected to see the error also when accessing the machine with normal ssh actually.

**Comment by LUK3ARK** [comment]
so, if i run the ssh -t line manually:

`[ark@nixos:~/Projects/nix-lib]$ ssh -t root@ip "$(cat result)"
umount: /mnt: not mounted
++ realpath /dev/nvme0n1
+ disk=/dev/nvme0n1
+ lsblk -a -f
NAME    FSTYPE   FSVER LABEL UUID FSAVAIL FSUSE% MOUNTPOINTS
loop0   squashfs 4.0                    0   100% /nix/.ro-store
loop1   erofs                           0   100% /run/etc-metadata
loop2
loop3
loop4
loop5
loop6
loop7
nvme0n1
nvme1n1
nvme2n1
nvme3n1
+ lsblk --output-all --json
+ bash -x
++ dirname /nix/store/3ys93zsghig63qpcs67vc37x0rwn1zhl-disk-deactivate/disk-deactivate
+ jq -r --arg disk_to_clear /dev/nvme0n1 -f /nix/store/3ys93zsghig63qpcs67vc37x0rwn1zhl-disk-deactivate/disk-deactivate.jq
+ set -fu
++ type zdb
++ zdb -l /dev/nvme0n1
++ sed -nr 's/ +name: '\''(.*)'\''/\1/p'
+ zpool=
+ [[ -n '' ]]
+ unset zpool
++ lsblk /dev/nvme0n1 -l -p -o type,name
++ awk 'match($1,"raid.*") {print $2}'
+ md_dev=
+ [[ -n '' ]]
+ wipefs --all -f /dev/nvme0n1
+ dd if=/dev/zero of=/dev/nvme0n1 bs=440 count=1
1+0 records in
1+0 records out
440 bytes copied, 0.00018051 s, 2.4 MB/s
+ lsblk -a -f
NAME    FSTYPE   FSVER LABEL UUID FSAVAIL FSUSE% MOUNTPOINTS
loop0   squashfs 4.0                    0   100% /nix/.ro-store
loop1   erofs                           0   100% /run/etc-metadata
loop2
loop3
loop4
loop5
loop6
loop7
nvme0n1
nvme1n1
nvme2n1
nvme3n1
++ mktemp -d
+ disko_devices_dir=/tmp/tmp.WJCgUFTmXa
+ trap 'rm -rf "$disko_devices_dir"' EXIT
+ mkdir -p /tmp/tmp.WJCgUFTmXa
+ device=/dev/nvme0n1
+ imageName=nvme0
+ imageSize=447G
+ name=nvme0
+ type=disk
+ device=/dev/nvme0n1
+ efiGptPartitionFirst=1
+ type=gpt
+ blkid /dev/nvme0n1
+ sgdisk --clear /dev/nvme0n1
Creating new GPT entries in memory.
The operation has completed successfully.
+ sgdisk --align-end --new=1:0:+1G --change-name=1:disk-nvme0-boot --typecode=1:EF02 /dev/nvme0n1
The operation has completed successfully.
+ partprobe /dev/nvme0n1
+ udevadm trigger --subsystem-match=block
+ udevadm settle
+ sgdisk --align-end --new=2:0:+512M --change-name=2:disk-nvme0-EFI_SYSPART --typecode=2:EF00 /dev/nvme0n1
The operation has completed successfully.
+ partprobe /dev/nvme0n1
+ udevadm trigger --subsystem-match=block
+ udevadm settle
+ sgdisk --align-end --new=3:0:+64G --change-name=3:disk-nvme0-swap --typecode=3:8200 /dev/nvme0n1
The operation has completed successfully.
+ partprobe /dev/nvme0n1
+ udevadm trigger --subsystem-match=block
+ udevadm settle
+ sgdisk --align-end --new=4:0:-0 --change-name=4:disk-nvme0-root --typecode=4:8300 /dev/nvme0n1
The operation has completed successfully.
+ partprobe /dev/nvme0n1
+ udevadm trigger --subsystem-match=block
+ udevadm settle
+ device=/dev/disk/by-partlabel/disk-nvme0-boot
+ extraArgs=()
+ declare -a extraArgs
+ format=ext4
+ mountOptions=('defaults' 'noatime')
+ declare -a mountOptions
+ mountpoint=/boot
+ type=filesystem
+ blkid /dev/disk/by-partlabel/disk-nvme0-boot
+ grep -q TYPE=
+ mkfs.ext4 /dev/disk/by-partlabel/disk-nvme0-boot
mke2fs 1.47.1 (20-May-2024)
Discarding device blocks: done
Creating filesystem with 262144 4k blocks and 65536 inodes
Filesystem UUID: 6364db76-e67e-43a6-87d7-e63c84eecd06
Superblock backups stored on blocks:
	32768, 98304, 163840, 229376

Allocating group tables: done
Writing inode tables: done
Creating journal (8192 blocks): done
Writing superblocks and filesystem accounting information: done

+ device=/dev/disk/by-partlabel/disk-nvme0-EFI_SYSPART
+ extraArgs=()
+ declare -a extraArgs
+ format=vfat
+ mountOptions=('defaults' 'noatime')
+ declare -a mountOptions
+ mountpoint=/boot/efi
+ type=filesystem
+ blkid /dev/disk/by-partlabel/disk-nvme0-EFI_SYSPART
+ grep -q TYPE=
+ mkfs.vfat /dev/disk/by-partlabel/disk-nvme0-EFI_SYSPART
mkfs.fat 4.2 (2021-01-31)
+ device=/dev/disk/by-partlabel/disk-nvme0-swap
+ discardPolicy=
+ extraArgs=()
+ declare -a extraArgs
+ mountOptions=('defaults')
+ declare -a mountOptions
+ priority=
+ randomEncryption=
+ resumeDevice=
+ type=swap
+ blkid /dev/disk/by-partlabel/disk-nvme0-swap -o export
+ grep -q '^TYPE='
+ mkswap /dev/disk/by-partlabel/disk-nvme0-swap
Setting up swapspace version 1, size = 64 GiB (68719472640 bytes)
no label, UUID=5b471ac4-c767-44c3-bc59-2adfc9c0ba01
+ device=/dev/disk/by-partlabel/disk-nvme0-root
+ extraArgs=()
+ declare -a extraArgs
+ format=ext4
+ mountOptions=('defaults' 'noatime')
+ declare -a mountOptions
+ mountpoint=/
+ type=filesystem
+ blkid /dev/disk/by-partlabel/disk-nvme0-root
+ grep -q TYPE=
+ mkfs.ext4 /dev/disk/by-partlabel/disk-nvme0-root
mke2fs 1.47.1 (20-May-2024)
Discarding device blocks: done
Creating filesystem with 100041984 4k blocks and 25018368 inodes
Filesystem UUID: fd792b44-43cc-4646-aabe-faee896bd771
Superblock backups stored on blocks:
	32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632, 2654208,
	4096000, 7962624, 11239424, 20480000, 23887872, 71663616, 78675968

Allocating group tables: done
Writing inode tables: done
Creating journal (262144 blocks): done
Writing superblocks and filesystem accounting information: done

+ set -efux
+ device=/dev/nvme0n1
+ imageName=nvme0
+ imageSize=447G
+ name=nvme0
+ type=disk
+ device=/dev/nvme0n1
+ efiGptPartitionFirst=1
+ type=gpt
+ device=/dev/nvme0n1
+ imageName=nvme0
+ imageSize=447G
+ name=nvme0
+ type=disk
+ device=/dev/nvme0n1
+ efiGptPartitionFirst=1
+ type=gpt
+ device=/dev/disk/by-partlabel/disk-nvme0-root
+ extraArgs=()
+ declare -a extraArgs
+ format=ext4
+ mountOptions=('defaults' 'noatime')
+ declare -a mountOptions
+ mountpoint=/
+ type=filesystem
+ findmnt /dev/disk/by-partlabel/disk-nvme0-root /mnt/
+ mount /dev/disk/by-partlabel/disk-nvme0-root /mnt/ -t ext4 -o defaults -o noatime -o X-mount.mkdir
+ device=/dev/nvme0n1
+ imageName=nvme0
+ imageSize=447G
+ name=nvme0
+ type=disk
+ device=/dev/nvme0n1
+ efiGptPartitionFirst=1
+ type=gpt
+ device=/dev/disk/by-partlabel/disk-nvme0-boot
+ extraArgs=()
+ declare -a extraArgs
+ format=ext4
+ mountOptions=('defaults' 'noatime')
+ declare -a mountOptions
+ mountpoint=/boot
+ type=filesystem
+ findmnt /dev/disk/by-partlabel/disk-nvme0-boot /mnt/boot
+ mount /dev/disk/by-partlabel/disk-nvme0-boot /mnt/boot -t ext4 -o defaults -o noatime -o X-mount.mkdir
+ device=/dev/nvme0n1
+ imageName=nvme0
+ imageSize=447G
+ name=nvme0
+ type=disk
+ device=/dev/nvme0n1
+ efiGptPartitionFirst=1
+ type=gpt
+ device=/dev/disk/by-partlabel/disk-nvme0-EFI_SYSPART
+ extraArgs=()
+ declare -a extraArgs
+ format=vfat
+ mountOptions=('defaults' 'noatime')
+ declare -a mountOptions
+ mountpoint=/boot/efi
+ type=filesystem
+ findmnt /dev/disk/by-partlabel/disk-nvme0-EFI_SYSPART /mnt/boot/efi
+ mount /dev/disk/by-partlabel/disk-nvme0-EFI_SYSPART /mnt/boot/efi -t vfat -o defaults -o noatime -o X-mount.mkdir
+ device=/dev/nvme0n1
+ imageName=nvme0
+ imageSize=447G
+ name=nvme0
+ type=disk
+ device=/dev/nvme0n1
+ efiGptPartitionFirst=1
+ type=gpt
+ device=/dev/disk/by-partlabel/disk-nvme0-swap
+ discardPolicy=
+ extraArgs=()
+ declare -a extraArgs
+ mountOptions=('defaults')
+ declare -a mountOptions
+ priority=
+ randomEncryption=
+ resumeDevice=
+ type=swap
+ test '' '!=' 1
+ swapon --show
++ readlink -f /dev/disk/by-partlabel/disk-nvme0-swap
+ grep -q '^/dev/nvme0n1p3 '
+ swapon --options=defaults /dev/disk/by-partlabel/disk-nvme0-swap
+ rm -rf /tmp/tmp.WJCgUFTmXa`

**Comment by LUK3ARK** [comment]
[root@nixos-installer:~]# ps aux | grep lsblk
root       12716  0.0  0.0   6732  2428 pts/0    S+   11:15   0:00 grep lsblk

i checked this before as well process always end fine...

**Comment by LUK3ARK** [comment]
I think that might of worked?? It has got on to the build step again I will update

**Comment by Mic92** [comment]
Are you running nixos-anywhere in an interactive terminal or in some sort of CI or script?

**Comment by LUK3ARK** [comment]
yep thats exactly what I had trouble with similar before and just carried over SSH_AUTH_SOCK I guess I was just unaware of the actual issue!
