### ISSUE TITLE
Multi-device btrfs support

### ISSUE THREAD

**Issue by accelbread** [nix-community/disko#99]
Are multi-disk btrfs filesystems already supported?

I see where I could add additional options to mkfs, so that can be used to pass the other devices and the raid options. However, I can't see how to create the other backing devices, and how to make the dependency such that the backing devices will all be created before the mkfs.

**Comment by Mic92** [comment]
cc @lilyinstarlight

**Comment by lilyinstarlight** [comment]
What type of backing devices? I've not used multidevice btrfs before but I thought you only needed the one mkfs command without anything special before it

**Comment by accelbread** [comment]
Yes, to make a multidevice btrfs filesystem, you use a command like follows:
```
mkfs.btrfs -m raid1 -d raid1 /dev/device1 /dev/device2
```

Looking at the source of this module, I can make that happen by configuring device1 and adding "-m dup -d dup /dev/device2" as extra mkfs options.

However, before the mkfs.btrfs is run, the devices have to be ready. I use LVM on LUKs on all my disks and use a lv on each disk as the devices for the btrfs volume. Thus the btrfs filesystem depends on both disk's logical volumes. Adding that dependency is what I could not figure out

**Comment by accelbread** [comment]
If it helps, my current disk setup is here: https://github.com/accelbread/config-flake/tree/master/nixos/common/disks

**Comment by lilyinstarlight** [comment]
Yeah I was worried you were gonna say something like that

As disko is right now, it creates LVs in lexographical order, so as long as you put the `type = "btrfs"` content in the last lv alphabetically, they should all be created by that point and it will technically work to provision. I think you only need to mount one device for btrfs to get all of them, so it should even work with the NixOS config part too like that

As it is right now though, I don't think there is an explicit way to order devices by dependency (#80 is related) and there is definitely no expicit multi-device btrfs support (that would probably have to be its own top-level type like VGs are now, but given mounting only needs to happen for one device anyway, the `extraArgs` kludge is probably sufficient)

**Comment by accelbread** [comment]
Thanks; that answers my question, so I'll close the issue.
